### ISSUE TITLE
Sprockets 3.0.0.rc QA

### ISSUE THREAD

**Issue by josh** [rails/sprockets#10]
I think I'm ready to call 3.0 done. I don't know of any blockers, so heres you chance to tell me!

Production apps running 3.0.0.beta.10 (will be rc1)

* [x] github.com
* [ ] basecamp.com
* [ ] rubygems.org

A few people mentioned they testing the Sprockets betas. Let me know if theres any other interesting apps.

/cc @jeremy @sstephenson @rafaelfranca @arthurnn

**Comment by rafaelfranca** [comment]
I know @jeremy and @lucasmazza had problems trying sprockets 3 betas with
sprockets-rails and sass-rails master branches. But it is more a bug on
sprockets-rails related with the after initialize change we did. sass-rails
was expecting app.assets to be available in a initializer but it is only
available after the initializers run.

**Comment by lucasmazza** [comment]
@rafaelfranca :+1: the `Sass::Rails::*Template` were no longer injected in the Sprockets configuration (https://github.com/rails/sass-rails/blob/master/lib/sass/rails/railtie.rb#L56-L62) and dir globbing wasn't working.

I also tried adding sprockets-es6 to our app but the es6 files weren't being compiled correctly. I can redo the tests this week and report back here.

**Comment by josh** [comment]
> I also tried adding sprockets-es6 to our app but the es6 files weren't being compiled correctly. I can redo the tests this week and report back here.

Thats probably this known issue with sprockets-es6 https://github.com/josh/sprockets-es6/issues/9

**Comment by josh** [comment]
> But it is more a bug on
> sprockets-rails related with the after initialize change we did. sass-rails
> was expecting app.assets to be available in a initializer but it is only
> available after the initializers run.

I think those `app.assets` accesses need to happen within a `config.assets.configure` block to ensure they run after its initialized. That should just be a specific issue with sprockets-rails which isn't going to be released quite yet. The current sprockets-rails 2.x stable branch should work fine with sprockets 3.x. But yeah, we should still get that fixed of course.

**Comment by lucasmazza** [comment]
I'm trying to test the branch from rails/sass-rails#316 but seems that the sprockets `beta.9` broke how `sass-rails`/`sass` are required by the application:

```
$ bundle list | grep sprockets; DISABLE_SPRING=1 bin/rails r 'puts Rails.configuration.sass'
  * sprockets (2.12.3)
  * sprockets-rails (2.2.4)
{:preferred_syntax=>:scss, :cache=>true, :read_cache=>true, :line_comments=>true, :load_paths=>[], :logger=>#<Sass::Rails::Logger:0x007f8669c1dda0 @log_level=:debug>, :cache_location=>"/private/tmp/thing/tmp/cache/sass", :full_exception=>true, :style=>:expanded}
```

with latest sprockets/sprockets-rails
```
$ bundle list | grep sprockets; DISABLE_SPRING=1 bin/rails r 'puts Rails.configuration.sass'
  * sprockets (3.0.0.beta.9)
  * sprockets-rails (3.0.0.beta1 0159123)
/opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `sass' for #<Rails::Application::Configuration:0x007fba84278cd8> (NoMethodError)
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/runner.rb:62:in `eval'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Downgrading sprockets to `3.0.0.beta.8` restores the expected behaviour.

**Comment by josh** [comment]
@lucasmazza found a sprockets bug with `depend_on` with a directory. Checking it out.

**Comment by lucasmazza** [comment]
@josh was diving through the error stack and noticed that - seems like it no longer supports passing a directory path.

**Comment by josh** [comment]
@lucasmazza directory issue fixed in 896f93c79a024ff70e307c84c49aba227f7f7b87

**Comment by lucasmazza** [comment]
@josh sass-rails globbing working with master sprockets/sprockets-rails/sass-rails :+1: great work.

**Comment by rafaelfranca** [comment]
OMG! Went out some hours and you already fixed everything :heart:

**Comment by elia** [comment]
Added 3 beta testing to @opal build matrix:

https://travis-ci.org/opal/opal/jobs/55460677

The two failure are due to our use of internal APIs I think, so shame on me, but I'd like to see if there's a better solution before branching on sprockets version in the code.

Use of AssetAttributes to check if an asset has been processed by Opal
https://github.com/opal/opal/blob/sprockets-3/lib/opal/sprockets/processor.rb#L94-L95

Something with `Hike::Trail` not returning `nil` for unknown paths anymore
https://github.com/opal/opal/blob/sprockets-3/lib/opal/path_reader.rb#L16
https://github.com/opal/opal/blob/sprockets-3/lib/opal/hike_path_finder.rb#L12-L16

cc @adambeynon

**Comment by josh** [comment]
@elia yeah, I'd love to take a look at the private api use cases. Hopefully we can have something exposed here properly that you can rely on going forward to 4.x.

**Comment by josh** [comment]
> Use of AssetAttributes to check if an asset has been processed by Opal

Could you just check if the filename ends in `.rb`? Just curious what the `load_asset_code` does?

> Something with Hike::Trail not returning nil for unknown paths anymore

Sprockets 3.x no longer depends on or requires hike. I wonder if some other version changes are happening there.

**Comment by elia** [comment]
> `AssetAttributes`

The check works for any engine inheriting from Opal::Processor (e.g. OpalERB, opal-haml, …) maybe I can change it to an extensions register.

> `load_asset_code`

In 0.7 we introduced "real requires", all opal files are registered to `Opal.modules` and then calls to `Kernel#require` will load the code at runtime, all but the first one which needed to be loaded to bootstrap the whole thing. Due to broken source-maps (concatenation is not that easy after all) and to the realization that we were partially reimplementing sprockets [I did what I didn't want to do](https://github.com/opal/opal-rails/blob/master/app/helpers/opal_helper.rb#L8-L19).

Now on master (will be 0.8) the sprockets processor will always register files to `Opal.modules` so some bootstrapping code is needed externally, to:

1. load the base/manifest file
2. mark non-opal assets as already required (will add them to `$LOADED_FEATURES` inside opal) so that `Kernel#require` doesn't fail.

> Hike

I'll check it and probably just lock to the working version

**Comment by elia** [comment]
> I did what I didn't want to do

just to be more explicit, `include_javascript_tag` is being overloaded by opal-rails by adding the bootstrapping code after calling `super`, AFAIK there's no way to do that in sprockets, but I'd love to be proved wrong :smiley_cat:

**Comment by rafaelfranca** [comment]
@josh should the manifest files being compiled and add to public since they don't generate any output?

I'm asking because they will be usually contains just `link`directives and the generated file will be empty.

**Comment by josh** [comment]
> should the manifest files being compiled and add to public since they don't generate any output?

I think its harmless at least. I was planning for one day add some sort of JS bundle mapping to them for the future ES6 modules stuff. Thats still a ways off.

Did you hit any issues with an empty file being compiled?

**Comment by rafaelfranca** [comment]
> Did you hit any issues with an empty file being compiled?

Not, just a question. I was rereading the discussion at Basecamp and saw the JS bundle mapping proposal.

**Comment by josh** [comment]
Any objections to tagging a `v3.0.0.rc.1`?

**Comment by lucasmazza** [comment]
:shipit:

**Comment by josh** [comment]
Released 3.0.0 RC1!!!

**Comment by lucasmazza** [comment]
:+1: we should cut new releases of `sprockets-rails` and `sass-rails` too.

**Comment by josh** [comment]
The currently published sprockets-rails 2.2.4 and sass-rails 5.0.1 should support sprockets 3.0.0 already. Maybe we should update the travis matrixes though, just to run against the RC.

**Comment by lucasmazza** [comment]
@josh sass-rails requires rails/sass-rails#319 to work with sprockets 3.

**Comment by josh** [comment]
@lucasmazza ah, thanks. I think @rafaelfranca got that out in sass-rails 5.0.2.
