### ISSUE TITLE
End user assets

### ISSUE THREAD

**Issue by thelucid** [rails/sprockets#107]
Apologies if this is the wrong place to ask such a question but I can't see any links to mailing list etc.

Would Sprockets be usable in an end-user scenario i.e. where the end user can edit stylesheets stored in a database. Would there be any security concerns for example compiling SASS via sprockets as long as ERB wasn't enabled? ...or Javascript requirements as another example?

**Comment by schneems** [comment]
This would not be an appropriate solution for that. You're probably looking for something like https://github.com/Shopify/liquid it's what Shopify uses to provide the functionality you're talking about (user modifiable stylesheets and templates)

**Comment by thelucid** [comment]
@schneems Liquid would not be appropriate as you wouldn't be able to do SASS includes etc. I'm thinking along the lines of SassMeister which looks like it uses Jammit... I thought Sprockets was a superior solution but obviously not.

**Comment by schneems** [comment]
Sprockets is an asset compilation system where you want to combine multiple assets together. The input is from disk and the final output is to disk. You could write your own pipeline that takes a user's database entry, writes it to disk, runs sprockets on it, stores the output back to disk if you want to. It wasn't explicitly designed for that capability, and the feedback cycle would be slow. I.e. every time a user makes a change you would have to run the task and let them know if it failed or not. I think you would be better off using sass directly

> Would there be any security concerns for example compiling SASS via sprockets as long as ERB wasn't enabled? ...or Javascript requirements as another example?

¯\_(ツ)_/¯ It's impossible to certify something as safe or not, if there's a CVE in sass then it's possible that could be used to leapfrog into another system. I've not tried. Maybe you could ask the sass maintainers if exposing sass on your site would be insecure.

**Comment by thelucid** [comment]
@schneems Ah, yes, it's a shame that there is the assumption that assets are stored on disk. It would be nice to be able to specify an adapter that reads the relevant content... I will perhaps look at implementing this as I'm sure it would be useful for projects such as codepen.io etc.
