### ISSUE TITLE
NoMethodError: undefined method `include?' for #<Pathname>

### ISSUE THREAD

**Issue by francisli** [rails/sprockets#112]
Hello,

Sprockets 3.3.2 and later generate this exception when building assets with the requirejs-rails gem (0.9.9):

NoMethodError: undefined method `include?' for #<Pathname:0x007ff4d60bb878>
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/sprockets-3.3.2/lib/sprockets/uri_tar.rb:13:in `initialize'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/sprockets-3.3.2/lib/sprockets/unloaded_asset.rb:24:in `new'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/sprockets-3.3.2/lib/sprockets/unloaded_asset.rb:24:in `initialize'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/sprockets-3.3.2/lib/sprockets/base.rb:55:in `new'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/sprockets-3.3.2/lib/sprockets/base.rb:55:in `file_digest'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/requirejs-rails-0.9.9/lib/tasks/requirejs-rails_tasks.rake:165:in `block (4 levels) in <top (required)>'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/requirejs-rails-0.9.9/lib/tasks/requirejs-rails_tasks.rake:148:in `each'
remote:        /tmp/build_9fdbed048bfec9fd21c6cae0fc415b85/vendor/bundle/ruby/2.2.0/gems/requirejs-rails-0.9.9/lib/tasks/requirejs-rails_tasks.rake:148:in `block (3 levels) in <top (required)>'
...

Downgrading, 3.3.0 and 3.3.1 result in this exception:

NoMethodError: undefined method `start_with?' for #<Pathname:0x007f8f739b1950>
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/sprockets-3.3.1/lib/sprockets/path_utils.rb:111:in `split_subpath'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/sprockets-3.3.1/lib/sprockets/loader.rb:156:in `get_relative_path_from_uri'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/sprockets-3.3.1/lib/sprockets/loader.rb:36:in `initialize'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/sprockets-3.3.1/lib/sprockets/base.rb:54:in `new'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/sprockets-3.3.1/lib/sprockets/base.rb:54:in `file_digest'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/requirejs-rails-0.9.9/lib/tasks/requirejs-rails_tasks.rake:165:in `block (4 levels) in <top (required)>'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/requirejs-rails-0.9.9/lib/tasks/requirejs-rails_tasks.rake:148:in `each'
/Users/francisli/.rvm/gems/ruby-2.2.2@wrapi-rails/gems/requirejs-rails-0.9.9/lib/tasks/requirejs-rails_tasks.rake:148:in `block (3 levels) in <top (required)>'
...

Downgrading to 3.2.0 and earlier works.

**Comment by schneems** [comment]
Interesting, That should be an easy fix. Are you manually passing in a pathname to a link or sprockets helper? Can you give me the full backtrace in 3.3.2 or 3.3.3?

**Comment by schneems** [comment]
Found it https://github.com/jwhitley/requirejs-rails/blob/a4b635928dc1545ff8104dca67521816be840225/lib/tasks/requirejs-rails_tasks.rake#L111

**Comment by schneems** [comment]
fixed. Can you test it out in your Gemfile

```
gem "sprockets", github: "rails/sprockets", branch: "3.x"
```

**Comment by francisli** [comment]
I reran the task on my project, and it now seems fixed. Thanks for the prompt handling, looking forward to the next cut of the gem!
