### ISSUE TITLE
Create stub with regular expression

### ISSUE THREAD

**Issue by jonricaurte** [rails/sprockets#13]
I made another issue for sprockets-rails but I think it belongs here instead.

I have an angular front end and I want to include all my unit test files in my project assets(in each feature module). Currently I have to stub every test file that is included, but what would be more ideal is if I could pass in a regular expression and have stub remove all test files that end in _spec.coffee.

After looking at some of the code, it looks like here:

https://github.com/rails/sprockets/blob/master/lib/sprockets/directive_processor.rb#L243

could take an options parameter that would have stub or even a regular expression and check to make sure as it is recursively adding the files that they don't fall under the regular expression. Actually maybe the method that it is calling:

https://github.com/rails/sprockets/blob/master/lib/sprockets/directive_processor.rb#L349

then this

https://github.com/rails/sprockets/blob/master/lib/sprockets/directive_processor.rb#L361

and it looks like it already has an options parameter.

Maybe have it be:

//= require_tree ., stub: /.*_spec.coffee/ 

What do you think?

Thanks.

**Comment by josh** [comment]
See my suggested solution on the other thread.

Regexp syntaxes won't be supported since theres no way know which directories apply. Even sass's imported globs are just limited to `*` and `**/*`. You can't do anything fancy beyond that.

**Comment by jonricaurte** [comment]
Okay, thanks for letting me know. When you say no way to know which directories, I think it would be the directories that fall under the respective directive. For //= require_directory "./javascripts", it would be the files listed in that directory and not the nested directories, and for  //= require_tree "./public", it would be the current directory and all subdirectories.

**Comment by jonricaurte** [comment]
If anyone wants to have this structure, use SystemJS with sprockets-es6 and sprockets 3.0 so then its module based and you do not have this issue.
