### ISSUE TITLE
Generate assets based on "virtual" files

### ISSUE THREAD

**Issue by brauliobo** [rails/sprockets#130]
If there is no source file and the output is generated from program's logic (hashes, databases), I should be able to register a preprocessor on Sprockets based on URIs on which my Processor can handle asset generation.

This is the case of https://github.com/fnando/i18n-js. The `%{locale}.js` are generated from the load of many YAML files and them splitted based on a config file.

So, the question is: is it possible to Sprockets based on a "virtual" file?

See also: https://github.com/fnando/i18n-js/issues/356

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but I don't think this is sprockets job. Also I believe it is already possible to implement this using current api but you will need a manifest source file and a custom pre processor.

**Comment by brauliobo** [comment]
@rafaelfranca Sorry, I can't find documentation of this manifest source file, how should I create/use it?

**Comment by rafaelfranca** [comment]
A manifest is a file like `application.js`.

So I believe something like this would work:

```javascript
// pt-BR.js
// = require_tree config/locale
```

And a pre processor from YAML to javascript registered
