### ISSUE TITLE
Changelog entry missing for 2.12.4

### ISSUE THREAD

**Issue by bdezonia** [rails/sprockets#134]
I am still using the 2.x series and noticed a patch was applied from 2.12.3 to 2.12.4. But I do not see anything listed in the Changelog. Could you add some info here? Thanks.

**Comment by schneems** [comment]
All sprockets releases are tagged, you can use github to compare https://github.com/rails/sprockets/compare/v2.12.3...v2.12.4

Would appreciate a PR with a changelog entry for that version.
