### ISSUE TITLE
register_postprocessor block form on master

### ISSUE THREAD

**Issue by glebm** [rails/sprockets#138]
[This example](https://github.com/rails/sprockets/blob/edae5cdfa241b0fb0fcb756b25cd561c3d8b7f29/lib/sprockets/processing.rb#L103) from the processing documentation:

```ruby
register_postprocessor 'application/javascript', :my_processor do |context, data|
  # ...
end
```
Results in the following error:

> undefined method `call' for :my_processor:Symbol
>
> [.../sprockets-edae5cdfa241/lib/sprockets/processor_utils.rb:83](https://github.com/rails/sprockets/blob/edae5cdfa241b0fb0fcb756b25cd561c3d8b7f29/lib/sprockets/processor_utils.rb#L83):in `call_processor'

This is because `register_postprocessor` calls:

```ruby
register_config_processor(:postprocessors, *args, &block)
```
However, `register_config_processors` does not expect a block if more than two arguments are given:

```ruby
def register_config_processor(type, mime_type, processor = nil, &block)
  processor ||= block
  # ...
end
```

Example in the wild: https://github.com/ai/autoprefixer-rails/blob/103a0823f2a0bb635cdd42eecca5816cf82240bb/lib/autoprefixer-rails/sprockets.rb#L25

---

Are the docs out of date or should this be considered a bug?

**Comment by rafaelfranca** [comment]
In fact that block version of a preprocessor with 2 arguments was deprecated in Sprockets 3 and removed in Sprockets 4. The doc need to be updated.
