### ISSUE TITLE
Perf Review: Cache key digest generation 

### ISSUE THREAD

**Issue by josh** [rails/sprockets#14]
Hey @tenderlove, now that I have you :wink: 

I love to know if you have a better idea for implementing this digest generation function. The main use case is generating <255c consistent cache keys. It accepts "simple" nested structured and needs to digest large strings.

https://github.com/rails/sprockets/blob/master/lib/sprockets/digest_utils.rb#L37-L88

Heres a simple use for caching the result of a coffeescript compile

``` ruby
cache.fetch([name, CoffeeScript::Source.version, VERSION, data]) do
 CoffeeScript.compile(data)
end
```

The entire input `data` string is used in a key here. That array key gets hashed down to a string that can be used for simple `cache = {}; cache[key]` lookups or written as the filename when the FS cache store is used.

Have any better implementation ideas here? It doesn't necessarily have to be SHA256 or anything. Just be a consistent hash and work on "simple" ruby objects. Restricting to objects that can be JSON serialized seems like a fine constrain too.

Thanks!

/cc @rafaelfranca

**Comment by tenderlove** [comment]
> Just be a consistent hash and work on "simple" ruby objects.

Why the requirement on simple ruby objects?  The coffee script example looks like it's just strings.  Is there an example where it would be more complex than a string (or list of strings)?

Now that I'm typing this out, is the idea that the cache key is different depending on the asset type?  If that is true, then why not use that to our advantage when generating the key?

This example:

```ruby
cache.fetch([name, CoffeeScript::Source.version, VERSION, data]) do
 CoffeeScript.compile(data)
end
```

clearly knows that it's caching a coffee script asset.  Does the context change depending on the asset type being cached?  IOW:

```ruby
# what is `self` here?
cache.fetch([name, CoffeeScript::Source.version, VERSION, data]) do
 CoffeeScript.compile(data)
end
```

If `self` changes in the context above, we could use polymorphism to efficiently generate the right key (as some sort of string).  Then we don't need a "catch all" method like the one in digest utils.  From a cursory glance, it looks like the cache implementation is the thing that generates the cache key.  Maybe we want to look at pushing key generation up to the caller.

Can you show me the typical code path that calls this?  Even better, do you have a way to benchmark typical usage?  I really don't know the sprockets code well, so demo code would probably help me sound more informed.  ;)

**Comment by josh** [comment]
> Maybe we want to look at pushing key generation up to the caller.

Yeah, theres already a higher level above this. That was actually added later and I've been considering dropping the low level per pipeline handler caching and just leave it per asset. I think these handler ones have a pretty low cache hit rate in practice. I'm still trying to hack up some stuff I can run in dev to gather some better data on this.

Though, this digest pattern is still used for per asset caching as well. It just combines the defined cache keys for each of the handlers in the chain.

``` ruby
CoffeeScriptProcessor#cache_key + UglifierProcessor#cache_key + SomeotherCustomProcessor#cache_key
```

The combined result of that already gets computed once per lookup. So multiple assets using identical processor chains reuse that.

The current cache policies seems to be working pretty well at handling incremental build changes after changing a few files or switching back and forward between the previous cache generations which is nice for people who switch branches alot. Though, I think I mostly just went overboard with some caching thats just adding more overhead that its worth. So I'm mostly trying to go through and strip back to the essentials.

**Comment by josh** [comment]
I think I'll `wontfix` this for now.

As you mentioned, we can probably just cut down the number of callers to `digest` that don't need all the fancy "complex object" stuff.
