### ISSUE TITLE
rake clobber:assets does not clobber assets with default capistrano config

### ISSUE THREAD

**Issue by wlipa** [rails/sprockets#140]
Capistrano 3 (or maybe capistrano-rails) makes a symlink from current/public/assets to shared/public/assets which is where the sprockets cross-release precompiled assets are stored.  The clobber task uses FileUtils.rm_r to delete shared/public/assets, and since this call does not follow symlinks, it doesn't actually delete the assets.

**Comment by jeremy** [comment]
+1 to delete the contents of the directory rather than deleting the directory itself. Should be a straightforward change to https://github.com/rails/sprockets/blob/master/lib/sprockets/manifest.rb#L227-L232 — please do investigate 😁
