### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by tf** [rails/sprockets#151]
Has anyone thought about how sprockets could integrate concepts like [CSS modules](https://github.com/css-modules/css-modules)? While there seems to be a strong focus on Sass in Sprockets at the moment, [over in Webpack land](https://github.com/webpack/css-loader) these new ideas get a lot of traction.

Given that the JS module system story (#73) also still is open, I'm not sure this really has a chance. But I think there are many valuable ideas in this area. I see more and more blog posts on how to move the front end part of Rails apps to Webpack usually resulting in a lot more boiler plate and a lot less integration with concepts like Rails engines which the asset pipeline is really great at.

**Comment by tf** [comment]
Relevant: https://github.com/css-modules/cssm-rails

**Comment by rafaelfranca** [comment]
I believe this idea need to get more traction before we think in including in sprockets by default. Thank you for the suggestion.
