### ISSUE TITLE
Sprockets 3.0.0 release

### ISSUE THREAD

**Issue by josh** [rails/sprockets#16]
Can we set a tentative date to tag the current RC as gold master? How many weeks should we wait?

/cc @rafaelfranca @tenderlove @lucasmazza @elia

**Comment by rafaelfranca** [comment]
Maybe two weeks is sufficient. It is what we do with Rails releases.

Just to be aware, do we need to release sass-rails and sprockets-rails?

In this next week I'll make Rails test suite run against sprockets 3.

**Comment by josh** [comment]
> Just to be aware, do we need to release sass-rails and sprockets-rails?

The latest sprockets-rails 2.x has no code changes from the most recent release https://github.com/rails/sprockets-rails/compare/v2.2.4...2.x

For sass-rails, looking at https://github.com/rails/sass-rails/compare/v5.0.1...master, we may want to push those changes out in a 5.0.2. We can do that now since it should be compatible with 2.x and 3.x.

**Comment by rafaelfranca** [comment]
sass-rails 5.0.2 released https://github.com/rails/sass-rails/releases/tag/v5.0.2

**Comment by rafaelfranca** [comment]
Opened https://github.com/rails/rails/pull/19587 to run our tests using sprockets 3 rc1

**Comment by lucasmazza** [comment]
> The latest sprockets-rails 2.x has no code changes from the most recent release rails/sprockets-rails@v2.2.4...2.x

What about 2x...master? I tried the latest sprockets-rails 2 on my app using the asset manifest API and got an `AssetNotPrecompiled` error that doesn't happens when using the `master` branch. Probably due some better support for the whole manifest/link/link_tree APIs.

**Comment by rafaelfranca** [comment]
Maybe a new sprockets-rails beta or even rc

**Comment by josh** [comment]
> I tried the latest sprockets-rails 2 on my app using the asset manifest API and got an AssetNotPrecompiled error that doesn't happens when using the master branch.

Hmm, we should double check that. But I think you *may* have to use sprockets-rails/master to do the manifest/link stuff. My hope is that everyone using sprockets-rails 2.x today can upgrade sprockets 3.x in isolation and have everything work. If theres any compat issues there I'd like to fix them in sprockets 3.x just to make sure everything is a smooth upgrade.

**Comment by lucasmazza** [comment]
> you may have to use sprockets-rails/master to do the manifest/link stuff.

I'm pretty sure that's the case. I'm going to test the basic upgrade path later to confirm this.

**Comment by lucasmazza** [comment]
> I'm going to test the basic upgrade path later to confirm this.

:+1:. Simply upgrading `sprockets` (and `sass-rails`) works as expected.

**Comment by josh** [comment]
@lucasmazza rad!

**Comment by josh** [comment]
Pushed an RC2 with two minor patches received over the week.

**Comment by josh** [comment]
:tada:

**Comment by elia** [comment]
✨
