### ISSUE TITLE
Caching too aggressive?

### ISSUE THREAD

**Issue by cymen** [rails/sprockets#163]
I contribute to https://github.com/browserify-rails/browserify-rails and it appears with recent versions of sprockets the caching is aggressive enough that the browserify-rails preprocessor is no longer called. To explain, browserify-rails hooks up browserify to the asset pipeline. That will let you do something like this:

application.js:
```js
//= require myApp
```

myApp.js:
```js
var wholeCommonJsBasedApp = require('./modules/app');
app();
```

Changes to `myApp.js` are detected by sprockets but we also need sprockets to flush the cache when anything in say `./modules` is changed.

Is there an easy way to do this or to simply disable the whole sprockets cache?

**Comment by cymen** [comment]
I dug into this a bit more -- we are passing back metadata to sprockets with our dependencies but a change in one of the dependent files doesn't seem to trigger cache invalidation. Our usage looks like this:

entry.js <- changing this file will bust cache

However, if entry.js has a `require './modules/x.js', we pass back that required file as a dependency when entry.js is processed. But changing ./modules/x.js does not bust the cache for entry.js.

Should this work?

**Comment by cymen** [comment]
It is our mistake not sprockets -- we were not correctly inserting the dependency and that of course broke things. My apologies for not hunting it down further before opening an issue as it is all obvious in hindsight.

**Comment by schneems** [comment]
Don't be sorry for opening up an issue. I'm glad you were able to find and fix your problem. Sorry for not responding sooner. 

Here's some back story: the original maintainer of sprockets is gone, now Rails owns the repo and very little knowledge has been transferred. Many questions such as yours are not known off the top of anyone's head. I've done some major work on the caching part of sprockets and know a good amount, but i've never touched the preprocessor extension code so there's a gap in my knowledge. 

What you said rings true, the cache should invalidate if any thing in the metadata dependencies is changed as that thing's SHA should change. However I have no idea how to actually add that to a 3rd party pre-processor. Here's where I'm hoping to work together. 

Would you be willing to hope me write a guide on how to correctly write a preprocessor for sprockets including info on how to add dependencies? I'm thinking that the README is too large as is, and we should start splitting up documentation into something like Rails's guides. The simplest way to do this would be to add a `docs/` directory with different markdown files (i'm not a big fan of using github's wikis for stuff like this that ultimately needs pretty tight quality control). A doc file on the ins and outs of "writing a preprocessor" would be a perfect start. If you can help me out by writing a first draft, I can give you my gratitude and I can also send you a pizza when you're done 🍕❗️ What do you think, would you be able to help me out? I can help with document structure and editing, but I need someone's first hand expertise in the subject.

**Comment by cymen** [comment]
@schneems I'd be willing to help. I maintain browserify-rails and was planning on doing a refactor at some point to go direct to sprockets instead of using tilt. But someone else did the PR to make that change which was great! Unfortunately, the PR also introduced the caching dependency bug but after some debugging with pry and some hints in the sprockets documentation, it started making more sense (well, I guessed what the issue was and I was right).

Anyway, I think I understand the basics enough to be useful and would be happy to help. One tiny lingering question I have is if there is a Rails/sprockets way to make a `file-digest://` URI -- I'm just doing it manually by appending `file-digest://` to the fully qualified path to the dependency.

What's next?

**Comment by schneems** [comment]
There is a helper method https://github.com/rails/sprockets/blob/98d0ccc42949815d959cf95fbffd52a3df650358/lib/sprockets/uri_utils.rb#L145

You could call `URIUtils.build_file_digest_uri("path")` if you require that file. Honestly if you're already building it manually, I would probably keep the code the same unless you've got that part tested. 

> What's next?

Clone this repo and make a new branch. Add a `docs` directory and a `writing_a_preprocessor.md` file. Take a stab at starting the doc. The basic questions to cover are: what is a sprockets preprocessor? What is a good problem space that is solved well by preprocessors? You can use your preprocessor as an example. Then finally what are gotchas you might encounter while writing a preprocessor? Here is where you could put your notes on properly declaring dependencies in the metadata. 

If you want to make the blank doc and submit a PR and ask me questions as we go, we can leave the PR open until we're both happy with the contents. How does that sound?

**Comment by brendon** [comment]
@cymen, I know it's a long time ago but I was wondering what it actually was that fixed your cache busting problem? I'm trying to upgrade `less-rails` to not use tilt and give it a Sprockets 2, 3, and 4 interface but modifying a dependant file doesn't bust the cache (like you mention). Here's the current dependency builder preprocessor (for `@import`'s):

```ruby
module Less
  module Rails
    class ImportProcessor

      IMPORT_SCANNER = /@import\s*['"]([^'"]+)['"]\s*;/.freeze

      PATHNAME_FINDER = Proc.new do |scope, path|
        begin
          scope.resolve(path)
        rescue Sprockets::FileNotFound
          nil
        end
      end

      def initialize(filename, &block)
        @filename = filename
        @source   = block.call
      end

      def render(scope, locals)
        self.class.evaluate(@filename, @source, scope)
      end

      def self.evaluate(filename, source, scope)
        depend_on scope, source
        source
      end

      def self.call(input)
        filename = input[:filename]
        source   = input[:data]
        scope  = input[:environment].context_class.new(input)

        result = evaluate(filename, source, scope)
        scope.metadata.merge(data: result)
      end

      def self.depend_on(scope, source, base=File.dirname(scope.logical_path))
        import_paths = source.scan(IMPORT_SCANNER).flatten.compact.uniq
        import_paths.each do |path|
          pathname = PATHNAME_FINDER.call(scope, path) || PATHNAME_FINDER.call(scope, File.join(base, path))
          scope.depend_on(pathname) if pathname && pathname.extname == '.less'
          depend_on scope, pathname.read, File.dirname(path) if pathname
        end
        source
      end

    end
  end
end
```

The key line is `scope.depend_on(pathname) if pathname && pathname.extname == '.less'` and as far as I can tell this creates a dependency in sprockets, but it seems this isn't enough for sprockets to check the dependency for changes and invalidate the cache.

What extra do I need to do?

**Comment by cymen** [comment]
@brendon Hrm... It was a while ago and I think I was working in parts of browserify-rails that I hadn't initially written. This appears to be the issue on the browserify-rails side:

https://github.com/browserify-rails/browserify-rails/issues/101

I want to say the key part was keeping track of dependencies using format of `file-digest` and I don't know where I got that -- maybe by looking at other Sprocket usage examples. We can look at the call on the browserify-rails side here:

https://github.com/browserify-rails/browserify-rails/blob/master/lib/browserify-rails/browserify_processor.rb#L28-L53

It looks like we do a fair amount of work to build up all the dependencies and then pass back up (to Sprockets?) on the last line of `call`:

`{ data: new_data, dependencies: dependencies }`

I wonder if the `scope.depend_on` just needs to be called like so:

`scope.depend_on("file-digest://#{Addressable::URI.escape pathname}") if pathname && pathname.extname == '.less'`

I'd also double check pathname is fully resolved if that doesn't work and try resolving it fully (based on looking at https://github.com/browserify-rails/browserify-rails/blob/master/lib/browserify-rails/browserify_processor.rb#L41-L49 .

**Comment by brendon** [comment]
Thanks @cymen, that gives me some leads :D The `file-digest` quick fix doesn't work. It's then unable to find the file on the filesystem. I'll look into passing the dependencies back through the meta-data instead of adding them in this way.

**Comment by brendon** [comment]
Wow, it looks like a timing issue! If I `sleep 1` after editing the file in the test the tests pass. Now I need to find a way to wait until the file is recompiled before testing it...

**Comment by brendon** [comment]
Ok, sorted this out properly now. It's not so much a timing issue (waiting for the regeneration to happen) but an issue to do with how the asset change is detected (`mtime`). I grabbed this from the SASS test suite:

```ruby
mtime = Time.now + 1
File.utime(mtime, mtime, the_file_path)
```

Run that in between each change and the file `mtime` will be different rather than potentially the same due to the speed of the save operations, and sprockets will see the change and regenerate the asset.

Thanks for your help again @cymen :)
