### ISSUE TITLE
Sprockets stub directory

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#165]
_From @johanstenberg92 on November 17, 2015 11:41_

Hi,

I've been trying but it seems to be impossible to stub a directory, is this something that will be added later or is there a specific reason why it isn't implemented?

Thanks,

Johan

_Copied from original issue: sstephenson/sprockets#741_

**Comment by rafaelfranca** [comment]
It is not implemented yet but we need to have a good reason to. If you don't want to compile a directory just don't require it.

**Comment by johanstenberg92** [comment]
Hi,

That's what I've end up doing. However it's quite nice to "blacklist" instead of "whitelist", since you might have just one folder you don't want to add and many that you want to add. But it's your call, thanks for responding by the way +1

**Comment by Rockster160** [comment]
I know this is old, but +1.

I constantly have the need to stub a full directory. 
I have a number of large assets that I only want to require on the pages that use them. It's worth that one single page slowing down slightly to speed up the rest of the app. 

In one specific app, every page has unique functionality, but the site still has global styles. I use `//= require_tree .` to include the global styles, then I want to stub out the `support` directory, which has each of the files that need to be applied to only specific pages. Right now I manually add each file to the `stub`, then add the specific include tag needed to require that file on the pages as desired.
