### ISSUE TITLE
Loading sprockets is too slow

### ISSUE THREAD

**Issue by tenderlove** [rails/sprockets#17]
I think we can do better:

```
[aaron@TC sprockets (master)]$ time ruby -v --disable-gems -I lib:../rack/lib -r sprockets -e ''
ruby 2.3.0dev (2015-03-25 trunk 50080) [x86_64-darwin14]

real	0m0.482s
user	0m0.426s
sys	0m0.053s
[aaron@TC sprockets (master)]$
```

**Comment by josh** [comment]
Theres alot of garbage objects being created in config process, https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L44-L155, but it doesn't seem to be more than 30-40ms here. Most of the time seem scoped to all of sprockets/environment file dependencies.

Though, if your looking to make an actual impact on the load time of doing something like `rake assets:precompile`, it'd be great if we didn't have the load the entire rails app, run all the initializers, make a database connection just to compile assets.

https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/task.rb#L58-L63

We're bypassing all that at @github with a custom environment initializer that skips all that. Also makes it easier to compile assets in places we don't have a db connection.

**Comment by tenderlove** [comment]
Here's the test script I'm using:

```ruby
require 'stackprof'

StackProf.run(mode: :wall, out: 'out.dump') do
  require 'sprockets'
end
system 'stackprof out.dump'
```

My output:

```
[aaron@TC sprockets (master)]$ time ruby -v --disable-gems -I lib:../rack/lib:../stackprof/lib:. -e'require "req_time"'
ruby 2.3.0dev (2015-03-25 trunk 50080) [x86_64-darwin14]
==================================
  Mode: wall(1000)
  Samples: 373 (10.55% miss rate)
  GC: 122 (32.71%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
        92  (24.7%)          92  (24.7%)     block (4 levels) in Sprockets::Mime#compute_extname_map
        26   (7.0%)          10   (2.7%)     <top (required)>
        15   (4.0%)           9   (2.4%)     <top (required)>
       105  (28.2%)           8   (2.1%)     Sprockets::Utils#hash_reassoc1
        15   (4.0%)           7   (1.9%)     <top (required)>
        92  (24.7%)           5   (1.3%)     <top (required)>
        14   (3.8%)           5   (1.3%)     <top (required)>
         7   (1.9%)           4   (1.1%)     <top (required)>
        12   (3.2%)           4   (1.1%)     <top (required)>
```

It's not just GC time, but also lots of time spent in `compute_extname_map'.  I don't really understand that function yet.

**Comment by josh** [comment]
> It's not just GC time, but also lots of time spent in `compute_extname_map'. I don't really understand that function yet.

Thats to precompute some engine extension stuff. Luckily all that is gone in the 4.x branch. So its probably not worth worrying about it too much.

Heres the top wall time offenders on the 4.x branch.

```
Measure Mode: wall_time
Thread ID: 70168319754760
Fiber ID: 70168332429220
Total: 0.156957
Sort by: self_time

 %self      total      self      wait     child     calls  name
 10.42      0.016     0.016     0.000     0.000        1   OpenSSL::X509::Store#set_default_paths 
  3.38      0.010     0.005     0.005     0.000     1180   Enumerator#next 
  2.30      0.004     0.004     0.000     0.000      535   Hash#initialize_copy 
  1.64      0.006     0.003     0.002     0.001     1180   Enumerator#peek 
  1.51      0.003     0.002     0.000     0.001      714   Module#define_method 
  1.46      0.007     0.002     0.000     0.005      339   Sprockets::ProcessorUtils#compose_processors 
  1.42      0.020     0.002     0.000     0.018      456   Kernel#loop 
  1.36      0.007     0.002     0.000     0.005      243   Sprockets::Utils#dfs_paths 
  1.34      0.002     0.002     0.000     0.000      339   Proc#[] 
  1.34      0.002     0.002     0.000     0.000     2265   Module#method_added 
```

**Comment by tenderlove** [comment]
> Thats to precompute some engine extension stuff. Luckily all that is gone in the 4.x branch. So its probably not worth worrying about it too much.

Why isn't the 4.x branch master?

**Comment by josh** [comment]
> Why isn't the 4.x branch master?

I still technically haven't released 3.x. Thats the thing I have the RC out for now.

3.x is going to have to support a bunch of dumb legacy code paths for 2.x compatibility. I have most of those crazy things dropped in 4.x. So all the new feature stuff like source maps is going there.

**Comment by josh** [comment]
If we could batch up the registration blocks for

https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L44-L155

we would probably avoid generating the intermediate structures that we end up discarding. I was hesitant to lazily compute those to avoid that hit happening the slow pain on the first asset find.

So coalesce it just during sprockets own init might be good enough and still get all the other immutable structures straight forward.

All the config stuff is immutable now to make sharing it easier. On 2.x, a ton of stuff gets dup'd between environments and find asset invocations. Now everything just shares the same immutable config reference. But that pushes some of that precomputation to be done on init rather than on compile time.

**Comment by tenderlove** [comment]
It still seems like edge should be on master.  I should be doing perf work against edge and backporting, not the other way around.

> All the config stuff is immutable now to make sharing it easier. On 2.x, a ton of stuff gets dup'd between environments and find asset invocations.

I think if we use an object that isn't a Hash for config values, we can have an immutable data structure without duping (for example use a linked list).

The configuration is linked to the performance of sprockets (I followed `parse_path_extnames` which looks up config values).  I think that we can make `digest` only handle strings and still support the `cache_key` api that is documented.  But I can only make that type of refactoring if I know what I'm working with.  If configuration is changed in 4.x, likely the work I'm doing won't be portable to that branch.  To fix #14, which branch should I work against?

**Comment by josh** [comment]
> I think if we use an object that isn't a Hash for config values, we can have an immutable data structure without duping (for example use a linked list).

I'd like to keep all the config stuff in a basic hash for future directory scoped configuration features. Where you'll be able to have `.json` files that override or change default configuration pieces. Its pretty easy to work with when JSON objects map to Ruby Hashes.

> The configuration is linked to the performance of sprockets (I followed parse_path_extnames which looks up config values).

Thats not directly related to the configuration rather than choosing to precompute that `config[:_extnames]` value (3.x only hack) than compute it on demand. We could flip that around if we really wanted to for 3.x.

**Comment by toolmantim** [comment]
So I just stumbled into this whilst trying to reduce the memory footprint and load time of our (Rails) app.

```
$ ruby -rmemory_profiler -I. -e 'MemoryProfiler.report { require "config/environment" }.pretty_print'
Total allocated 2057572
Total retained 390073

allocated memory by gem
-----------------------------------
activesupport-4.2.1 x 60149050 (note: this is just because dependency require'ing gets reported under here)
sprockets-3.0.1 x 56626099
2.2.0/lib x 28229776
rubygems x 13925583

retained memory by gem
-----------------------------------
sprockets-3.0.1 x 14024689
2.2.0/lib x 7370079
activesupport-4.2.1 x 5285833
```

That's 56MB of allocated memory and 14MB of retained, almost all of which is that extnames hash: https://gist.github.com/toolmantim/d9a18fc7e853f93cb052

I've done a dump of the typical final data structure: https://gist.github.com/toolmantim/56fd2421b2e515f7c5e9 (131k keys)

We can shave 8MB off the total memory allocations (retained memory is unchanged) by just adding `.freeze` to the strings that are created in that method:

```
$ ruby -rmemory_profiler -I. -e 'MemoryProfiler.report { require "config/environment" }.pretty_print'
Total allocated 1926448
Total retained 390071

allocated memory by gem
-----------------------------------
activesupport-4.2.1 x 60149050
sprockets-3.0.1 x 46138113
```

```diff
         graph = {}
 
         ([nil] + pipelines.keys.map(&:to_s)).each do |pipeline|
-          pipeline_extname = ".#{pipeline}" if pipeline
+          pipeline_extname = ".#{pipeline}".freeze if pipeline
           ([[nil, nil]] + config[:mime_exts].to_a).each do |format_extname, format_type|
             4.times do |n|
               config[:engines].keys.permutation(n).each do |engine_extnames|
-                key = "#{pipeline_extname}#{format_extname}#{engine_extnames.join}"
+                key = "#{pipeline_extname}#{format_extname}#{engine_extnames.join}".freeze
                 type = format_type || config[:engine_mime_types][engine_extnames.first]
                 graph[key] = {type: type, engines: engine_extnames, pipeline: pipeline}
               end
```

Though after digging in I realised this shouldn't be happening on Rails require at all, it's actually being triggered by reactjs/react-rails#249. It still seems like a pretty sad panda method for memory and performance though (and it seems like `extname_map` is only setting up data for `match_path_extname`, and there's only 1 or 2 callsites, all internal)… but I thought I'd leave this here as some data about the memory usage of this method in 3.x.

Should I shoot through a PR for the `freeze` change?

**Comment by blackjid** [comment]
hey @josh would you share the environment initializer you mention [here](https://github.com/rails/sprockets/issues/17#issuecomment-87486010) thanks!

**Comment by schneems** [comment]
Going to close this as somewhat inactive. I got a lot of improvements from switching to bootscale https://github.com/byroot/bootscale. If you have new ideas that can be implemented to speed up boot without sacrificing stability please open up a new issue, i'll be happy to dissect and debug with you.
