### ISSUE TITLE
Create stub with regular expression

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#176]
_From @jonricaurte on March 23, 2015 23:54_

I have an angular front end and I want to include all my unit test files in my project assets(in each feature module). Currently I have to stub every test file that is included, but what would be more ideal is if I could pass in a regular expression and have stub remove all test files that end in _spec.coffee.

Thanks!

_Copied from original issue: sstephenson/sprockets#712_

**Comment by rafaelfranca** [comment]
_From @schneems on August 28, 2015 17:22_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
_From @schneems on August 28, 2015 17:22_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment]
I don't think it is a good idea to have it by default but you can write your own directive processor to make it work https://github.com/rails/sprockets/blob/7c5ff2fd90deb7c9dd6b4507390456cb1e696e1e/lib/sprockets/directive_processor.rb#L285

**Comment by schneems** [comment]
Love this idea. We should make it easier to write a custom processor https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md

**Comment by rafaelfranca** [comment]
@schneems :+1: I have some examples in my own application. I'll write some examples.

**Comment by schneems** [comment]
Thanks :heart:
