### ISSUE TITLE
v3.0.1 breaks index.html static files

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#182]
_From @xdmx on April 22, 2015 9:54_

I have sprockets 3.0.1 going through our assets and I have few with a path like `app/assets/angular/views/something/other/index.html`, after the precompile I get `public/assets/views/something/other.html` instead of `public/assets/views/something/other/index.html`.

This obviously breaks all my views, since in dev I use index.html and in production it doesn't find it

It works fine under 2.12.3

_Copied from original issue: sstephenson/sprockets#722_

**Comment by rafaelfranca** [comment]
_From @tikijian on April 24, 2015 10:38_

+1 same for me.

**Comment by rafaelfranca** [comment]
_From @schneems on August 28, 2015 17:22_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by gilesbowkett** [comment]
This is fixed.

I created an example app which confirms that the bug was real in v3.0.1, as requested, and also that it's gone as of the current version, 3.7.0.

https://github.com/gilesbowkett/example-182

**Comment by rafaelfranca** [comment]
Thank you so much @gilesbowkett for doing the investigation!
