### ISSUE TITLE
could you make your error message be more readable

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#185]
_From @poc7667 on May 21, 2015 11:16_

All the message the sprockets show us, for example `rake aborted!
end of file reached` . who knows what should we do on this error.

_Copied from original issue: sstephenson/sprockets#727_

**Comment by rafaelfranca** [comment]
_From @schneems on August 28, 2015 17:21_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by arthurnn** [comment]
seems like there was no response from @poc7667 after @schneems comment. I will close this for now. If we get more info we can reopen it.
