### ISSUE TITLE
Uglify error on compiling assets for production

### ISSUE THREAD

**Issue by andreynering** [rails/sprockets#187]
Rails 4.2.5 (but it happens also in 4.2.4).

One of my apps works fine in development mode, and I can also compile assets in development mode without any problem (`rake assets:precompile RAILS_ENV=development`), because, by default, Rails do not minify the assets on development mode.

But when I try to compile in production (`rake assets:precompile RAILS_ENV=production`) I get an error from uglify. See: https://gist.githubusercontent.com/andreynering/123b60cb81e3a1c97dab/raw/bf7bad49c719e90231e6eafb91879d9ba25a58e3/output.txt

I'm using Babel/ES6/JSX from the ReactJS gem (https://github.com/reactjs/react-rails), but I don't think there is a problem with it because the non-uglified output works.

**Comment by rafaelfranca** [comment]
Would not that characterize a problem at uglifier?

**Comment by andreynering** [comment]
@rafaelfranca Thanks for the fast response.

I actually couldn't find the exact location of that caracter, because the log don't tell us in what file it is.

I double checked and the non-uglified version compiles and runs fine on both Chrome and Firefox. So, I think there isn't any sintax error, right?

**Comment by rafaelfranca** [comment]
Yeah. I'll take a look but it seems note a uglifier issue than a sprockets
issue. It is possible that for a specific input uglifier get lost in the
compression.

**Comment by andreynering** [comment]
Thanks!

Do exist any easy alternative to uglifier? I could make a simple test.

**Comment by schneems** [comment]
I don't know of a good alternative. You can disable using uglifier in your production.rb

Can you open an issue on uglifier with the repro case and link back to this issue please?

**Comment by rafaelfranca** [comment]
In sprockets master we have the jsmin compressor but you would be able to switch to sprockets 4

**Comment by andreynering** [comment]
@schneems Done: https://github.com/lautis/uglifier/issues/89

I just don't know how to reproduce it. Sorry.

**Comment by blooper05** [comment]
@andreynering 
I've got same error today on my application, with these versions.
- rails 4.2.1
- uglifier 2.7.2
- sprockets 3.4.1
- bower-rails 0.10.0
When I change sprockets to 2.12.4, the jQuery error is solved.
I hope this information helps you.

**Comment by blooper05** [comment]
But I still got an error on another jQuery plugin...
So I hope this problem will be solved.

**Comment by rafaelfranca** [comment]
@blooper05  Can you please provide a sample application that reproduces the error?

**Comment by blooper05** [comment]
@rafaelfranca
Hi! I've created a sample application. https://github.com/blooper05/SAAPE
You can see the error when `rake assets:precompile`. Please check it.

**Comment by andreynering** [comment]
I think this comment on the uglifier issue should explain everything: https://github.com/lautis/uglifier/issues/89#issuecomment-164145828

> ES6 would explain this. UglifyJS doesn't support ES6 syntax at least yet.

I will try to take a look at it this week (e.g. check if any of the files is ES6). It makes sense that the uglified version work on Chrome/Firefox since they already support most ES6.

Since it isn't related to sprockets, feel free to close this issue if you want.

**Comment by andreynering** [comment]
I can confirm this issue happened because of accidental ES6.

I could solve it by appending `.js.jsx` on some JS files, since it will convert ES6 to ES5. (This works because of [this gem](https://github.com/reactjs/react-rails)).

I am closing this since this isn't a sprockets issue. But I think maybe it would be nice to include babel by default to prevent this kind of problems.
