### ISSUE TITLE
3.5.1 autoload error JRuby + concurrent-ruby

### ISSUE THREAD

**Issue by jdantonio** [rails/sprockets#199]
Line [4 of manifest.rb](https://github.com/rails/sprockets/blob/master/lib/sprockets/manifest.rb#L4) requires `concurrent/future` rather than requiring the full gem. Unfortunately this causes an exception on all JRuby versions. The error is with `autoload`. To prevent a circular reference we need to autoload one particular module. The autoload works as expected on MRI Ruby but fails on JRuby. This issue was first [reported on concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby/issues/480).

I'm going to work on this within c-r and I'll release an update if I can figure out a solution. In the interim please consider requiring the full gem if possible.

Removing the offending circular references is on the roadmap for c-r 2.0

**Comment by rafaelfranca** [comment]
> In the interim please consider requiring the full gem if possible.

Okay :cry:

**Comment by schneems** [comment]
I'll backport this to 3.x. Thanks :heart:

**Comment by jdantonio** [comment]
Working on a fix here: https://github.com/ruby-concurrency/concurrent-ruby/pull/481
