### ISSUE TITLE
Should the gem gzip the SVG files?

### ISSUE THREAD

**Issue by vicocamacho** [rails/sprockets#202]
Today i upgraded my Gemfile to use the new gzip feature and when i precompiled it also gzipped my svg files (which made the website stop showing this files), im just curious if this is the desired behavior? 

Thank you.

**Comment by fxn** [comment]
If the client does not ask for a compressed resource, you'll get the plain SVG, it it asks, it will get the compressed one either from disk or compressed on the fly.

That is, in theory this feature shouldn't make a difference on the client side.

Why is the website not showing these files?

**Comment by schneems** [comment]
Pretty sure gzipping SVG files is fine: https://css-tricks.com/snippets/htaccess/active-gzip-compression/

The server should only deliver a GZIP file if the browser supports it. When they do they will set `accept-encoding` https://github.com/rails/rails/blob/1ad94e760d7a0f4288fb6d29114176b2e5dde250/actionpack/lib/action_dispatch/middleware/static.rb#L85 to include `gzip`. The browser should then see that we set `content-encoding` to `gzip` https://github.com/rails/rails/blob/1ad94e760d7a0f4288fb6d29114176b2e5dde250/actionpack/lib/action_dispatch/middleware/static.rb#L62 then it will unzip the contents.

So, how are you serving gzip files? Did you configure nginx to serve static assets and gzip files?

**Comment by vicocamacho** [comment]
Sorry, my bad. It was a server misconfig that was messing up with the SVG files, thank you so much for the directions and for all your work in OSS. :smile:

**Comment by fxn** [comment]
:+1: thanks for the followup!

**Comment by schneems** [comment]
Thanks all :heart:
