### ISSUE TITLE
Couldn't find file when using require_asset

### ISSUE THREAD

**Issue by mikem** [rails/sprockets#209]
I have an app using the [react-rails](https://github.com/reactjs/react-rails) gem. That gem [registers the `application/jsx` mime type and engine](https://github.com/reactjs/react-rails/blob/3b21569f5defb1705172c4a9a09b6ed0a1a9d38e/lib/react/rails/engine.rb#L7-L8) as follows:

```ruby
sprockets_env.register_mime_type("application/jsx", extensions: [".jsx", ".js.jsx", ".es.jsx", ".es6.jsx"])
sprockets_env.register_transformer("application/jsx", "application/javascript", React::JSX::Processor)
```

I can successfully load JSX files if I use `require` directives in another JS file, but it doesn't work if I use `require_asset` from within an ERB file.

I created a [minimal Rails app](https://github.com/mikem/sprockets_jsx_bug) to reproduce this bug. That app has two "components:"

- [`some_component.js`](https://github.com/mikem/sprockets_jsx_bug/blob/master/app/assets/javascripts/some_component.js)
- [`another_component.js.jsx`](https://github.com/mikem/sprockets_jsx_bug/blob/master/app/assets/javascripts/another_component.js.jsx)

There's also a [`main.js.erb`](https://github.com/mikem/sprockets_jsx_bug/blob/master/app/assets/javascripts/main.js.erb) which uses `require_asset` to load the two components. You can visit http://localhost:3000/some_component/index and note in the console that `some_component.js` logs to the console successfully. Uncomment [line 6](https://github.com/mikem/sprockets_jsx_bug/blob/master/app/assets/javascripts/main.js.erb#L6) to also load `another_component.js.jsx` and see the error.

I can include `another_component.js.jsx` without any problems if I don't use ERB. To verify this, comment out `main.js.erb`'s line 6 and add an `=` to [line 17 of `application.js`](https://github.com/mikem/sprockets_jsx_bug/blob/master/app/assets/javascripts/application.js#L17). Both components will write to the console now.

I'm bumping up against this in the [jasmine-rails](https://github.com/searls/jasmine-rails) gem, which uses [ERB to generate a JS file which loads all the Jasmine specs](https://github.com/searls/jasmine-rails/blob/ea97098844bef373470739f2927e895450e5e9a9/lib/assets/javascripts/jasmine-specs.js.erb#L11-L13).

I tried to resolve this myself and discovered the following:
- in both the ERB `require_asset` case and the JS `//= require` case, [`Sprockets::Resolve#resolve`](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L23) is executed
- in the JS `//= require` case, the provided `path` is absolute, so [`resolve_absolute_path`](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L31) is taken on line 31 and everything is smooth
- in the ERB `require_asset` case, the provided `path` is not absolute nor relative (ie: it's just `another_component.js.jsx`), so `resolve_logical_path` is called in the [last branch of the if-statement on line 35](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L35)
- `resolve_logical_path` first [determines the `mime_type` for the `path` using `parse_path_extnames`](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L104) and gets `application/jsx`
- next, [`mime_type` and `accept` are used to get `parsed_accept`](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L105) which is an empty array, then [`transformed_accept`](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L106) is also empty
- because `transformed_accept` is empty, [`resolve_under_paths` returns a `nil` `filename`](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L107) (see [this guard clause](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L120))
- the `nil` `filename` [prevents a `uri` from being built](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L38-L44) and in turn [triggers the `FileNotFound` exception](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/resolve.rb#L54-L65)

Since the absolute path case seems to work just fine, I'm not sure why the logical path shouldn't also work.

**Comment by searls** [comment]
Hey @schneems--would you have time to look at this with me this week?

**Comment by searls** [comment]
Argh, @schneems

**Comment by mikem** [comment]
I believe the commit above is a failing test for this issue. It looks like the issue might actually be that the argument to `require_asset` includes the original suffix. This is [what jasmine-rails does](https://github.com/searls/jasmine-rails/blob/ea97098844bef373470739f2927e895450e5e9a9/lib/assets/javascripts/jasmine-specs.js.erb#L12). In my test case above, if I `require_asset 'noformat'` then the test passes.

**Comment by schneems** [comment]
@searls ACK, sorry for the delay. This week is looking pretty tight. Not sure if i'll have time, can definitely set aside some next week to dig in.

**Comment by rmosolgo** [comment]
> if I `require_asset 'noformat'` then the test passes.

I noticed this in [UPGRADING.md](https://github.com/rails/sprockets/blob/master/UPGRADING.md): 

> **We can request the file in its original content type.**
>
> ```ruby
>  # Return the file as is
>  env.find_asset("foo.coffee").source
> ```
>
> Its important we can serve the original source file to the browser if source maps are being used.

So, I think it's a breaking change, but I understand why it works that way! (And it seems better overall.)

**Comment by Strech** [comment]
I confirm. I have the same problem with `js.jsx` files and `react-rails 1.6.x`. They are not compiled with sprockets 3.x, but compiled with 2.x. I will try to give more information I found but right now everything is similar to issue description - application/jsx is not being transformed.

**Comment by gilesbowkett** [comment]
I dug into this a tiny bit. PR #370 shows an awful hack which gets rid of the problem for the example app. The goal of the PR is not actually to be accepted, just to show what I found. TLDR: `@content_type` isn't getting set correctly.

**Comment by schneems** [comment]
Is this related to https://github.com/rails/sprockets/issues/231#issuecomment-243187921 ? I think we're maybe not registering something quite right or perhaps the order that things are happening isn't what they should be. In that case the comments were being stripped before it ever got to the JSX code.

**Comment by rmosolgo** [comment]
Seems like it must be! In both cases, it's `react-rails` + `@content_type` issues. 

I haven't had a chance to dig in because I know it will be a deep dive 😞 . The [JSX processor](https://github.com/reactjs/react-rails/blob/master/lib/react/jsx/processor.rb) itself is so simple, it implements the `.call(input :: Hash) :: String` API.

In terms of registering itself, it's [gotten a bit messy](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L105-110), trying to figure out how to handle `//= require`s & coffeescript, so maybe we're doing something wrong there!

**Comment by schneems** [comment]
Think I want to close this in favor of #231 since it has the debugging thread.
