### ISSUE TITLE
Question on the run order of engine processing

### ISSUE THREAD

**Issue by bradly** [rails/sprockets#210]
I've added a custom engine but I'm having trouble understanding the run order of the engines.

I've added a file app/assets/javascripts/donuts.js.jsx.coffee.hsx and it does get processed by the new engine, but I'm trying to make sure my custom engine get processed first. My assumption was that the engines are ran starting at the right most extension moving to the left, but that doesn't seem to be the case. I am seeing an ExecJS::RuntimeError when loading the http://app.dev/assets/donuts.js in the browser in the output I see the text that should have been removed by my custom processor.

Is there a way to see the execution order of the engines? Am I correct is assuming that they are suppose to be processed from right to left?

Thank you for any help you can offer.

My Preprocessor for reference:
```ruby
class HsxPreprocessor
  def call(input)
    input[:data].gsub! /\`([^<])(.+)\`/ do |haml_chunk|
      # do stuff here...
    end
    input[:data]
  end
end

Rails.application.assets.register_engine '.hsx', HsxPreprocessor.new
```

**Comment by rafaelfranca** [comment]
Could you please post your question in the Rails core mailing list? We reserve the issue tracker only for issues.

**Comment by GBH** [comment]
@bradly have you figured this out? I didn't find your question on rails core mailing list. I'm having a similar issue.

**Comment by bradly** [comment]
@GBH No, unfortunately I was not able to get this sorted and ended up scraping the approach.
