### ISSUE TITLE
Error encountered while saving cache ... can't dump anonymous class

### ISSUE THREAD

**Issue by stephanfriedrich** [rails/sprockets#212]
Hi I updated my gems. now i get an error in production env like:
```
    Warning. Error encountered while saving foo.scssc: can't dump anonymous class
```
my gems list: 
   * sass-rails 3.2.6
   * sass 3.4.20
   * sprockets 2.2.3
   * rails 3.2.22

**what can i do to fix this, which sprocket version works with sass ?**

there are equal issues 
   * https://github.com/sass/sass/issues/1144
   * https://github.com/sstephenson/sprockets/issues/507

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by stephanfriedrich** [comment]
Oh thx for your quick response.

here is my application on github: https://github.com/stephanfriedrich/kalender
hope this helps. 

*btw i am no a goog ruby/rails programmer, sorry for my bad written code ;)*

**Comment by rafaelfranca** [comment]
I used you code and it is working fine. Try to clean the sprockets cache.
