### ISSUE TITLE
Support something like depend_on_tree

### ISSUE THREAD

**Issue by joshjordan** [rails/sprockets#216]
https://github.com/sstephenson/sprockets/issues/567 was not resolved, reopening here. Apologies if this is the wrong place for it.

**Comment by matthewd** [comment]
This seems like a legitimate use case in principle... assuming that implementing it doesn't add too much complexity.

**Comment by xw19** [comment]
I would like to work on it but I need mentoring to be able to solve this

**Comment by joshjordan** [comment]
@matthewd would a PR for this feature be accepted, assuming, as you said, it is relatively low complexity?

**Comment by rstacruz** [comment]
I'd really appreciate this!

**Comment by schneems** [comment]
@joshjordan yep, seems reasonable. Going to close this issue for now. Please send over a PR and i'll try to help get it over the line.
