### ISSUE TITLE
let sprockets transform .html to javascript template

### ISSUE THREAD

**Issue by rn2dy** [rails/sprockets#218]
I need to let sprocket process `.html` file and output mime type as `application/javascript`, so it can be used as a javascript template. I did something like this:

```ruby
Sprockets.register_engine '.html', MyTemplateProcessor, mime_type: 'application/javascript'
```
However when sprockets process a `.html` file it will always interpret the file as `text/html` (as it suppose to be). I am not sure if this is the reason why `MyTemplateProcessor` was not called (does sprockets map mime type to processors instead of suffix string). If it is, is there a way to override default mime types?

**Comment by rafaelfranca** [comment]
Use:

```
register_transformer 'text/html', 'application/javascript', MyTemplateProcessor
```

**Comment by rn2dy** [comment]
Thank You! That resolved my problem.
