### ISSUE TITLE
When using Sprockets 3.0.0.rc.2 get error with slim: couldn't find file 'home.html.slim' with type 'application/javascript'

### ISSUE THREAD

**Issue by jonricaurte** [rails/sprockets#22]
Saw the update guide here:

https://github.com/rails/sprockets/blob/master/UPGRADING.md#user-content-processor-interface

Using: 
//= require home.html.slim

and I get the error: couldn't find file 'home.html.slim' with type 'application/javascript'

I'm using angular-rails-templates which relies on this. Is there any way around this?

Thanks.

**Comment by rafaelfranca** [comment]
Is this extension registered in some custom processor?

**Comment by jonricaurte** [comment]
It looks like even without using angular-rails-templates and just try to load the slim file, I get an error. When I downgrade to 2.11 it doesn't give an error.

**Comment by jonricaurte** [comment]
Updating my gem file to use gem 'sprockets', '~> 2.11' I don't get the error. However, when I use gem 'sprockets', '~> 3.0.0.rc.2' I get the: couldn't find file 'home.html.slim' with type 'application/javascript'

**Comment by rafaelfranca** [comment]
Yes, it give the error because you are trying to require a non-javascript file in a javascript file and now we are more strict about it. This is something that `angular-rails-templates` should implement as explained here https://github.com/rails/sprockets/blob/master/UPGRADING.md#transformers

**Comment by josh** [comment]
Give 

``` js
//= require home
```

a try without the extensions.

**Comment by jonricaurte** [comment]
@josh it still doesn't work without extensions so I left a ticket in the angular-rails-templates
