### ISSUE TITLE
Sprockets 3.0.0 breaks web fonts

### ISSUE THREAD

**Issue by gregblass** [rails/sprockets#229]
After upgrading sprockets from 2.3.3 to 3.0.0, none of my web fonts are loading. I was using this code:

    @font-face {
      font-family: 'derp';
      src: font-url('derp.eot');
      src: font-url('derp.eot?#iefix') format('embedded-opentype'),
           font-url('derp.woff') format('woff'),
           font-url('derp.ttf') format('truetype'),
           font-url('derp.svg?#derp') format('svg');
      font-weight: normal;
      font-style: normal;
    }

Then in assets.rb:

    Rails.application.config.assets.paths << Rails.root.join('vendor', 'assets', 'fonts')  
    Rails.application.config.assets.precompile << /\.(?:svg|eot|woff|ttf)$/

I'm getting this:

    ActionController::RoutingError (No route matches [GET] "/assets/fonts/Derp.woff"):
    ActionController::RoutingError (No route matches [GET] "/assets/fonts/Derp.ttf"):

Does anyone have any idea if something was changed in this release that could be causing this issue? It's weird that its requesting a capital font name...I tried changing it to a capital D, but it didn't fix the issue.

**Comment by rafaelfranca** [comment]
You don't need the line with `Rails.application.config.assets.paths << Rails.root.join('vendor', 'assets', 'fonts')`. Could you remove that and see if that fix your problem?

**Comment by gregblass** [comment]
That doesn't seem to make any difference.

**Comment by rafaelfranca** [comment]
Thank for confirming.  Can you please provide a sample application that reproduces the error?

**Comment by jekuno** [comment]
Does `rake --trace assets:precompile` produce any warnings or errors?

**Comment by schneems** [comment]
Could you give us a small example app that reproduces the problem?

**Comment by gregblass** [comment]
I was able to fix this, but I can't quite remember what I did to do it. I think it was a combination of assets:precompile, clearing the cache in my browser, and adding #djrig4, or some random extra bit to the file. So not a sprockets problem after all.
