### ISSUE TITLE
Getting error when including manifest.js in Sprockets 3.0

### ISSUE THREAD

**Issue by jonricaurte** [rails/sprockets#23]
When I include a manifest.js, I get the following error:

Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( application.css )` to `config/initializers/assets.rb` and restart your server

Did not see this in the upgrade guide and was wondering if this should be documented?

Thanks.

**Comment by rafaelfranca** [comment]
Could you explain better how do you get this error?

**Comment by josh** [comment]
This *feature* has been around for a while in sprockets-rails. Perhaps you upgraded from an old version that introduced it?

**Comment by jonricaurte** [comment]
Yea, looks like it was something else.
