### ISSUE TITLE
Couldn't find the specified file on `app.config.assets.precompile` option

### ISSUE THREAD

**Issue by dex1t** [rails/sprockets#230]
I specified `foo/bar.svg` as precompile target. however v3.5.2 couldn't find `bar.svg`.
```
app.config.assets.precompile += %w(foo/bar.svg)
```
gem's versions are here:
rails (4.2.5.1)
sprockets (3.5.2)
sprockets-rails (3.0.0)

**Comment by schneems** [comment]
You need to add `foo` to the paths

http://stackoverflow.com/questions/14735635/add-folder-to-asset-pipeline-path

**Comment by dex1t** [comment]
Thanks. I'll try it. :runner:
