### ISSUE TITLE
Combining engines and transformers? (CoffeeScript and JSX)

### ISSUE THREAD

**Issue by rmosolgo** [rails/sprockets#231]
Hi there, 

Thanks for all your work on Sprockets 3! I've been learning a lot about the changes and it looks like the system is becoming a lot stronger. 

I'm trying to fix a bug with `react-rails` but I'm not sure where to go next. The issue is with `.js.jsx.coffee` files (:weary:), apparently `#= require` directives are being ignored.

Here's some relevant info I found: 
- In a `.js.jsx.coffee` file, CoffeeScript and JSX _are_ transformed to JSX, but the `#= require` directive is ignored. 
- Sprockets 3.x uses an engine for CoffeeScript (https://github.com/rails/sprockets/blob/3.x/lib/sprockets.rb#L122-L124)
- `react-rails` uses a transformer for JSX in Sprockets 3.x (https://github.com/reactjs/react-rails/blob/master/lib/react/rails/engine.rb#L5-L10)
- I added a failing test for `react-rails` here: https://github.com/reactjs/react-rails/pull/453/files#diff-12252fd17a637f609790b7868b648ecaR2
- There's a Rails app that reproduces the issue here: https://github.com/tmikoss/react-rails-coffeescript-require-example

Do you have any suggestions what I can try next? Is there some way I can attach the JSX transformer that will cause `.js.jsx.coffee` files to be handled correctly?

**Comment by schneems** [comment]
Is this the same issue as https://github.com/rails/sprockets/issues/209 ?

**Comment by rmosolgo** [comment]
I don't think so. I think that other issue had to do with requesting asset by its _original_ file extension. If I understand correctly, `require_asset("my_file.js.coffee")` behaves differently in Sprockets 2 vs Sprockets 3. In Sprockets 2, it _does_ apply transformation, but in Sprockets 3, it _doesn't_ apply transformation. 

Of course, the new behavior makes a lot more sense, but it broke some code that was using the _original_ file name to generate "compiled" assets. 

This one is different in couple ways: 

- Instead of `require_asset` in Ruby, it surfaces via `//= require` directives in assets 
- It _does_ transform assets, but it _doesn't_ follow a second `#= require` directive

**Comment by bogdanRada** [comment]
I have a similar problem , considering the code below, although i have a transformer registered for 

``` .scss.erb``` seems that instead of calling first the ErbProcessor and then preprocessor , 
the preprocessor is called first, and it receives the erb file, which should not happen, or am i missing something? This only happens with sprockets 4.0.0.beta2. 

```
  register_mime_type 'application/scss+ruby', extensions: ['.scss.erb', '.css.scss.erb']
  register_mime_type 'application/sass+ruby', extensions: ['.sass.erb', '.css.sass.erb']

  register_transformer 'application/scss+ruby', 'text/scss', Sprockets::ERBProcessor
  register_transformer 'application/sass+ruby', 'text/sass', Sprockets::ERBProcessor

  register_preprocessor 'text/sass',  Sprockets::Sass::SassTemplate
  register_preprocessor 'text/scss', Sprockets::Sass::ScssTemplate
```

Or maybe i am missing the point of transformers and preprocessors? 

Also is there a way to unregister a transformer? I am working on sprockets-sass gem , and it seems that with this new version 4, this gem registers some transformers, which messes with my own transformers, and as a workaround i am trying to use them as preprocessors, but that doesn't seem to work when using the ErbProcessor .  


or any idea how to register a transformer before another transformer? that would make my day :) 

Any help would be appreciated.

**Comment by schneems** [comment]
I have a little more info. 

If you change the file name to `jsx-coffee-file.coffee` then it works. When you change it back you can see that the comments are being removed by the time they get to the directive processor.

I used your example and would build assets using:

```
$ rm -rf public/assets; rm -rf tmp/cache/assets/ ; RAILS_ENV=production bundle exec rake assets:precompile
```

Then I did a `bundle open sprockets` and added some puts to the directive processor

```ruby
    def _call(input)
      @environment  = input[:environment]
      @uri          = input[:uri]
      @filename     = input[:filename]
      @dirname      = File.dirname(@filename)
      @content_type = input[:content_type]
      @required     = Set.new(input[:metadata][:required])
      @stubbed      = Set.new(input[:metadata][:stubbed])
      @links        = Set.new(input[:metadata][:links])
      @dependencies = Set.new(input[:metadata][:dependencies])

      puts "== Processing #{ input[:name] }"
      puts input.inspect
      puts input[:data]
```

This is the output you get

```
== Processing jsx-coffee-file
{:data=>"(function () {\n  console.log(\"I should be the 4th log statement\");\n}).call(this);", :metadata=>{:dependencies=>#<Set: {"environment-version", "environment-paths", "processors:type=application/javascript&file_type=application/jsx&engines=.coffee&pipeline=self", "file-digest:///Users/richardschneeman/Documents/projects/tmp/react-rails-coffeescript-require-example/app/assets/javascripts/jsx-coffee-file.js.jsx.coffee"}>}, :environment=>#<Sprockets::CachedEnvironment:0x3ff568607140 root="/Users/richardschneeman/Documents/projects/tmp/react-rails-coffeescript-require-example", paths=["/Users/richardschneeman/Documents/projects/tmp/react-rails-coffeescript-require-example/app/assets/javascripts", "/Users/richardschneeman/.gem/ruby/2.3.1/gems/react-rails-1.5.0/lib/assets/javascripts", "/Users/richardschneeman/.gem/ruby/2.3.1/gems/react-rails-1.5.0/lib/assets/react-source", "/Users/richardschneeman/.gem/ruby/2.3.1/gems/coffee-rails-4.1.0/lib/assets/javascripts", "/Users/richardschneeman/.gem/ruby/2.3.1/gems/react-rails-1.5.0/lib/assets/react-source/production", "/Users/richardschneeman/.gem/ruby/2.3.1/gems/react-rails-1.5.0/lib/assets/javascripts"]>, :cache=>#<Sprockets::Cache local=#<Sprockets::Cache::MemoryStore size=12/1024> store=#<Sprockets::Cache::FileStore size=5473/26214400>>, :uri=>"file:///Users/richardschneeman/Documents/projects/tmp/react-rails-coffeescript-require-example/app/assets/javascripts/jsx-coffee-file.js.jsx.coffee?type=application/javascript&pipeline=self", :filename=>"/Users/richardschneeman/Documents/projects/tmp/react-rails-coffeescript-require-example/app/assets/javascripts/jsx-coffee-file.js.jsx.coffee", :load_path=>"/Users/richardschneeman/Documents/projects/tmp/react-rails-coffeescript-require-example/app/assets/javascripts", :name=>"jsx-coffee-file", :content_type=>"application/javascript"}
(function () {
  console.log("I should be the 4th log statement");
}).call(this);
```

So it looks like something in the JSX processor of yours is stripping the header before it gets to the directive processor.

**Comment by rmosolgo** [comment]
Thanks for taking a look and sharing your steps! I'll try the same thing and look at the react-rails code to see if I can find it.

**Comment by schneems** [comment]
@rmosolgo you had a chance to dig into this any more?
