### ISSUE TITLE
Non js/css compressors are ignored

### ISSUE THREAD

**Issue by toy** [rails/sprockets#246]
If I want to add a compressor for jpeg asset, then it seems logical to just register it using `register_compressor 'image/jpeg', :jpeg_compressor, JpegCompressor`.
But this doesn't work as just registering compressor doesn't add it to pipeline. Adding to pipeline happens only when calling `css_compressor=` or `js_compressor=` and only for css and js.
Is there a plan to make compressors work for other mime types? Otherwise it would be better to clarify this in documentation (especially in Extending Sprockets).

**Comment by schneems** [comment]
So, IDK. I inherited this project. I think you could make your own "compressor" with a transformer, check out https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md. Let me know if you've got questions, it's a WIP. If not, what does a "compressor" do that a "transformer doesn't?

What version of sprockets are you using, you should try on at least 3.3.x

**Comment by rafaelfranca** [comment]
compressors are only for JavaScript and CSS. We should make the documentation clear.

You can make your own JPG compressor using processors. Here is an example https://github.com/byroot/sprockets-svg/blob/master/lib/sprockets/svg.rb#L27

**Comment by mikong** [comment]
@rafaelfranca, do you think it's enough to update the documentation in the following?

* lib/sprockets/compressing.rb
* Extending Sprockets guide, compressors section

In lib/sprockets/compressing.rb, we can update the `Compressing` module documentation, and the `register_compressor` method documentation.
