### ISSUE TITLE
directive to prevent file from being cached

### ISSUE THREAD

**Issue by modosc** [rails/sprockets#247]
we are using `3.5.2` and have a js file like this:
```
function foo() { 
  <% if Rails.env.test? %>
  // short-circuit for tests because ajax testing in the capybara world is horrible
  return;
  <% end %>
  // do something here
}
```
this file is being cached and doesn't change when my local rails environment changes between `development` and `test`. i've worked around this by running `rake tmp:cache:clear` before and after each test run but i happen to know this is happening and can work around it - i expect many people wouldn't notice and might be suffering from side-effects. there are a few related older issues in the `sstephenson` fork:

sstephenson/sprockets#210
sstephenson/sprockets#486
sstephenson/sprockets#563

is this currently on anyone's radar or is there a known workaround? i'd also be happy to work on it.

**Comment by rafaelfranca** [comment]
Dup of https://github.com/rails/sprockets-rails/issues/325
