### ISSUE TITLE
add a Sprockets::Cache#clear method

### ISSUE THREAD

**Issue by modosc** [rails/sprockets#248]
is there any interest in this? initially i ran into a problem and reported it [here](rails/sprockets-rails#326) but since it's possible to set `assets.cache` to an arbitrary class it would be nice to add a high level `#clear` method that will try to proxy the call through to the underlying store (of course this means implementing this in the various stores as well).

is there a reason this functionality wouldn't be desired? i realize that for the most part clearing the cache isn't a common thing unless one is working on a processor/transformer/etc but i have run into [some issues](rails/sprockets#247) where this is necessary in a regular dev/test environment.

if this would be useful i'd be happy to implement it.

**Comment by rafaelfranca** [comment]
Could you explain why that is needed? We usually avoid to clear the cache. Your problem can be fixed having separate cache per environments and that is what we had in sprockets-rails 2.

**Comment by modosc** [comment]
separate cache per environments would definitely solve rails/sprockets-rails#325 - the other issue i'm running into is while i'm working on porting various processors to sprockets 3/4. i do a test assets build, make a code change, then run it again but the previously built asset is already compiled so i have to clear the cache. `rake tmp:cache:clear` works but that's (i think) only because i'm using the default disk cache store, right? if i was to use memcached i don't think the rake task would flush the cache. if it's not a common thing for people to use anything other than the default then no worries, i'll just deal with it.

**Comment by rafaelfranca** [comment]
I see. Make sense to me.

**Comment by modosc** [comment]
ok, i'll get a pr together. thanks!

**Comment by schneems** [comment]
We resolved that issue on sprockets-rails. Is this still a concern? Do you still have a need tof clearing the cache on clobber?
