### ISSUE TITLE
Incorrect upgrading link in 3.x changelog

### ISSUE THREAD

**Issue by gravitystorm** [rails/sprockets#261]
In the [3.x changelog](https://github.com/rails/sprockets/blob/3.x/CHANGELOG.md) under 3.0.0 there is a link to [https://github.com/rails/sprockets/blob/master/UPGRADING.md](https://github.com/rails/sprockets/blob/master/UPGRADING.md) . However, this url is now the guide to upgrading from 3.x to 4.x. 

I think the correct thing is to patch the 3.x branch so that that link points to [https://github.com/rails/sprockets/blob/3.x/UPGRADING.md](https://github.com/rails/sprockets/blob/3.x/UPGRADING.md)

**Comment by rafaelfranca** [comment]
Fixed
