### ISSUE TITLE
environment.unregister_processor doesn't unregister processor

### ISSUE THREAD

**Issue by tylerball** [rails/sprockets#266]
I have a simple directive processor that looks for javascript in some non-standard directories. I followed [this comment](https://github.com/rails/sprockets/blob/f7bfd95445d648da766755388f6085b77a79ad25/lib/sprockets/directive_processor.rb#L155-L176) in my implementation.

    class JsDirectiveProcessor < DirectiveProcessor
      def process_npm_directive(path)
        uri, deps = @environment.resolve!(path, accept: @content_type, pipeline: :self, load_paths: Dir["#{Rails.root}/**/node_modules"])
        @dependencies.merge(deps)
        @required << uri
      end
    end

Then I unregister the original and register my processor.

    Rails.application.config.assets.configure do |env|
      env.unregister_processor('application/javascript', Sprockets::DirectiveProcessor)
      env.register_processor('application/javascript', JsDirectiveProcessor)
    end

The files are included, but out of order. Dependencies included via `require` are included before the `npm` dependencies. Dropping a debugger into `configure` shows that `env.processors` contains multiple classes despite unregister.

    (byebug) env.processors
    {"application/javascript"=>[JsDirectiveProcessor, #<Sprockets::DirectiveProcessor:0x007fdb83737a38 @header_pattern=/\A(?:(?m:\s*)(?:(?:\/\/.*\n?)+|(?:\/\*(?m:.*?)\*\/)|(?:\#.*\n?)+|(?:\#\#\#(?m:.*?)\#\#\#)))+/>]}

**Comment by tylerball** [comment]
Interestingly, iterating through all the DirectiveProcessors seems to work: https://github.com/tylerball/sprockets/commit/6f4d41651c48fea8e3c07473fc6089bc90ac085e

**Comment by rafaelfranca** [comment]
Yes. The reason that iterating though all the processors work is that in one you are passing the instance of `DirectiveProcessors` as argument and in other you are passing the class `DirectiveProcessors`. Since `unregister_processor` is not smart enough you have to pass the same object that is inside the list, and in this case it is an instance of `DirectiveProcessors`.

**Comment by Strech** [comment]
@rafaelfranca Do you think that it's a good idea to remove all processors of a given class in case of the class name given? Want to have your approval, before taking action.

**Comment by rafaelfranca** [comment]
@Strech yes, I think it is acceptable.
