### ISSUE TITLE
way to disable gzip for assets precompile in sprockets 2?

### ISSUE THREAD

**Issue by abiacco** [rails/sprockets#267]
i'm using sprockets 2.12.4 to precompile assets to be served by apache. I'm trying to disable the gzipping of the assets but can't find a setting to accomplish this.
It seems like there's an option for this in 3.x, but 3.x versions make my precompile take 3x longer than with 2.x.
Any help is appreciated.

**Comment by rafaelfranca** [comment]
There is no way to do that with sprockets 2. I recommend you to upgrade to sprockets 3 as soon as possible. As you found performance problems we would love that you report them so we can fix it and your upgrade path is smooth as possible.

**Comment by schneems** [comment]
You can't. That I know of. Why do you want to disable gzip asset generation?

**Comment by mfittko** [comment]
CloudFront is handling this for us. Is it still not possible?
