### ISSUE TITLE
Slim processor does not work with JST 

### ISSUE THREAD

**Issue by kinnalru** [rails/sprockets#269]
sprockets-rails 2.3.3 version works well with slim temapltes in assets. For example with app/assets/snippets/onlinetv.jst.ejs.slim

But sprockets-rails 3.0.4 does not.

**Comment by rafaelfranca** [comment]
Sprockets doesn't have a Slim processor by default. If you are using a gem to add this processor maybe this gem needs to be changed to work with latest sprockets.

**Comment by schneems** [comment]
Open an issue with the maintainer of the slim processor, maybe show them this documentation https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
