### ISSUE TITLE
Uncaught ReferenceError: JST is not defined

### ISSUE THREAD

**Issue by vuhailuyen1991** [rails/sprockets#279]
My gem file: 

> gem 'execjs'
> gem 'jade-rails', '~> 1.11.0.0'
> gem 'sprockets', '~> 3.0'

My application.js 

> //= require turbolinks
> //= require jade/runtime
> //= require underscore
> //= require backbone
> 
> //= require app
> //= require_tree ./templates

When I load the page I get this error: `Uncaught ReferenceError: JST is not defined` 

I have no idea why JST is not loading. I have put a *.jst.jade file in /assets/javascript/templates/ folder and required the whole tree in application.js file. 

<img width="192" alt="screen shot 2016-04-18 at 8 48 39 pm" src="https://cloud.githubusercontent.com/assets/7251715/14606336/f70602a8-05a6-11e6-8fbd-a51d5a475201.png">

**Comment by schneems** [comment]
What is the exact version of sprockets you're using? ` $ bundle list | sprockets` 

Was this previously working? If so what version of sprockets were you using? 

I know nothing about JST, maybe https://gist.github.com/jgorset/1747655 could be helpful. Looks like https://github.com/rails/sprockets#javascript-templating-with-ejs-and-eco says you need .eco or .ejs file to make it work. I don't think the `.jade` works out of the box, you would need a gem for it. Something like https://github.com/zohararad/jader but I don't know if that works with sprockets.

**Comment by vuhailuyen1991** [comment]
Hi @schneems. 
1. Here is my sprockets version 
 * sprockets (3.6.0)
  * sprockets-rails (3.0.4)

2. I created a brand new app

3. I install the gem jader and it works now. I saw that jader requires `therubyracer` gem. I think it could be the missing one.

**Comment by schneems** [comment]
I'm thinking there should be some kind of `$ rake assets:extensions:list` task that will output all known file formats. Or maybe when we fail to find an asset with a given name list all assets with that name in a different extension.
