### ISSUE TITLE
Source maps for files in sub-directories don't work

### ISSUE THREAD

**Issue by siebertm** [rails/sprockets#284]
When playing with Sprockets 4.0.0.beta2 on one of our apps, I noticed a bug which leads to sourcemaps not working.

When I load an asset file from a subdirectory (`javascript_include_tag "sub/directory"`), the file contains a sourcemaps entry with a relative path duplicating the `sub` path:

```javascript
/# sourceMappingURL=sub/directory.js-SHA.map
```

This makes my chrome devtools request `/assets/sub/sub/directory.js-SHA.map` which of course fails.

To make sure it's not our (rather huge) application itself, I created a small test rails application to demonstrate the issue at [siebertm/sprockets-sourcemaps-bug](https://github.com/siebertm/sprockets-sourcemaps-bug)

This is a standard rails 5.0.0.beta3 `rails new` generated application. The offending files are [app/views/layouts/application.html.erb:10](https://github.com/siebertm/sprockets-sourcemaps-bug/blob/master/app/views/layouts/application.html.erb#L10) and [app/assets/javascripts/sub/directory.js](https://github.com/siebertm/sprockets-sourcemaps-bug/blob/master/app/assets/javascripts/sub/directory.js)

The default `application.js` sourcemap works like a charm!

Is this indeed a bug or am I misunderstanding anything here?

**Comment by schneems** [comment]
Basically everything I know about source maps I wrote into a guide. Looks like when it's a relative path it will use the parent's directory as the base from my notes here https://github.com/rails/sprockets/blob/master/guides/source_maps.md#source-map-detection

Thanks for the repro case. Source maps is still very much a WIP, and the only way to move it forwards is to break it with lots of example apps. I'll likely not be able to get to this before RailsConf.

**Comment by siebertm** [comment]
My first impulse was the question: "why no absolute paths?" Does the sprockets environment (or processor) know what the absolute path is?

**Comment by schneems** [comment]
Sprockets knows all! But sometimes it's expensive or difficult to compute. I didn't write the code for source maps (i inherited this project), so I don't know if that was done for a reason or it was a mistake. Would have to dig deeper.

**Comment by siebertm** [comment]
@schneems I'm currently trying to wrap my head around that issue and have a possible fix here. Will send a PR as soon as I deem it "ready"
