### ISSUE TITLE
Not loading .jst.hamlc assets

### ISSUE THREAD

**Issue by arjun-urs** [rails/sprockets#286]
After upgrading sprockets from 2.2.2 (in rails3) to 3.6.0 (in rails5), i am not able to use .jst.hamlc assets. 

Can you please have a look at this please?

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
