### ISSUE TITLE
`mtime` used in 2.x to determine cache freshness

### ISSUE THREAD

**Issue by agibralter** [rails/sprockets#287]
After a bit of digging into confusing asset-related bugs, I realized that we've been running into a cache-related race condition in our deployment process with asset pre-compilation. We are currently on the 2.x branch of Sprockets, so I'm not sure if this behavior still occurs in 3.x+.

In short, we use the Rails asset cache with memcache in order to vastly speed up `rake assets:precompile`. Since we share a cache for a single environment (e.g. "staging"), it's possible for asset changes in one branch/deployment to leak into another. This comes from this bit of code:

https://github.com/rails/sprockets/blob/v2.12.4/lib/sprockets/asset.rb#L231-L267

The pertinent line is `mtime.to_i >= stat.mtime.to_i`: if someone has changed a file, deployed, and filled the cache, that changed file will cause `dependency_fresh?` to resolve to `true` for any deploy with an older version of the file.

Now my question are:
- Is this something that still happens on the 3.x branch?
- Would sprockets be open to having this behavior (checking `mtime` before checking the file digest) be configurable/disableable?

Thanks so much!

**Comment by schneems** [comment]
Thanks for the report. Yes 3.x also uses mtime heavily. 

> Since we share a cache for a single environment (e.g. "staging"), it's possible for asset changes in one branch/deployment to leak into another.

Don't share a cache between different "environments" for this very reason. This isn't an expected or supported use of Sprockets.

**Comment by schneems** [comment]
Accidentally submitted too soon.

The 3.x branch is a stability branch. Nothing was removed (that I know of). Try out 3.6.0 and see if the problem persists. There's not much we can do to support the multiple apps using one cache case. If there is a fix for this that isn't invasive and performance prohibitive then i'm interested. The easiest thing would be to either use the filestore for staging and memcache for production or to use two seperate memcache instances. As a rule of thumb it's a bad idea to store datastores even if they're just a "cache".

**Comment by agibralter** [comment]
Thank you @schneems! Yeah... I kind of assumed this was a case of "it's not really meant to be used that way." I'll think it over. For now, we're removing our cross-environment asset cache.
