### ISSUE TITLE
Sprockets::NotImplementedError: Custom asset_path helper is not implemented

### ISSUE THREAD

**Issue by cmalpeli** [rails/sprockets#294]
I am getting the following when trying to precompile my assets locally

```
RAILS_ENV=production bundle exec rake assets:precompile

rake aborted!
Sprockets::NotImplementedError: Custom asset_path helper is not implemented

Extend your environment context with a custom method.

    environment.context_class.class_eval do
      def asset_path(path, options = {})
      end
    end
/Users/cman/.rvm/gems/ruby-2.2.2@jbd-ruby2.2.2/gems/sprockets-3.6.0/lib/sprockets/context.rb:198:in `asset_path'
/Users/cman/.rvm/gems/ruby-2.2.2@jbd-ruby2.2.2/gems/sprockets-3.6.0/lib/sprockets/context.rb:218:in `font_path'
/Users/cman/.rvm/gems/ruby-2.2.2@jbd-ruby2.2.2/gems/font-awesome-rails-4.6.1.0/app/assets/stylesheets/font-awesome.css.erb:15:in `_evaluate_template'
```

Any thoughts as to why this is occurring.  [As you can see in this SO thread ](http://stackoverflow.com/questions/36947064/sprockets-error-sprocketsnotimplementederror-custom-asset-path-helper-is-not)I've tried implementing it (though I don't understand why on earth I would need to).

**Comment by repinel** [comment]
@cmalpeli Could you make sample project with the problem?

**Comment by cmalpeli** [comment]
I'm going to close this issue.  I wound up pulling down my working production app from Heroku, verified everything precompiled and then slowly upgraded gems, verifying precompile still worked each step of the way.
