### ISSUE TITLE
Optionally skip compression for specific files

### ISSUE THREAD

**Issue by emptyflask** [rails/sprockets#298]
Some JS libraries are already compressed in the most efficient way, and some are actually broken when run through a compressor (like selectivizr a few years ago), so a feature like this would be useful:

```
//= require 'zxcvbn', compress: false
```

Discussed briefly with @schneems at RailsConf, but there's no obvious way to implement this yet.
Here's [the previous thread](https://github.com/sstephenson/sprockets/issues/394) on this topic.

**Comment by yoelblum** [comment]
@emptyflask @schneems So in the previous thread you mentioned it's not clear if this is the 'require' directive responsibility or the minifier's responsibility , any thoughts on that ? In other words:  what should be done to get where we want?

**Comment by SamMolokanov** [comment]
@emptyflask I tried to custom sprockets compressor to skip minification for already minified files, there is a Gist with workaround https://gist.github.com/SamMolokanov/efc441b44345c24662cf1063dd6ed950

PS. It is very naive and non-flexible, just an idea :)

**Comment by justqyx** [comment]
@SamMolokanov  Thanks for your idea, I'd like to take an experiment in the sandbox env of my project. Hope it can resolve the complication requirement of over 3000+ small files.

**Comment by schneems** [comment]
I made it so that compression is provided by an "extractor" you can unregister the current extractor and write your own with custom logic to skip any assets you want. Check out https://github.com/rails/sprockets/pull/386 for more info.
