### ISSUE TITLE
fstat unimplemented unsupported or native support failed to load

### ISSUE THREAD

**Issue by cha55son** [rails/sprockets#30]
Anyone have any clue why i'm getting this error from Sprockets 3.0.1?

ENV:
linux (CentOS 6.5)
jruby 1.7.12
Rails 4.1.1
Sprockets 3.0.1

```
NotImplementedError (fstat unimplemented unsupported or native support failed to load):
  org/jruby/RubyFile.java:1116:in `size'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache/file_store.rb:110:in `set'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:274:in `atomic_write'
  org/jruby/RubyIO.java:1182:in `open'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/path_utils.rb:273:in `atomic_write'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache/file_store.rb:108:in `set'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache.rb:210:in `set'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cache.rb:86:in `fetch'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/base.rb:53:in `file_digest'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/loader.rb:160:in `fetch_asset_from_dependency_cache'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/loader.rb:33:in `load'
  vendor/bundle/jruby/1.9/gems/sprockets-3.0.1/lib/sprockets/cached_environment.rb:20:in `initialize'
  org/jruby/RubyProc.java:290:in `call'
```

**Comment by josh** [comment]
Looks like its just trying to do `File.size`. The seems to be working here on my jruby 1.7.19.  I dunno if theres something different with the way jruby is configured on your system.

**Comment by cha55son** [comment]
Downgrading to sprockets 2.12.3 fixes the issue for me. Probably still
worth looking into what changed in newer version.

On Saturday, April 18, 2015, Joshua Peek <notifications@github.com> wrote:

> Looks like its just trying to do File.size. The seems to be working here
> on my jruby 1.7.19. I dunno if theres something different with the way
> jruby is configured on your system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/sprockets/issues/30#issuecomment-94210568>.
>


-- 
Thanks,
Chason Choate

**Comment by rafaelfranca** [comment]
@cha55son could you provide an way to reproduce this error so we can take a look?

**Comment by josh** [comment]
Anyone up for getting a PR going to add jruby to .travis.yml and working out all those bugs?
