### ISSUE TITLE
How Sprockets Works - doc

### ISSUE THREAD

**Issue by schneems** [rails/sprockets#308]
@rafaelfranca I got your video from RailsConf transcribed https://gist.github.com/schneems/08f2cb98ad5629a6b9115bff5bc0a972

It would be killer if we could go through that, fix some of the missed transcriptions and add code examples from your slides to make this either a blog post or a guide.

If anyone is interested in this effort please chime in here. 
Here are slides https://speakerdeck.com/rafaelfranca/how-sprockets-works 

Here is the talk: https://www.youtube.com/watch?v=CzFFYelG7WY

**Comment by rafaelfranca** [comment]
OMG! Of course. I'll review this tomorrow.

**Comment by dixpac** [comment]
@schneems @rafaelfranca I would love to help because I'm currently trying to figure out how sprockets work :)

Because I'm not exactly sprockets guru how can I help, what would u like me to do ?

:)

**Comment by schneems** [comment]
Can you view this? https://docs.google.com/document/d/1Srn4lZgyZwgMBGmRHLYRksdDavamhH8xvJ8_UTtNbps/edit?usp=sharing

Can you request access to edit?

Basically we need to go through that transcript and add in code examples and do some light copy editing.

You don't need to know what's going on, but be able to follow the transcript along with the video and turn slides into code examples.

**Comment by dixpac** [comment]
@schneems  requested, thnx!

**Comment by schneems** [comment]
I want to make it understandable without the context of the talk. So basically go crazy. I think google docs keeps a diff when contributors make changes so we can undo something if it was too much.

I'm thinking we take out the stuff like introduction, maybe add a little intro section explaining the context. 

We can also remove verbal things like "so" and "um". I really want to add code examples straight into the doc.

I'm going through the first bit of it now, maybe you can follow the changes after that.

**Comment by dixpac** [comment]
sounds great .....I will try to put in code examples tonight :)

**Comment by dixpac** [comment]
@schneems  manage to add all of the code into document and also do some light editing (sections, etc...), will try to put some more work on weekend :)

**Comment by schneems** [comment]
Thanks! You're awesome!
