### ISSUE TITLE
Asset was not declared to be precompiled in production

### ISSUE THREAD

**Issue by radar** [rails/sprockets#316]
I believe I've encountered a bug with Sprockets 4.0.0-beta2 and how it does path resolution for assets. I have an app which can reproduce the problem here https://github.com/radar/twist/tree/sprockets-bug

Steps to reproduce:

1. `bundle install`
2. `bundle exec rspec spec/features/accounts/sign_up_spec.rb`

Here's what I see:

```
Failure/Error: <%= javascript_include_tag "accounts/plans" %>

ActionView::Template::Error:
  Asset `accounts/plans.js` was not declared to be precompiled in production.
  Declare links to your assets in `assets/config/manifest.js`.
  Examples:
  `//= link ../javascripts/application.js`
  `//= link_directory ../javascripts .js`
  `//= link_directory ../stylesheets .css`
  `//= link_tree ../javascripts .js`
  `//= link_tree ../images`
```

This is understandable and true. I haven't declared that asset.

However, when I follow this advice of adding the asset to `assets/config/manifest.js`, like this:

```js
//= link_tree ../images
//= link ../javascripts/accounts/plans.js
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```

It now tells me:

```
Failure/Error: //= link ../javascripts/accounts/plans.js

ActionView::Template::Error:
  couldn't find file '../javascripts/accounts/plans.js' under '/Users/ryanbigg/Projects/twist/app/assets/config'
```

However, this works:

```
cd /Users/ryanbigg/Projects/twist/app/assets/config
file ../javascripts/accounts/plans.js
```

So I am not sure where it's trying to look for this file.

**Comment by schneems** [comment]
Thanks for the report I can try and dig in on Monday.

**Comment by radar** [comment]
I just tried `//= link accounts/plans.js` and that apparently works. I think I was misled by this line in the original error:

```
`//= link ../javascripts/application.js`
```

**Comment by schneems** [comment]
I fixed this error message in sprockets-rails https://github.com/rails/sprockets-rails/pull/329

However the version of sprockets-rails you're using shouldn't have given you an error message telling you about `config/manifest.js`.

Let me know if there's anything else we need to look at.
