### ISSUE TITLE
require gems with sprockets

### ISSUE THREAD

**Issue by miguelalarcos** [rails/sprockets#317]
Hi, I'm making a realtime web framework (with rethinkdb) where I'd like to use sprockets. This is my config.ru file:

```ruby
require 'opal'

run Opal::Server.new { |s|

  s.append_path '.'
  s.append_path '..'
  s.append_path '../../app'
  s.append_path '../../app/client'

  s.debug = true
  s.source_map_enabled
  s.index_path = 'index.html'
  s.main = '../../app/client/main'
  
}
```

This is my index.html file:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="http/build.css">
    <script src="/assets/opal.js"></script>
    <script src="/assets/main.js"></script>

</head>
<body>
<div id="container"></div>
</body>
</html>
```

I run `bundle exec rackup` and open `http://localhost:9292/`. But I've got this error:

```
main.js:1 Uncaught Error: Sprockets::FileNotFound: couldn't find file 'browser' with type 'application/javascript'
  (in /home/miguel/.rvm/gems/ruby-2.2.2/gems/sprockets-3.6.1/lib/sprockets/resolve.rb:64:in `resolve!')
```

This is my ruby file where I require 'browser' gem:

```ruby
require 'browser'
require 'browser/socket'
require 'browser/delay'
require 'promise'
require 'json'
require 'time'
...
```

If I use `require_tree 'browser'` the error is not shown, but I'm not sure this is a good solution. Is there a way of use the normal `require 'some gem'` with sprockets? Thanks.

**Comment by schneems** [comment]
I think that sprockets "require" and opal's "require" may be getting in the way here. Can you give me a small example app so I can play around here? I've never tried using opal + sprockets together. 

I did find https://github.com/opal/opal-sprockets

**Comment by miguelalarcos** [comment]
Thanks for the quick reply.

This is a minimal code:
index.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <script src="/assets/application.js"></script>
</head>
<body>
</body>
</html>
```
config.ru:
```ruby
require 'opal'

run Opal::Server.new { |s|
  s.append_path 'app'
  s.debug = true
  s.source_map_enabled
  s.main = 'application'
}
```

And this is app/application.rb:
```ruby
require "opal"
require 'bigdecimal'
```
When I go to http://localhost:9292/ I get the error:
```
Sprockets::FileNotFound at /
couldn't find file 'bigdecimal' with type 'application/javascript'

Ruby	/home/miguel/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/resolve.rb: in resolve!, line 64
```

**Comment by schneems** [comment]
I don't know how to run that. You've got no dependencies specified Gemfile, Gemfile.lock etc. Can you put that in example app form?

**Comment by miguelalarcos** [comment]
I'm sorry.

This is the Gemfile:

```ruby
gem 'opal'
```
`bundle install`

This is app/application.rb after edit 1:

```ruby
require 'opal'
require 'browser'
```

And you run this by `bundle exec rackup`.

(sorry again I don't see an example app form)

**Comment by schneems** [comment]
No worries. Go to github.com and click "new repo". Locally run `mkdir exampleapp` then `cd exampleapp` then `git init` then add all your files until it works then run `git add .; git commit -m first`. Follow the directions from github on pushing your local repo to github. Once you're comment here and link to the repo.

Here's me riffing on example apps a bit: https://youtu.be/qxaE8yblHPk?t=15m31s

**Comment by miguelalarcos** [comment]
[the repo](https://github.com/miguelalarcos/example-opal-sprockets)

Please tell me anything more you need.

**Comment by dixpac** [comment]
Hey @miguelalarcos been playing a bit with you `Opal` setup. Open uses sprockets 3.1 internally, so your problem is more of a opal implementation then sprockets per se.

Opal has this "opal" gems which are working like a charm `opal-rspec, opal-jquery. opal-browser.etc....` but as far as I know they can't promise that any ruby gem will work with opal. 
There are some workarounds when requiring other ruby gems in opal file, such as adding gems `lib` path to Opal load path by using `Opal.use_gem`
[http://stackoverflow.com/questions/24573142/can-i-use-ruby-gems-in-opal](Can I use Ruby gems in Opal?)

I would recommend you to join opal Gitter channel and try to ask them this same question here I think they will be able to help you
https://gitter.im/opal/opal

:)

**Comment by miguelalarcos** [comment]
Hi @dixpac 

Thank you very much for the info!

**Comment by Strech** [comment]
@miguelalarcos I think you miss the most important part about `opal-browser` – it has to be presented in your Gemfile

```ruby
# Gemfile

source 'https://rubygems.org'
gem 'opal'
gem 'opal-browser'
```

```ruby
# config.ru

require 'opal'
require 'opal-browser'

run Opal::Server.new { |s|
  s.append_path 'app'
  s.debug = true
  s.source_map_enabled
  s.main = 'application'
}
```

And the rest is the same as in your repo. I've added [working example for you here](https://github.com/Strech/example-opal-sprockets/commit/48177ffa8480f4c64ed482d43d5e983b4653f092)

**Comment by Strech** [comment]
@miguelalarcos If this issue is solved, can you close it?
