### ISSUE TITLE
custom mime and transform for riotjs

### ISSUE THREAD

**Issue by u007** [rails/sprockets#319]
hi,

ive extended padrino sprockets to try to run riotjs .tag
::Sprockets.register_mime_type 'text/riot-tag', extensions: ['.tag.js']#, charset: :unicode
::Sprockets.register_transformer 'text/riot-tag', 'application/javascript', ::Padrino::Processor::RiotProcessor

but when i require in application.js
//= require tags/myfile

i wish to have a preprocessor that compile the .tag by running command line riot which produces a javascript.
ive put in def call, but the processor is not being called...
it fails to find tags/myfile.tag of type application/javascript

did i do it wrongly?
my files are located here:
https://github.com/u007/padrino-sprockets

sorry that i do not know where else to ask...

thank you

**Comment by schneems** [comment]
That project is locked to Sprockets 2.x in the gemfile. Everything I know about transformers is written in https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#transformers . Note that Sprockets 2 and 3 work differently with processors/transformers/etc for example Sprockets 2.0.5 which you're locked to in that project you linked doesn't even have a `register_transformer` method

Take a look at the coffeescript transformer and see how it's implemented. If you run into something suprising that isn't documented please write down some notes and either add them to this issue or open a PR with updates to that guide.

**Comment by u007** [comment]
hi schneems,

no, its not locked at sprocket 2, its >= 2.2 for sprocket-helper
ive updated padrino-sprocket (my version) to enforce 3.6
and im still getting this :after msg
Error: Sprockets::FileNotFound: couldn't find file 'tags/tree-list' with type 'application/javascript'
  (in /private/var/www/akeypoints/app/assets/javascripts/application.js:12)

ive app/assets/javascripts/tags/tree-list.tag 

it does not seems to even load my transformer class
https://github.com/u007/padrino-sprockets

**Comment by u007** [comment]
the code is state here
https://github.com/u007/padrino-sprockets/blob/master/lib/padrino/sprockets.rb
line 87
::Sprockets.register_mime_type 'text/riot-tag', extensions: ['.tag']#, charset: :unicode
        ::Sprockets.register_transformer 'text/riot-tag', 'application/javascript', ::Padrino::Processor::RiotProcessor
        ::Sprockets.register_preprocessor 'text/riot-tag', ::Sprockets::DirectiveProcessor.new(comments: ["//", ["/*", "*/"]])
