### ISSUE TITLE
undefined method `lookup_asset_for_path' for #<#<Class:0x000000057d2058>:0x007f5db926e5f8>

### ISSUE THREAD

**Issue by davidalejandroaguilar** [rails/sprockets#337]
The error started when I installed Jquery-migrate-rails from this repo: https://github.com/krishnasrihari/jquery-migrate-rails.

After that, no matter how many commits I go back, I can't get out of that error.

Here's the screenshot of it:
https://gyazo.com/3f617e80aa9643e87ecd559fcd09f91c

I found this method which I think was deprecated on Sprockets 3.x:
```
lookup_asset_for_path(path, options = {})
Internal method to support multifile debugging. Will eventually be removed w/ Sprockets 3.x.
```

I think my app is somehow calling that method, but I really don't know, I've spent days on this. Any help would be greatly appreciated.

- David

**Comment by davidalejandroaguilar** [comment]
This was actually compatibility issues with my Rails version and https://github.com/schneems/sprockets_better_errors

**Comment by vaguila95** [comment]
How did you fix it??

**Comment by davidalejandroaguilar** [comment]
Don't remember, sorry. Perhaps my last post can point you in the right direction?

**Comment by vaguila95** [comment]
No worries, I ended up deleting the sprockets gem alltogether. Thank you anyway!
