### ISSUE TITLE
Watcher

### ISSUE THREAD

**Issue by merqlove** [rails/sprockets#341]
Hi all,
I want ask, `Sprockets` has some background watcher? Like in `Webpack`, `gulp` and others?
Very useful feature for SPA developers.

Just tried Sprockets 4.x, looks good, running well with Rails 4.2. But i have opinion, that environments with large number of assets must have asset change watcher in the background.

**Comment by rafaelfranca** [comment]
There is no support for watchers and we don't have plans to implement one.

**Comment by merqlove** [comment]
Ok, i understand.
Rafael, please tell me, Sprockets 4 currently stable as 3.x? It is next major release?

**Comment by rafaelfranca** [comment]
Sprockets 4 is the next major release, yes. It is not stable yet though.

**Comment by schneems** [comment]
I'm not opposed to the idea, but maybe we could instead implement hooks to reset caches and then let other libraries like Rails take care of the file watching. Either way there's no immediate plans for either option. I might come back to it in the future but there's way too much house cleaning that needs to be done first.

**Comment by merqlove** [comment]
Yeah, first Sprockets 4 must be stable as rock :)
