### ISSUE TITLE
Fingerprint inside source-maps

### ISSUE THREAD

**Issue by merqlove** [rails/sprockets#343]
How to disable it?
Rails 4.2, Sprockets 4
It not disabling by `config.assets.digest = false`
[lib/sprockets/source_map_processor.rb#L26](https://github.com/rails/sprockets/blob/master/lib/sprockets/source_map_processor.rb#L26)

When debugging via source-maps we need original filenames, otherwise available only in-browser debugging mode, which is not so comfortable way. You don't need source-maps at all if it contains files with name different than original :)

**Comment by merqlove** [comment]
I think that with source map Sprockets can skip on fingerprints every file, instead add or not fingerprint for the manifest linked source file and/or its source map.

**Comment by schneems** [comment]
I don't understand what the problem is. Can you give me an example app that reproduces the problem along with a description of what you were expecting and what you got instead?

**Comment by merqlove** [comment]
@schneems It can be same app as is my next issue: https://github.com/merqlove/sprockets4-source-map-bug

1. Currently, every element inside source-map has it's own fingerprint. 
2. Every time some element is charged, it's fingerprint inside the map too updating(with bug #344, but it is current logic of Sprockets site-maps).
3. If you want use any debugger like WebStorm, RubyMine, ... with your source-code outside the browser, debugger will not found any file, because your source files don't have fingerprints.

I don't understand why fingerprints needed inside SourceMap, due source map has its own fingerprint. Too difficult in my opinion. Source map can containtain only natural file-names., due you can change global source-map fingerprint.
Also i'm understand, that fingerprints in the heart of Sprockets logic. It helps Sprockets find & identify/cache files.

**Comment by merqlove** [comment]
@schneems hi, here some explanation

## Hard to use (because these fingerprints in the filenames inside SourceMap always changes...)
### Sprockets SourceMap
![Sprockets map](https://cloud.githubusercontent.com/assets/18354/16966237/b1649136-4e14-11e6-8bc0-97dcd9a0fd16.png)

## Easy to use
### Webpack SourceMap (no fingerprints in filenames)
![Webpack example map](https://cloud.githubusercontent.com/assets/18354/17671526/7ebbcfc8-6328-11e6-829b-249c661b194b.png)

**Comment by TylerHorth** [comment]
I've been looking into this one. I think it's safe to remove fingerprints from sources since the source map processor adds fingerprinted source uri's to the links metadata attribute which will update the maps fingerprint. That being said, we will still require the `.source` pipeline suffix so the files aren't processed by sprockets when the browser requests them. 

I'll hopefully have a branch up soonish which will address this.

**Comment by merqlove** [comment]
@TylerHorth, looks like state of current topic was resolved.
But, now filenames in the map has suffix `.source`.
Can we drop it at all? To have original names in map.
