### ISSUE TITLE
Registered transformer not called

### ISSUE THREAD

**Issue by mihai-dinculescu** [rails/sprockets#348]
I'm trying to register a transformer without much luck. It is simply not called.
    
     # transformer
    class MyTransformer
      def self.instance
        @instance ||= new
      end
    
      def self.call(input)
        instance.call(input)
      end
    
      def call(input)
        { data: '#TRANSFORMED#' + input[:data] }
      end
    end

    # registration
    require 'sprockets'    
    Sprockets.register_mime_type 'text/typescript', extensions: ['.js.ts']
    Sprockets.register_transformer 'text/typescript', 'application/javascript', MyTransformer

Registering it as a preprocessor makes the transformation happen, but it should obviously be a transformer, right?

Inspecting `assets.transformers.first` shows the transformer as registered
`["text/typescript", {"application/javascript"=>#<Proc:0x00000002ed3e68 (lambda)>}]`

What am I doing wrong?

**Comment by schneems** [comment]
Can you give me an example app?

**Comment by mihai-dinculescu** [comment]
Never mind, it works just fine :)

When registering as an engine, `assets['javascripts/hello']` used to return the processed version. 

After the change to `register_transformer`, `assets['javascripts/hello']` returns the unprocessed file and I have to do `assets['javascripts/hello.js']` in order to access the processed result.
