### ISSUE TITLE
Sprocket 4.0 development stopped?

### ISSUE THREAD

**Issue by rubyonrails3** [rails/sprockets#364]
I wanted to try to ES6 on my rails project as including webpack is bit of pain with Rails project.. and I came across Sprock 4.0 and tried beta version it seems to work but it makes each request very slow. and I've also seen there is no update for about 6months. Is Sprocket 4.0 development halted and is there a way to try newest build which is not 6 month old?

**Comment by schneems** [comment]
> Is Sprocket 4.0 development halted

No, but development is slow. I spent a long time working with sprockets 3.x to add deprecations so people can prepare for sprockets 4 upgrade.

> and is there a way to try newest build which is not 6 month old?

No, what is on master is the latest. I run it in production. I believe Shopify does as well. To get Sprockets 4 across the line we need more bug reports and data. Sprockets 4 was not completed when the maintainer left, so we're having to figure out everything from scratch.

> but it makes each request very slow. 

I've already implemented quite a few performance patches, this is something I care about. For the slowness, can you give me an example app that I can use to benchmark? If I can reproduce the slowness maybe I can patch it.

**Comment by rubyonrails3** [comment]
@schneems  Just double checking we can't do `import MyClass from 'myclass'

**Comment by schneems** [comment]
> Just double checking we can't do `import MyClass from 'myclass'

I've got no idea. I haven't implemented any of the es6 stuff myself. We lean heavily on babel, so anything babel can do we should be able to do as well?

**Comment by rubyonrails3** [comment]
I can't use `import` syntax in 3.x.x version of sprocket as I'm working with Rails 5 but if I try beta I can use import syntax though.

**Comment by schneems** [comment]
If something isn't working that you think should, please open an issue and attach an example app so I can debug it first hand.
