### ISSUE TITLE
Incorrect timestamps for images assets

### ISSUE THREAD

**Issue by RogerE** [rails/sprockets#37]
After we started using Sprockets 3 we are seeing some strange timestamps for the image assets. With version 3.0.1 they where set to 'Jan 1 1970', now with 3.0.2 'May 25 2008'.

**Comment by josh** [comment]
I know where that date is coming from, but its mostly supposed to be a fallback in case an asset somehow doesn't have any files on disk to base the mtime from.

https://github.com/rails/sprockets/blob/2baf38c08e2de74e9b8843690f01f57093dafa66/lib/sprockets/loader.rb#L144-L152

Can you help me narrow down the type of asset that is using this fallback date.

**Comment by RogerE** [comment]
Anything other than .js and .css gets this date, eg. images and fonts. And it happens both for assets included in the project and from gems. 

It started happening when we switched to Sprockets 3 as part of upgrading from Rails 4.2.0 to 4.2.1 for several different Rails projects. We're on Ruby 2.2.2 and deploy with Capistrano 3.

Let me know if there is anything else we can do to help.

**Comment by josh** [comment]
> images and fonts

Ah, interesting. Okay, let me see I can reproduce that there. Maybe its losing its original mtime somewhere.

**Comment by josh** [comment]
Thanks! Fixed in bd96c323f30e2fabd878cc393466edfacf5f0962

**Comment by RogerE** [comment]
Great, thanks!
