### ISSUE TITLE
Adding load path

### ISSUE THREAD

**Issue by chlebta** [rails/sprockets#373]
### Expected behavior

In my `application.js` I'm trying to add `/= require` file that exist in different directory then `javascript`  folder
### Actual behavior

I get always

> Sprockets::FileNotFound at /
> couldn't find file 'datatables/dataTables.bootstrap' with type 'application/javascript'
### System configuration
- Sprockets version : 3.6.2
- Sprockets-rails version : 3.0.4
- Ruby version : 2.3.0
- Rails version : 5.0.0.rc1
### Example App

This is my `application.js` : 
`//= require datatables/dataTables.bootstrap`

This is my `config.ru` : 

```
# This file is used by Rack-based servers to start the application.

require_relative 'config/environment'

require 'sprockets'
map '/assets' do
  environment = Sprockets::Environment.new
  environment.append_path 'vendor/plugins/adminlte/plugins'
  run environment
end

map '/' do
  run Rails.application
end

# run Rails.application
```

And this is the link of folder I'm trying to add :

> https://github.com/80percent/adminlte-rails/tree/master/vendor/assets/plugins/adminlte/plugins

**Comment by gilesbowkett** [comment]
I believe this is a non-issue.

@chlebta I created an example app here based on your description:

https://github.com/gilesbowkett/sprockets-373-example

I couldn't figure out your meaning when you said "the link of the folder I'm trying to add." definitely go ahead and fork my example and send a PR if you want to clarify that.

however, I think you won't need to.

the [readme](https://github.com/80percent/adminlte-rails) for AdminLTE, the gem you're trying to use, says that this line:
```
= require datatables/dataTables.bootstrap
```

goes in the `application.css` file. But your description above says that you put it in the `application.js` file.

So, although I was unable to reproduce your error in my example app, I think you may have just put a CSS require inside a JS file.

**Comment by schneems** [comment]
I made this PR but never got it over the line https://github.com/rails/sprockets/pull/322 would show you all the load paths when you get an error.

Is this still an issue? Did you get it working?
