### ISSUE TITLE
Usage of random() in a sass stylesheet breaks sprockets

### ISSUE THREAD

**Issue by MartinodF** [rails/sprockets#38]
Having just updated to sprockets 3.0.2, my rails app began to raise a Sprockets::VersionNotFound exception when evaluating `stylesheet_link_tag('application')`.

Here's the complete error:

````
could not find specified id: file:///[...]/app/assets/stylesheets/application.scss?type=text/css&pipeline=self#4563a7b014631a51625729c3ac881b6d4bc10d5ee7b37f41c001461ad54a7a1a
````

I tried stepping through both `sprockets` and `sprockets-rails` and I traced it down to multiple consecutive calls to `Sprockets::Loader.load`. The first one creates a new Asset with a corresponding id. The second one tries to lookup the cached asset by id, but fails since the compiled stylesheet contains different random values and the ids don't match.

Now, I understand that using `random()` in a sass stylesheet is kind of unusual (we need a ton of randomized values to get some complex CSS animations to look natural and this was much easier than hardcoding them by hand). I also haven't tried simulating a deployment so I don't know if this happens in production too. I still believe that, even if the problem was unfixable without significantly altering the sprockets architecture, it would at least warrant some kind of warning or a more specific error message.

I can reproduce the bug easily, so let me know if you need a minimal repo to test it.

ruby 1.9.3p194 (I know, our client's IT department doesn't want to update)
rails 4.2.1
sprockets 3.0.2
sprockets-rails 2.2.4

**Comment by josh** [comment]
> Now, I understand that using random() in a sass stylesheet is kind of unusual (we need a ton of randomized values to get some complex CSS animations to look natural and this was much easier than hardcoding them by hand).

Is there any way you can just statically seed the initial random value?

>  I also haven't tried simulating a deployment so I don't know if this happens in production too.

Its not going to work. What will end up happening is one server is going to have random value A, and the next server is going to have random value B, etc. Which will likely result in 404s trying to link across to different assets that don't exist on multiple servers.

**Comment by josh** [comment]
>  my rails app began to raise a Sprockets::VersionNotFound 

I think Sprockets should also start gracefully degrading in this case. Instead of the exception, it *may* just logger warn the version wasn't found and treat it as a cache miss.

**Comment by MartinodF** [comment]
@josh Thanks for the feedback! I've tried looking into how sass `random()` works and there's not much I can do. `Sass::Util::CrossPlatformRandom` is a simple wrapper around `Random`. Only one instance of this class is ever instantiated (and then cached in `Sass::Script::Functions.class.@random_number_generator`), so even if I were to specify a fixed seed on creation, each following compilation of my stylesheet will have different values. There's no way to re-seed the random number generator from sass itself.

Either sass exposes `srand` to the language or it will require some serious monkey patching to make it sure that a) the random number generator is initialized with a seed and b) sprockets clears the cached instance before compiling a stylesheet.

I agree with you that a warning would be much better than an exception in this case. I'm sure there's someone else doing something fancy with their assets that will encounter the same problem soon.

**Comment by MartinodF** [comment]
I will try to ping @nex3. Do you have any plans regarding having control on the seed of the random number generator behind sass' `random()`? Sprockets 3 at the moment doesn't play nice with non-deterministic stylesheets. Moreover, I'm sure it could be fairly useful for testing purposes. Thanks!

**Comment by josh** [comment]
890e11f201787280fe72755bbb77ba8f3e01b611

**Comment by nex3** [comment]
@MartinodF I'd accept a patch that did that, although I kind of feel like if you're using `random()` you should plan around nondeterminism.
