### ISSUE TITLE
Using register_mime_type and register_transformer instead of the deprecated register_engine leads to unnecessary compilation of files not in the precompile list

### ISSUE THREAD

**Issue by rmacklin** [rails/sprockets#384]
### Expected behavior

Per the Asset Pipeline rails guide (http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets - permalink [here](https://github.com/rails/rails/blame/47db952bf6938da78092096336d14c23b974a44c/guides/source/asset_pipeline.md#L722-L734)):

> anything that compiles to JS/CSS is excluded [from precompilation]

Thus, I expect sprockets not to precompile files that compile to JS.

### Actual behavior

Using `register_mime_type` and `register_transformer` to register a transformer for `.es6` files results in unnecessary precompilation of `.es6` files that are not in the precompile list. Changing it to just call the deprecated `register_engine` method fixes it (but isn't a good long-term fix since that method has been deprecated and replaced by `register_mime_type` and `register_transformer`). Full details are in the example app README.

### System configuration

- Sprockets version 3.7.0
- Ruby version 2.2.3

### Example App

https://github.com/rmacklin/sprockets_regression_demo

**Comment by rafaelfranca** [comment]
Are you using the manifest file to configure the precompile list? This is happening because the default precompile list get all files that are not `.js` and `.css` and include in the precompile list.

**Comment by rmacklin** [comment]
> Are you using the manifest file to configure the precompile list?

Are you asking if I have an `app/assets/config/manifest.js` file? If so, the answer is no.

> This is happening because the default precompile list get all files that are not .js and .css and include in the precompile list.

That seems contradictory to the note in the Rails guide:

> The default matcher for compiling files includes `application.js`,
`application.css` and all non-JS/CSS files (this will include all image assets
automatically) from `app/assets` folders including your gems:
```ruby
[ Proc.new { |filename, path| path =~ /app\/assets/ && !%w(.js .css).include?(File.extname(filename)) },
/application.(css|js)$/ ]
```
_NOTE: The matcher (and other members of the precompile array; see below) is
applied to final compiled file names. This means anything that compiles to
JS/CSS is excluded, as well as raw JS/CSS files; for example, `.coffee` and
`.scss` files are **not** automatically included as they compile to JS/CSS._

And indeed, `.coffee` files are _not_ precompiled. But the `CoffeeScriptProcessor` is registered via the deprecated `register_engine` method: https://github.com/rails/sprockets/blob/v3.7.0/lib/sprockets.rb#L127. That's what led me to try replacing `register_mime_type` and `register_transformer` with just `register_engine`, which is when I found using `register_engine` does not precompile the `.es6` files unnecessarily.

**Comment by rafaelfranca** [comment]
Yeah, that is exactly what is expected. `coffee` and `scss` files are also in the precompile list but register_engine doesn't use the mime type to compile files. Once it starts to use the mime type, if a file with that mime type is inside the precompile list it will be precompiled.

I recommend you to use the manifest file instead of precompile.

**Comment by rmacklin** [comment]
> Yeah, that is exactly what is expected.

Can you clarify what you are referring to by "that"? Are you saying that it's expected that when you change a sprockets plugin from using the deprecated `register_engine` to the new methods  `register_mime_type` and `register_transformer` it will have the side effect that unnecessary files will start getting compiled in applications that use the plugin? That seems really undesirable.

> I recommend you to use the manifest file instead of precompile.

It's good to know that's the recommendation but that's a concern to be handled by applications, not by a sprockets plugin.

**Comment by rafaelfranca** [comment]
Yeah, that is exactly what is expected. If the mime type is found in the
precompile list the transformer will be called.

**Comment by rafaelfranca** [comment]
It is not a regression, if there is a transformation registered and there
is a valid transformation target in the precompile list that transformation
should run.

This is the main difference between an engine and a transformation

**Comment by rmacklin** [comment]
I must be misunderstanding you. I want the files to be transformed to ES5. What I don't want is for them to be precompiled individually (only as part of application.js, or wherever they are `//= require`d) when they have not been added to the precompile list. This works with no issues (other than deprecation warnings) using `register_engine`. Upgrading to the replacements of `register_mime_type` and `register_transformer` will transform them to ES5 in application.js (or wherever they are `//= require`d), but will also compile them individually. Why is that desirable?

**Comment by schneems** [comment]
First of all, thanks for the bug report and the example app, it was very easy to repro with your instructions.

I can confirm that the example app compiles `thing.es6` even though it's not on the precompile list. It looks like `legacy.rb` is iterating over all contents in `app/assets/javascript` even if it's not in the precompile list https://github.com/rails/sprockets/blob/84a90b182a3ac71c23cff263b15dabe2e38e18f2/lib/sprockets/legacy.rb#L104-L118

Then sprockets-rails has a "loose assets" filter, i think the idea here was to pass through any image assets etc like `.png` you can see the code here https://github.com/rails/sprockets-rails/blob/10bc1bd096b39a3dd632571dd517788314657056/lib/sprockets/railtie.rb#L86

It get's added to the precompile list here: https://github.com/rails/sprockets-rails/blob/10bc1bd096b39a3dd632571dd517788314657056/lib/sprockets/railtie.rb#L108

So sprockets doesn't know what es6 is , so it assumes it's some kind of an image or video or special file so it falls through. Note that the public/asset/thing-1o3iu1oiuoivsjoisjd.es6 is not a compiled javascript file, but rather it is the raw es6 that was in app/assets

```
const square = (x) => x * x

class Animal {
  constructor(name) {
    this.name = name
  }
}
```

I don't know why this works when using register engine without `register_transformer`.

## Realtalk

So sprockets 4 has a built in es6 support, I would recommend using that over `sprockets-es6` there is a beta that seems to work, if not I need more bug reports. This bug won't happen when using register_transformer with sprockets 4 because the "loose assets" filter isn't being added when using sprockets 4. If you really really wanted to fix this in the short term, I might do something like this

```
if respond_to?(:register_engine)
    args = ['.es6', ES6]
    args << { mime_type: 'text/ecmascript-6', silence_deprecation: true } if Sprockets::VERSION.start_with?("3")
    register_engine(*args)
else
    register_mime_type 'text/ecmascript-6', extensions: ['.es6'], charset: :unicode
    register_transformer 'text/ecmascript-6', 'application/javascript', ES6
    register_preprocessor 'text/ecmascript-6', DirectiveProcessor
end
```

Which would solve the problem. The only unanswered question is why `register_engine` doesn't trip the loose asset fallback. Unfortunately even if we answer that I don't think we'll be able to change the behavior to "fix" this "regression" without breaking something else.

**Comment by rmacklin** [comment]
Thanks a lot for the detailed reply @schneems. I really appreciate it.

> Note that the public/asset/thing-1o3iu1oiuoivsjoisjd.es6 is not a compiled javascript file, but rather it is the raw es6 that was in app/assets

Yeah, I noticed that.

> I don't know why this works when using register engine without `register_transformer`.

I don't either, but when I was debugging yesterday I gathered a bit more information that may help. I ended up at the same `LOOSE_APP_ASSETS` filter and `Sprockets::Base#logical_paths` method you linked and here's what I noticed:

When `register_engine` is used, `logical_path` that gets passed to the `LOOSE_APP_ASSETS` filter is `thing.js`:

![screen shot 2016-09-16 at 4 10 32 pm](https://cloud.githubusercontent.com/assets/1863540/18610143/16e34312-7cc9-11e6-891c-9a8f15f830e2.png)

whereas with `register_mime_type` and `register_transformer`, `logical_path` is `thing.es6`:

![screen shot 2016-09-16 at 4 20 16 pm](https://cloud.githubusercontent.com/assets/1863540/18610140/16ddf1e6-7cc9-11e6-8520-7af63557f599.png)

This seems to be where the contradiction with the note in the Rails guide (_"The matcher (and other members of the precompile array; see below) is applied to final compiled file names..."_ ) begins.

Inside `Sprockets::Base#logical_paths`, when `register_engine` is used, the `mime_type` variable gets set to `"application/javascript"` (the "post-transformation" mime type):

![screen shot 2016-09-16 at 4 30 12 pm](https://cloud.githubusercontent.com/assets/1863540/18610142/16e04176-7cc9-11e6-8018-7e864b528d35.png)

so `mime_types[mime_type][:extensions].first` is `'.js'`, resulting in `logical_path` being `thing.js`.

But with `register_mime_type` and `register_transformer`, the `mime_type` variable is `"text/ecmascript-6"` (the "pre-transformation" mime type, i.e. [`from`](https://github.com/rails/sprockets/blob/v3.7.0/lib/sprockets/transformers.rb#L23), rather than [`to`](https://github.com/rails/sprockets/blob/v3.7.0/lib/sprockets/transformers.rb#L24)):

![screen shot 2016-09-16 at 4 25 36 pm](https://cloud.githubusercontent.com/assets/1863540/18610141/16de84e4-7cc9-11e6-8175-321cb265ac6d.png)

so `mime_types[mime_type][:extensions].first` is `'.es6'`, resulting in `logical_path` being `thing.es6`.

I stopped there as things get hairy when you get into [`compute_extname_map`](https://github.com/rails/sprockets/blob/v3.7.0/lib/sprockets/mime.rb#L111-L128) which makes me tend to agree with you on:

> I don't think we'll be able to change the behavior to "fix" this "regression" without breaking something else.

That said, I think it could be helpful to update the [Registering All Versions of Sprockets in Processors](https://github.com/rails/sprockets/blob/99444c0a280cc93e33ddf7acfe961522dec3dcf5/guides/extending_sprockets.md#registering-all-versions-of-sprockets-in-processors) documentation with this information. If you agree, I can submit a PR for that.

**Comment by rmacklin** [comment]
As for the "realtalk",

> So sprockets 4 has a built in es6 support, I would recommend using that over sprockets-es6

This is true, but I'm actually not able to use either sprockets-es6 or sprockets 4. The reason is that both rely on the `babel-transpiler` gem which is stuck on Babel 5, which doesn't support babel plugins (even if it supported Babel 6, the gem would need significant rearchitecting to support arbitrary plugins, which are implemented as individual npm packages).

So I actually ran into this issue not while using sprockets-es6, but rather while writing my own sprockets plugin for es6 transpilation. (I only used sprockets-es6 in my example app because it's already released so it was easier to demonstrate the issue using that.) My plugin needs to support sprockets 3 at least until sprockets 4 is out of beta and the applications using my plugin have had time to upgrade. In the meantime, I'll proceed with always using `register_engine` when it's available.

Thanks again for your reply!

**Comment by schneems** [comment]
Got it. I'm not up with all the babel libs, would love to see what yours looks like when it's ready.

**Comment by rmacklin** [comment]
Very late followup, but my sprockets plugin is finally released: https://github.com/rmacklin/sprockets-bumble_d (for a long time it was blocked by some outstanding changes I had submitted to babel). It's geared specifically toward migrating large codebases to ES6 modules (transpiled to UMD via babel), since that was my use case at work, but it works for general purpose babel transpilation.
