### ISSUE TITLE
Source map appears to be unable to find correct file

### ISSUE THREAD

**Issue by vincentwoo** [rails/sprockets#395]
### Example App

https://github.com/vincentwoo/sprocketstest

You should simply be able to checkout, `bundle install`, and `rails s`. Visit `localhost:3000` in chrome with debugger tools open
### Expected behavior

There's a file called `test.js` that just has `debugger` written in it. Chrome should show that when debugging.
### Actual behavior

For some reason, the two files included above `test.js`:

```
//= require codemirror
//= require sql
//= require test
```

cause the source maps to be unable to find `test.js` correctly. The debugging window opens up on the first line of `application.js`.
### System configuration
- Sprockets version: master
- Ruby version: 2.3.1

I have no idea if this is related to #388 or #157

**Comment by danshultz** [comment]
This is related to #388 - you'll note the number of lines off are related to the number of semicolons inserted causing it to point to the "application.js" file.

Note how https://github.com/vincentwoo/sprocketstest/blob/master/app/assets/javascripts/sql.js#L413 does not include a trailing semicolon (yes after the comments :sad:). So, sprockets will shove another one in with a newline.

You'll note the source map is off by exactly 1 line for your debugger statement.

**Comment by vincentwoo** [comment]
Okay, I'm happy to close this as a dupe of #388

**Comment by schneems** [comment]
Thanks for the issue. Re-opening to look at both example apps. Thanks for the report!

**Comment by vincentwoo** [comment]
Hi, I think this may be fixed on master now! I'll leave it at your discretion to close, though.
