### ISSUE TITLE
Add config option for memory cache size

### ISSUE THREAD

**Issue by TylerHorth** [rails/sprockets#409]
It's hardcoded [here.](https://github.com/rails/sprockets/blob/a270576b32d82f7a62ff2dcd82cd979cb777ffb9/lib/sprockets/cache.rb#L70)

Shopify was seeing ~5 second page load times after upgrading to sprockets 4. Doubling this value return load times to ~600ms. 

I don't know if this extra memory use and the thrashing that resulted from it are just due to the extra source map metadata, or if something else is going on.

cc @bouk @rafaelfranca

**Comment by schneems** [comment]
Can you give me a PR to set it from an env var? 

Would love ideas of ways we could add more information here. Maybe a debug mode to show when you're hitting max memory or getting close would be cool.

Should check on Heroku, I think we only have 512 memory in the container building your app which might be part of the speed problems.

**Comment by TylerHorth** [comment]
This issue is throwing me for a loop.

The cache size is bound by the [number of items](https://github.com/rails/sprockets/blob/a62c02556216ac7e3b0f09257b02cace439e280b/lib/sprockets/cache/memory_store.rb#L20-L21), not the amount of memory. Doubling the number of slots solved the issue, so clearly we're simply running out of space. 

This would make sense since in sprockets 4 we have to also store the source map for each file. EXCEPT, and here's the kicker, this problem no longer exists in #402. The only thing that has changed is the format of the source maps. There's still the same number of 'em, so we must still be running out of memory. 

OK, well perhaps we still are, we're just loading the files after cache miss much faster? The source maps did shrink in size, after all. But, load times went from 600ms to 5 seconds. Can this really explain a 10 fold increase in load time? Or did #402 just solved a problem I didn't even know existed? I don't know.

I'm going to do some testing and see if I can't figure out what's really going on here.

**Comment by schneems** [comment]
Did you ever come back to this issue? I still think being able to set the cache size would be good.
