### ISSUE TITLE
My first 5 minutes

### ISSUE THREAD

**Issue by woodall** [rails/sprockets#412]
@schneems, Just finished watching your [inspiring talk](https://www.youtube.com/watch?v=qxaE8yblHPk). The first thing I did with my 5 minutes was start reading the last 20 or so [closed commits](https://github.com/rails/sprockets/issues?q=is%3Aissue+is%3Aclosed) to see what kinds of activity is actually happening and determine if I would be able to help. Thanks for giving us ideas for ways to help with such an important project. I'll be back later. 👋

**Comment by schneems** [comment]
🚀
