### ISSUE TITLE
Potential Ruby Sass Deprecation

### ISSUE THREAD

**Issue by 412andrewmortimer** [rails/sprockets#414]
### Expected behavior

Sprockets should(?) continue to support Sass.

Now I'm not in this project, but I just read that Ruby Sass will be deprecated within 1 year if unmaintained. And to me that seems pretty impactful to this project. 
Source:  http://blog.sass-lang.com/
.

### Actual behavior

Ruby Sass is being potentially being deprecated.

> [If no one steps up] Ruby Sass will be officially considered deprecated and unmaintained.

**Comment by 412andrewmortimer** [comment]
This also may be kind of weird. 

https://github.com/sass/dart-sass/issues/14

**Comment by guilleiguaran** [comment]
I don't think Rails team have enough bandwidth to take the maintenance of Ruby Sass, if no one wants to maintains it in the future we can make [sassc-ruby](https://github.com/sass/sassc-ruby) (that is already supported by Sprockets) the default for Rails users.

Also we can explore the integration with dart-sass package through ExecJS/Node in the future.

**Comment by 412andrewmortimer** [comment]
Both of those sound like good ideas. At the least [sassc-ruby](https://github.com/sass/sassc-ruby) will available immediately. And if/when the ExecJS/Node bridge needs to be crossed it can.

**Comment by PikachuEXE** [comment]
sassc-ruby is not supported in sprockets 3.x though :S
And 4.x is still in beta... (generating source map in asset precompile still missing)

**Comment by PikachuEXE** [comment]
I think I can try to backport the sassc related classes (compressor and processor)
back to 3.x
Just not very sure what options should be used
Will submit a PR during Chinese new year (one week day off hehe)

**Comment by schneems** [comment]
Sassc is the ideal future. It's faster, and libsass is maintained. 

sassc-ruby has some edge cases on windows that I tried to get working, but ran into problems with. 

There is a sass-c processor in Sprockets 4, but it doesn't totally work and needs sass-rails support. A good next step for helping could be to get Rails apps to use Sprockets 4 and the sass-c using built in processor along with a fork of sass-rails. I got sassc working for codetriage/codetriage however I had to use a third party gem and not use our built in integrations.

**Comment by PikachuEXE** [comment]
Since I am using sprockets 3 so I think I will try [sassc-rails](https://github.com/sass/sassc-rails)

**Comment by 412andrewmortimer** [comment]
Is there a deprecation path for Sprockets 3? Is it realistic in my assumption that everything just needs to move forward, to Sprockets 4 support and therefore C Sass over Ruby Sass. And also, is this a bad thing? Are there reasons that Ruby Sass should be maintained over just moving to C Sass?
