### ISSUE TITLE
manifest.js for gems / engines?

### ISSUE THREAD

**Issue by richpeck** [rails/sprockets#415]
### Expected behavior

I included a gem's assets in its `/app/assets/../[gem_name]` folders.

Previously, I added `config.assets.precompile << %w(exception_handler/**)` to the Engine and the assets were precompiled successfully.

### Actual behavior

When I use it today, the error response is: 

``` Error during failsafe response: Asset `exception_handler.css` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.```

- I have added the required links to `/gem/app/assets/config/manifest.js` but the error still appears.
- I have added the required links to my app's `manifest.js` and it works perfectly

My question is how do I make the `manifest.js` file independent of the application? People will not put the individual links into their app's `manifest.js` file. _How do I add a `manifest.js` to my gem?_
 
### System configuration

- Sprockets 4.0.0.beta.4
- Ruby 2.3.1
- Rails 5.0.01

### Example App

Can provide specifics as required. This is a general issue involving Rails engines.

**Comment by TylerHorth** [comment]
From what I can tell, rails adds load paths for each directory of a gems assets folder. So you should just be able to put your manifest in, for example: `/gem_name/app/assets/config/gem_name/manifest.js`. (note the `gem_name` subfolder, so there isn't a naming conflict.)
Then, consumers can link to it from their manifest: `//= link gem_name/manifest.js`. 

Let me know how this turns out.

**Comment by richpeck** [comment]
I fixed this in the end by using the `link_tree` directive inside the CSS file, which I explicitly added to the precompile queue. Because `link_x` directives are available in both `3` & `4` versions of `Sprockets`, this seemed to work:

https://github.com/richpeck/exception_handler/blob/master/lib/exception_handler/engine.rb#L19
https://github.com/richpeck/exception_handler/blob/master/app/assets/stylesheets/styles/_base.css.erb#L8

**Comment by epipheus** [comment]
I don't understand, why wouldn't a gem's manifests be honored automatically?  Both via app/assets/config/manifest and vendor/assets/config/manifest in gems?

**Comment by AlexVPopov** [comment]
Hey @richpeck, sorry for pinging you for such an old issue. Did you find a solution to that problem, which:
a) doesn't require the users of a gem to do anything additionally (modify their `/app/assets/config/manifest.js`;
b) doesn't including adding an initializer in the gem, which explicitly adds the files for precompilation.

Is there a way to add `/gem/app/assets/config/gem_name/manifest.js/` and make sprockets load it automatically?

**Comment by AlexVPopov** [comment]
So according to the Rails guides the way to go is via an initializer: https://guides.rubyonrails.org/engines.html#separate-assets-precompiling

It seems that what I describe is not an intended workflow.

**Comment by epipheus** [comment]
but it should be.
