### ISSUE TITLE
NameError: uninitialized constant Sprockets::SafetyColons

### ISSUE THREAD

**Issue by blanchma** [rails/sprockets#416]
### Expected behavior

In previous version, I could unregister SafetyColons. 

### Actual behavior

NameError: uninitialized constant Sprockets::SafetyColons

### System configuration

- 3.7.0
- MRI 2.2.0

### Example App

Rake::SprocketsTask.new do |t|
  environment = Sprockets::Environment.new( File.expand_path(File.dirname(__FILE__)) )
  environment.unregister_postprocessor 'application/javascript', Sprockets::SafetyColons
  #environment.js_compressor = :uglifier
  environment.append_path Bower.environment.directory
  environment.append_path 'app/assets/javascripts'
  environment.append_path 'app/assets/webpack'
  environment.append_path 'app/assets/stylesheets'

  #environment.append_path 'public/assets'
  t.environment = environment
  t.output      = "./public/assets"
  t.assets      = %w( all.js all.css )
end

**Comment by gilesbowkett** [comment]
I expanded this out into a full example app here:

https://github.com/gilesbowkett/sprockets-issue-416

it uses Rails 4.2, since you said you're on Ruby 2.2.0, and Rails 5 requires 4.2.2.

I saw the same error you did, I'm just setting this up as a convenience for the maintainers.

**Comment by blanchma** [comment]
Thanks. I'm running this in a Cuba (almost vainilla Rake).

**Comment by gilesbowkett** [comment]
fwiw, I don't think Sprockets uses the `SafetyColons` processor any more. I couldn't find it anywhere in the source.

there is a `lib/sprockets/utils.rb` file with a `string_end_with_semicolon?` method, though, and there's also an `"appends missing semicolons"` test in `test/test_asset.rb`. So my guess is the `SafetyColons` functionality got moved somewhere else.

**Comment by gilesbowkett** [comment]
also, removing the implementation of `string_end_with_semicolon?` causes 85 test fails. that's about all I know at the moment.

**Comment by TylerHorth** [comment]
It looks like `SafetyColons` was removed [sometime after sprockets 2](https://github.com/rails/sprockets/blob/2.x/lib/sprockets/safety_colons.rb). 

@blanchma Could you explain your use case, why do you want to unregister it?

Semicolon insertion currently needs to be reworked, as it is breaking source maps [#388]. It may be the case that the solution to that fixes your issue?
