### ISSUE TITLE
Sprockets#logical_paths changed extension name

### ISSUE THREAD

**Issue by Martin91** [rails/sprockets#42]
Hello guys, I have meet a problem related to sprockets in Rails v4.2 but I can not determine if it is a bug from sprockets. The details is below:

1. I have an image named "something.jpeg" under `app/assets/partners/`, so the path for it is `app/assets/partners/something.jpeg`;
2. I have wrote the below line of code in a template:
```erb
<%= image_tag "partners/something.jpeg" %>
```
ok, everything works well under development environment. But when I started to precompile assets, something weird appears, the precompiled file name was changed to `something-e758d2d1631a23e0a91ef8366a803cc3e0d5e48d5ea99f62fd124c21a1911a6c.jpg`. See, the extension name of the file was changed from **"jpeg"** to **"jpg"**, which resulted in that my image can not be shown under production rails environment now.

The rendered template outputs something like:
```html
<img href="images/something.jpeg">
```
while something like the below is expected:
```html
<img href="/assets/something-e758d2d1631a23e0a91ef8366a803cc3e0d5e48d5ea99f62fd124c21a1911a6c.jpeg">
```
Now, to resolve the problem, I have to manually change extension names of my **special jpeg** images.

Additionally, I have debugged and found that the below codes might change extension names of assets:
https://github.com/rails/sprockets/blob/b131fdf727/lib%2Fsprockets%2Flegacy.rb#L109-L111
```ruby
path, mime_type, _, _ = parse_path_extnames(path)
path = normalize_logical_path(path)
path += mime_types[mime_type][:extensions].first if mime_type
```

But I am not sure if it is a bug, or if it should be fixed in rails instead. Can anyone help?

**Comment by josh** [comment]
Hey @Martin91, thanks for the report!

Pretty good find actually. This is really related to https://github.com/rails/sprockets/issues/40. I'll take this extension normalization edge case into account for the upcoming fix.

**Comment by schneems** [comment]
This still happening in 3.x or master of sprockets?

**Comment by tjouan** [comment]
> This still happening in 3.x or master of sprockets?

  I observe same issue in sprockets 3.7.0. Never understood why using
JPEG became problematic some time ago, and just avoided doing it until
now.

    Sprockets.register_mime_type 'image/jpeg', extensions: %w[.jpeg .jpg .jpe]

  Workaround issue with JPEG, but not a real solution for any mime
type with more than one filename suffix registered. Not very nice too.

  In my case, code responsible for filename change is not
`Sprockets::Base#logical_paths`, but
`Sprockets::Loader#load_from_unloaded`, in `sprockets/loader.rb' line
120 as of v3.7.0. Maybe it depends on cache state.

  Anyway I see no obvious fix, and maybe "fixing" issue and preserving
filenames suffix might be seen as broken behavior by sprockets users
who expect this kind of "normalization" happening?
(I realize it's from 2.x, but maybe some 3.x users rely on the "new"
behavior).
