### ISSUE TITLE
[Guides] Code from Extending Sprockets Guide produces error within Gem

### ISSUE THREAD

**Issue by tomprats** [rails/sprockets#421]
Using this code from the [extending sprockets guide] in my gem

```
module MySprocketsExtension
  def self.call(input)
    # code
    result = input[:data] # :data key holds source
    { data: result }
  end
end

require 'sprockets/processing'
extend Sprockets::Processing

register_preprocessor 'text/css', MySprocketsExtension
```

I get an error within [register_config_processor] when starting my rails server with the gem.

> Gem Load Error is: undefined local variable or method `config' for main:Object
> Backtrace for gem load error is:
> /Users/tom/.rvm/gems/ruby-2.3.1/gems/sprockets-3.7.0/lib/sprockets/processing.rb:211:in `register_config_processor'
> /Users/tom/.rvm/gems/ruby-2.3.1/gems/sprockets-3.7.0/lib/sprockets/processing.rb:51:in `register_preprocessor'
> /Users/tom/.rvm/gems/ruby-2.3.1/bundler/gems/sprockets-cjsx-9b647abb29e3/lib/sprockets-cjsx.rb:11:in `<top (required)>'

I created a new [rails app] that reproduces the issue. It's just a new app that I added a [gem] to. The [gem] is made up of the example code from the guide.

Versions: Ruby 2.3.1p112 and Sprockets 3.7.0

[extending sprockets guide]: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md
[register_config_processor]: https://github.com/rails/sprockets/blob/3.x/lib/sprockets/processing.rb#L211
[rails app]: https://github.com/tomprats/sprockets-test
[gem]: https://github.com/tomprats/sprockets-cjsx/blob/sprockets-test/lib/sprockets-cjsx.rb

**Comment by tomprats** [comment]
I created a [working version], but I'm not sure if it's bad because it's requiring so much more

```
require "sprockets"

module MySprocketsExtension
  def self.call(input)
    # code
    result = input[:data] # :data key holds source
    { data: result }
  end
end

Sprockets.register_preprocessor 'text/css', MySprocketsExtension
```

Let me know if you want me to create a pull request to change the example. Otherwise I'm here to further troubleshoot the original

[working version]: https://github.com/tomprats/sprockets-cjsx/blob/sprockets-test-alt/lib/sprockets-cjsx.rb

**Comment by schneems** [comment]
It could be useful to make this extension actually do something? Ideally we could even have a test for it and could update the test if the docs ever get updated. I think we want the guide code to be runable.

**Comment by tomprats** [comment]
There's an example before it that just adds a comment to the css. This one could be updated to just continue that. Should I add a new test file like test_guides.rb? And just add a test case for each block of code in the guides?

Additionally I've run into a problem adding a preprocessor for `text/coffeescript`. Using the same code but with a different mime type it's not getting run. Should I open a new issue for that? (Example [app] + [gem])

[app]: https://github.com/tomprats/sprockets-test/tree/coffee
[gem]: https://github.com/tomprats/sprockets-cjsx/blob/sprockets-test-coffee/lib/sprockets-cjsx.rb

**Comment by tomprats** [comment]
I opened a new issue for the other problem https://github.com/rails/sprockets/issues/423

**Comment by tomprats** [comment]
@schneems Bump. Mind responding to the questions above once you get a chance? Thanks!

**Comment by schneems** [comment]
> There's an example before it that just adds a comment to the css. This one could be updated to just continue that. Should I add a new test file like test_guides.rb? And just add a test case for each block of code in the guides?

That would be a good idea. Actually having this code tested would be great. We can put an HTML comment in the guides markdown pages pointing at the test file to so people know to update both.
