### ISSUE TITLE
images in manifest.js error

### ISSUE THREAD

**Issue by hesongGG** [rails/sprockets#422]
Hi, My rails4 app was upgrade to the rails5.
However, I'm deploy it have a issue 
```ruby
rails assets:precompile
```

Error: 
> 'NoMethodError: undefined method `split' for nil:NilClass'

I'm try to clear the manifest file content. Then to run:
```ruby
rails assets:precompile
```
it works.

Then keep try it, I found that this error is caused because the
```ruby
//= link_tree ../images
```

But , it work's fine with the Rails4.

Some current version
```ruby
rails -v  #5.0.0
sprockets (4.0.0.beta4, 3.7.0)
```

Now, I was deal with it use sprockets(3.7.0).
The above error， was a bug?

**Comment by richpeck** [comment]
Same for me

**Comment by richpeck** [comment]
The immediate hotfix is to reference [the following](https://github.com/rails/sprockets/blob/99444c0a280cc93e33ddf7acfe961522dec3dcf5/lib/sprockets/directive_processor.rb#L321):

>       # `link_tree` links all the nested files in a directory.
>       # Its glob equivalent is `path/**/*`.
>       #
>       #     //= link_tree "./images"
>       #
>       # Use caution when linking against JS or CSS assets. Include an explicit
>       # extension or content type in these cases.
>       #
>       #     //= link_tree "./styles" .css
>       #

This means you should look to call the following:

```
//= link_tree "../images" .png
//= link_tree "../images" .jpg
//= link_tree "../images" .jpeg
```

It's not the best solution but should get it working (for now).

**Comment by richpeck** [comment]
#427

**Comment by richpeck** [comment]
The error is specifically that you've included a file with an unrecognized `mime_type`.

Do you have any `.md` files or other obscure files present in that directory?

**Comment by hesongGG** [comment]
Hi, I'm sorry to reply you so late.
I remember I solved this problem by lowering the sprockets version.
There is no ``` .md ``` files.
