### ISSUE TITLE
asset-data-url SVG: encode via URL escaping instead of base64

### ISSUE THREAD

**Issue by glebm** [rails/sprockets#425]
While SVG images *can* be encoded as base64 in CSS, but it is more efficient to encode them directly.

This is a feature request for sprockets to do the same in https://github.com/rails/sprockets/blob/a9c65250f46429912dbbab2859dcb08bb5c32f95/lib/sprockets/context.rb#L199, maybe implemented like this:

```ruby
def asset_data_uri(path)
  asset = depend_on_asset(path)
  if asset.content_type == 'image/svg+xml'
    encoding = 'charset=utf-8'
    data = CGI::escape(asset.source).gsub('+', '%20')
  else
    encoding = 'base64'
    data = EncodingUtils.base64(asset.source)
  end
  "data:#{asset.content_type};#{encoding},#{data}"
end
```

(implementation based on https://github.com/ai/rails-sass-images/blob/852a33364d86f47884793fb2af1fcc541a706495/lib/rails-sass-images/sass/inline.rb)

**Comment by schneems** [comment]
Seems fine. Can you send me a PR?

> more efficient

How so? Is it faster or smaller or both? Can you share any numbers or benchmarks?

**Comment by glebm** [comment]
> How so? Is it faster or smaller or both?

It is smaller because base64 is ~33% larger on average than the string it encodes.
It is faster because the browser does not have to decode base64.

**Comment by glebm** [comment]
> Can you send me a PR?

I've sent a PR.
