### ISSUE TITLE
Files not loaded/available in development when filename starts with "+"

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [rails/sprockets#43]
I put the `+` symbol in front of the filename when I want it to have higher priority than the rest of the files in a given asset directory.

Example:

`[Rails.root]/app/assets/javascripts/page-specific/invoices/+first.js.erb`
`[Rails.root]/app/assets/javascripts/page-specific/invoices/an_example.js.erb`

I get 404's when using the `+` symbol only after updating sprockets to the latest release. An easy fix is to use underscores but I thought it was something worth mentioning.

**Comment by josh** [comment]
I just added a test for a `+` asset to see what would happen. 992f2581120de0edcd9f84a04c691a87dc42f194 Seems like it works fine. Do you think you could do some more debugging and figure out where its getting messed up. I bet theres some incorrect CGI escaping happening somewhere.
