### ISSUE TITLE
Circular dependency issues on js manifest files

### ISSUE THREAD

**Issue by yosefsun** [rails/sprockets#430]
### Expected behavior

When adding a resource on the manifest file, if the resource is having a circular dependency issue - Sprockets should throw an exception with the relevant error.

### Actual behavior

Nowadays, when such circular dependency happens - no error is being thrown and segmentation fault occurs.

### Steps to reproduce

Setup a js manifest file that have circular dependency (for example - one js file requesting the other and the other js file requesting the first one)

**Comment by schneems** [comment]
Can you give me an app that reproduces the problem please?

**Comment by yosefsun** [comment]
@schneems I encountered that issue when installing [polymer-rails](https://github.com/alchaplinsky/polymer-rails) which extends sprockets to support polymer web components and others. I suspect the issue is still with sprockets since AFAIK the extension still uses the **path_to_asset** method supplied by sprockets. 

If I'm wrong, please direct me to the right source of issue if you find any.

**Comment by yosefsun** [comment]
@schneems if you would like to reproduce this issue, simply bundle install the polymer-rails, run rails g polymer:install and add the following line to your application.html manifest file :

//= require paper-button/paper-button

**Comment by schneems** [comment]
I've played this game before, i always lose 😉 : https://speakerdeck.com/schneems/saving-sprockets.

![Please provide an example app](https://www.dropbox.com/s/woa4h08jwuobzgp/example-apps.gif?dl=1)

I usually spend maybe 30 minutes to an hour trying to reproduce a problem, which is 30 minutes to an hour less that I get to spend actually fixing issues 😬 . So huge ❤️❤️❤️ if you can throw it in a github app.

**Comment by montague** [comment]
@schneems FWIW, I was unable to reproduce using the steps given by @yosefsun using a fresh rails 5 app. 

I also attempted to reproduce using a vanilla rails app w/out polymer-rails here: https://github.com/montague/sprockets-circular-js-dep/tree/master/app/assets/javascripts

Hope this is helpful.
