### ISSUE TITLE
Huge memory usage in 3.7

### ISSUE THREAD

**Issue by printercu** [rails/sprockets#432]
Every call to `register_engine` allocates huge memory amount. I've got sample:

```ruby
require 'sprockets'

puts Sprockets::VERSION

env = Sprockets::Environment.new
env.append_path './'

7.times do |i|
  if env.respond_to?(:register_engine)
    env.register_engine ".a#{i}", Proc.new {}, silence_deprecation: true
  else
    # for 4.0
    env.register_mime_type "text/a#{i}", extensions: [".a#{i}"]#, charset: :html
    env.register_preprocessor "text/a#{i}", Proc.new {}
  end
  env['smth'].to_s
  GC.start
  stat = GC.stat
  puts "#{i}. Heap slots: #{stat[:heap_live_slots]}/#{stat[:heap_available_slots]}"
end

# my output
3.7.0
0. Heap slots: 255590/309369
1. Heap slots: 346578/627704
2. Heap slots: 462202/1001063
3. Heap slots: 605377/1001063
4. Heap slots: 779058/1352823
5. Heap slots: 986193/1799959
6. Heap slots: 1229737/2054710
```

It shows that every registered engine adds at least 10k live heap slots, and this amount increasing.
There is branch for sprockets 4, it works fine and significantly faster.

Ruby version 2.3.

For comparison, preloaded rails app takes about 65k slots.

I'm not using sprockets directly, just noticed that memory usage increased after updating to the latest `slim-rails`. Update adds a call to `register_engine`. I see that there is no such method in sprockets 4. So should this call be avoided, if `register_preprocessor` is available, and everything would work the same way?

**Comment by schneems** [comment]
Here's our docs on supporting multiple versions of sprockets https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors

I would recommend using `memory_profiler` gem to see what is allocating so much stuff. Maybe we could clean it up.

**Comment by printercu** [comment]
Ah yes, here is just the same thing which appeared in new version of slim-rails: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#registering-all-versions-of-sprockets-in-processors

Can you please tell, why do we need `register_engine` for sprockets3 if it's already deprecated? Can be this avoided, and only `register_preprocessor ` left?

**Comment by printercu** [comment]
/ping @josh 

Memory_profiler and git bisect bring me to this commit: 608532c906abaa07b48b97d5c3097f78fec87882

Most of allocations come from https://github.com/rails/sprockets/blob/v3.7.0/lib/sprockets/mime.rb#L119-L121. For it's hard to say what this code really do, and how it can be fixed. I've checked, that before this commit it still increases memory, but much more slower:

```
3.0.0.rc.1
0. Heap slots: 90071/152032
1. Heap slots: 98198/161815
2. Heap slots: 107322/181786
3. Heap slots: 117406/212764
4. Heap slots: 128450/242111
5. Heap slots: 140454/274312
6. Heap slots: 153419/307736
```

Here is updated test script, which can be put into sprockets root:

```ruby
$LOAD_PATH.unshift "#{__dir__}/lib"

require 'sprockets'
require 'memory_profiler'

puts Sprockets::VERSION

env = Sprockets::Environment.new
env.append_path './'

7.times do |i|
  MemoryProfiler.report {
    env.register_engine ".a#{i}", Proc.new {}, silence_deprecation: true
    env['smth'].to_s
  }.pretty_print
  GC.start
  stat = GC.stat
  puts "#{i}. Heap slots: #{stat[:heap_live_slots]}/#{stat[:heap_available_slots]}"
end
```

Hope it helps.

**Comment by januszm** [comment]
@schneems docs say to use `if ...preprocessor... end` + `if ...transformer... end` flow which suggests both are enabled, shouldn't we stick to just one, either the 'transformer' or 'engine' branch?

**Comment by printercu** [comment]
@schneems why is it closed? Is it fixed in v4?

**Comment by schneems** [comment]
Register engine is deprecated and removed in v4
