### ISSUE TITLE
ES2015 supported?

### ISSUE THREAD

**Issue by RichardJECooke** [rails/sprockets#437]
### Expected behavior

Contemporary Javscript like this should compile fine `App.View.DashboardOverview = class DashboardOverview extends App.View.Base {`

### Actual behavior

`Unexpected token: name (DashboardOverview) (line: 54518, col: 36, pos: 2516027)`

### System configuration

- Sprockets version `3.7.0`
- Ruby version `2.3.0`

### Example App

Our .js code works fine locally in all browsers with basic ES6 syntax, like backtick and `class`, but our live precompile fails.  **Does sprockets support modern Javascript?**

**Comment by RichardJECooke** [comment]
I think it might be Uglifier that doesn't support ES2015: https://github.com/lautis/uglifier

**Comment by guilleiguaran** [comment]
ES6 is partially supported by Sprockets because Babel transpiles ES6 modules to CommonJS modules but Sprockets doesn't include an CommonJS environment for those modules.

To use ES6 you must add the `babel-transpiler` gem to your Gemfile and change the extension of the files from .js to .es6.

**Comment by RichardJECooke** [comment]
Thanks. I don't want to transpile though, all our browsers support current Javascript.  When I tried adding the `babel-transpiler` gem and renaming `.es6` our now app builds correctly, but the output has bad syntax.

Is it possible to just leave our Javascript as is when bundling? Cos the browsers are all fine with it.

**Comment by guilleiguaran** [comment]
Oh, in that case I think you might right about Uglifier.

You can try with Closure compiler instead of Uglifier to check if you have better luck with ES6 code: https://github.com/documentcloud/closure-compiler

**Comment by RichardJECooke** [comment]
Even when I remove Uglifier from the build process I still get parsing errors on deploy.  I'll switch back to Coffee from ES6 for now, and move our project from Sprockets to Webpack/Browserify later. Thanks for your help today.
