### ISSUE TITLE
Source map files are generating "sources" without digests while actual source files on disk include digest

### ISSUE THREAD

**Issue by mikeycgto** [rails/sprockets#449]
### Expected behavior

We are explicitly linking against some select source maps files for our error reporter ([see #410](https://github.com/rails/sprockets/issues/410#issuecomment-270450004) for more discussion). For example:

```javascript
//= link admin.js.map
//= link editor.js.map
//= link onboarding.js.map
```

The `"sources"` array in the map JSON files should contain .source.js files with digests and match what is written to the disk. For example:

```json
"sources":["style.source-edd27de24d7c3c8f4270b7beef0a0c53b0dd9f527e44871bbb886a41ff83d5f7.js","polyfills/arrayFrom.source-ae04f9e7c520908dd50a1ef8097b9f52e044cf6786c910b322aa5ffab67d727f.js"]
```

```
> ls public/assets/style.source-*
Jan  5 14:45 public/assets/style.source-edd27de24d7c3c8f4270b7beef0a0c53b0dd9f527e44871bbb886a41ff83d5f7.js

> ls public/assets/polyfills/arrayFrom.source-*
2739 Jan  5 14:45 arrayFrom.source-ae04f9e7c520908dd50a1ef8097b9f52e044cf6786c910b322aa5ffab67d727f.js
```

### Actual behavior

The `"sources"` array in the map JSON files does not contain .source.js files with digests. For example:

```json
"sources":["style.source.js","polyfills/arrayFrom.source-.js"]
```

The actual files written to disk _do_ include the digest.

### System configuration

We're using Ruby 2.3.3 with the current master of Sprockets.

The environment itself is setup with `:uglify` as the `js_compressor` and with `digests` set to `true`.

### Example app

I setup a small Rails application [here](https://github.com/SimplyBuilt/sprockets-source-maps-digest) to demonstrate the problem. Run `rake assets:precompile` to generate the assets as normal.

Notice that the generated map file _does not_ list "sources" files with digests.

Please note: while the JS files are slightly different than described above, it should be enough to show the problem.

**Comment by mikeycgto** [comment]
As a small aside, perhaps the `asset_host` from the Rails asset settings can be used as the `sourceRoot` field in the source map file. The `sourceRoot` field is defined [here](https://github.com/mozilla/source-map/#consuming-a-source-map).

**Comment by plrthink** [comment]
I'm also facing this problem, @mikeycgto have you got some workaround?

**Comment by schneems** [comment]
For me I get the files without assets generated on disk as well as the source map points to the asset with no digest

![image](https://user-images.githubusercontent.com/59744/32958742-042efdb8-cb85-11e7-9ee7-4073d6c8469b.png)

That linked example app is a broken link.

All source map debugging and operations working for me. Please try beta6. I don't think it's supposed to list files with digests. Your source files shouldn't be getting compiled.
