### ISSUE TITLE
Setting up regex for manifest.js files

### ISSUE THREAD

**Issue by akholodenko** [rails/sprockets#453]
### Expected behavior

I'm currently using Rails 4.2 and Sprockets 3.7.0. My assets.rb file has the following regex that precompiles page-specific manifests for JS and CSS files. The regex excludes any asset files that start with _ (underscore) or are in the _components directory.

Rails.application.config.assets.precompile << /^(?!_components)(?:.+\/)?(?!_)([^\/]*)\.s?css$/
Rails.application.config.assets.precompile << /^(?!_components)(?:.+\/)?(?!_)([^\/]*)\.js$/

The advantage is on every page I have a dedicated JS/CSS file with code only needed for that page. For example for the homepage there's a homepage.js and homepage.css; for contact page there's a contact.js and contact.css. The respective files list their dependencies using sprocket's require statements (for JS) and @import (for CSS).

How is it possible to reproduce this set up with Sprockets 4 and manifest.js?

(Not sure if this is the best place to post, please point to the right forum if not).

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

- Sprockets version: 3.7.0
- Ruby version: 2.3.3
- Rails version: 4.2.6 

### Example App

Please provide an example app that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

To create an example app, make an application locally that uses your same version of Sprockets. Add files to reproduce the problem. Once you've reproduced the problem add instructions on how to run your example app to a README.md file. Then commit everything to git and push to a new project on github. Once you've pushed your app add a link back to this issue.

**Comment by rafaelfranca** [comment]
To make this work you will need to iterate through all the assets, filter than and in a loop call the `link` directive. You manifest file also needs to be an erb file.
