### ISSUE TITLE
backport assets version fix

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/sprockets#457]
Curious if v4.0.0 is on the near-term horizon or not.  If not... https://github.com/rails/sprockets/commit/64fadf90882761ed5baac3546c4435c600c50ae5 was fixed some time ago and wasn't backported.  Any chance we could include that in 3.7.next?

I've cherry picked that into the 3.7.x line and deployed it -- https://github.com/josh-m-sharpe/sprockets/tree/version_that_bumps_assets -- It seems to work and do what it's supposed to.

I'm also happy to put together a PR for it if that helps.

Thanks!

**Comment by jacobbednarz** [comment]
#478 addresses this if there is interest

**Comment by schneems** [comment]
4.0.0 is close
