### ISSUE TITLE
Sprockets Cookbook

### ISSUE THREAD

**Issue by josh** [rails/sprockets#46]
Had an idea for documentation. We should have some sort of section of common sprockets use cases.

Heres some ideas

* Loading bower packages
* Organizing multiple bundles to optimize bundle sizes and delivery
* Adding js/css linters
* Working with JS module loaders (require.js, browserify)
* Writing an image format conversation tool
* Web Worker best practices
* (your idea here)

What do you guys think? I wonder if this should be something under a docs/ directory here or just under the Wiki for anyone to add ideas?

/cc @rafaelfranca @arthurnn

**Comment by arthurnn** [comment]
+1 to add possible use cases of Sprockets .
I think WIKI is a good place.
