### ISSUE TITLE
extending_sprockets.md update about supporting all versions?

### ISSUE THREAD

**Issue by januszm** [rails/sprockets#462]
Shouldn't we change the instructions how to support multiple versions in extensions, so instead of two `if` we should have `if ... elsif ... end` ? I've noticed with sprockets4 beta `env` responds to both `register_transformer` AND `register_engine` methods

```ruby
if env.respond_to?(:register_transformer)
  env.register_mime_type 'text/css', extensions: ['.css'], charset: :css
  env.register_preprocessor 'text/css', MySprocketsExtension
end

if env.respond_to?(:register_engine)
  args = ['.css', MySprocketsExtension]
  args << { mime_type: 'text/css', silence_deprecation: true } if Sprockets::VERSION.start_with?("3")
  env.register_engine(*args)
end
```
=>
```ruby
  env.register_preprocessor 'text/css', MySprocketsExtension
elsif env.respond_to?(:register_engine)
  args = ['.css', MySprocketsExtension]
...
```

also `charset` seems odd, ... `:css` ?

**Comment by schneems** [comment]
I have no idea honestly. It's all pretty murky in my head. I remember there being an edge case where transformer existed, but didn't do the right thing, but I honestly don't know right now. Maybe it was a mistake on my part. Here's the PR where I wrote the docs https://github.com/sass/sassc-rails/pull/65/files.

Does having those both there harm things? If so, can you send me a doc PR?

**Comment by januszm** [comment]
No worries @schneems, we already resolved the related issue in https://github.com/slim-template/slim-rails by changing that double `if` to `if ... elseif`. Here's the PR https://github.com/rails/sprockets/pull/527

The PR linked by you is not about docs, btw.
