### ISSUE TITLE
tmp asset caches not reused

### ISSUE THREAD

**Issue by stefanmb** [rails/sprockets#464]
### Expected behavior

Caches should be re-used between builds.

### Actual behavior

Caches are not reused, and new ones are generated with new names.

### System configuration

- Sprockets version: `3.7.1`
- Ruby version: `2.3.1`

### Details

I'm trying to speed up some custom build scripts relying on https://github.com/heroku/heroku-buildpack-ruby.

Previously sprockets used the full asset path to generate a digest, but this behaviour was [patched to rely on the relative path](https://engineering.heroku.com/blogs/2016-02-18-speeding-up-sprockets/).

> ...  Heroku stores the cache between deploys ...

@schneems How does Heroku cache between deploys? 

I see in the [Sprockets source](https://github.com/rails/sprockets/blob/6eac004a1567f70270606170f8a4d51d4e2fb3e8/lib/sprockets/base.rb#L51-L63) that `mtime` is part of the digest. 

In my build system the cache folder is compressed and uploaded to cloud storage, every time it's decompressed new timestamps are created (`tar` does not preserve the old ones) so `sprockets` regenerates all the assets causing a huge buildup in cache size and preventing reuse.

The only way I could see to make this work is to always keep the files on disk with their old timestamps. Any advice on how to alleviate this issue is appreciated!

**Comment by wjordan** [comment]
I couldn't reproduce the issue as described in a minimal test (`rails new`, `rake assets:precompile`, `touch` all files and caches, `rake assets:precompile` again, observe nothing is regenerated).

> I see in the Sprockets source that mtime is part of the digest.

I don't think this is entirely accurate - "Digests are cached by the path's current mtime" (according to the [source comment](https://github.com/rails/sprockets/blob/6eac004a1567f70270606170f8a4d51d4e2fb3e8/lib/sprockets/base.rb#L53)), so `mtime` is only part of the asset-digest's _cache key_, not part of the asset-digest itself.

This means that when the `mtime` on a file is changed, all that happens is that the asset has its file contents recomputed by the digest class. The digest will stay the same if the contents aren't modified.

**Comment by schneems** [comment]
> @schneems How does Heroku cache between deploys?

We put whatever is in your `tmp/cache/assets` folder into a cache, and make it available on next build. When you move a file on disk it's mtime doesn't change.

```
$ touch foo.txt
$ ruby -e "puts File.stat('foo.txt').mtime"
2017-11-17 11:06:36 -0600
$ mkdir tmp
$ mv foo.txt tmp/foo.txt
$ ruby -e "puts File.stat('tmp/foo.txt').mtime"
2017-11-17 11:06:36 -0600
```

Note, the file moved, but the mtime did not change.
