### ISSUE TITLE
README references `eco` and `ejs` libraries; both appear unmaintained

### ISSUE THREAD

**Issue by nzifnab** [rails/sprockets#465]
The README on master (here: https://github.com/rails/sprockets#javascript-templating-with-ejs-and-eco) references EJS and Eco as JS templating libraries to use with the Rails asset pipeline (and the `.jst` extension).

But looking at both of those repos; they don't appear to be very active. `Eco` hasn't had an update since 2012 (And according to one of the issues there, has a potential XSS vulnerability in that variables don't escape single quotes, only double quotes).

EJS also hasn't been updated since 2012.

I guess I'm wondering if either the README should be updated to reflect more up-to-date templating libraries, or if there's newer better ways than using the `JST` object to handle JS templates.

### Expected behavior

README should link to maintained libraries for JS templating

### Actual behavior

README links to two libraries whose last commits are from 2012 for JST templates.

### System configuration

- Master README file

### Example App

N/A

**Comment by kaspth** [comment]
Perhaps the Basecamp folks are still using it? cc @dhh

**Comment by dhh** [comment]
Basecamp 3 uses eco, yes. Works great for us 👍

**Comment by kaspth** [comment]
Great, looks like it's just one of those libs that don't need much updating.

Let's keep the readme reference then. Thanks!

**Comment by aar0nr** [comment]
Looks the repos have been archived, and are now read-only/unmaintained.

**Comment by schneems** [comment]
Did you find a bug with one of them?

**Comment by aar0nr** [comment]
@schneems No, I was just checking around to see if I would use them or not. I used the ejs gem in the past, but will most likely go with a webpack solution instead.
