### ISSUE TITLE
Move CHANGELOG to GH releases

### ISSUE THREAD

**Issue by josh** [rails/sprockets#47]
@rafaelfranca saw you do this on another rails project. Do you think it worked out well? Would you suggest we do the same for sprockets itself? Any tips for migrating?

**Comment by vincentwoo** [comment]
Why not both? I think they're both quite useful.

**Comment by themilkman** [comment]
I agree with @vincentwoo, a pure changelog file in the repository is very useful and a good convention.

**Comment by elia** [comment]
I like to have the file too, I find it particularly useful in the released gems

**Comment by rafaelfranca** [comment]
For small projects like sass-rails, sprockets-rails and rails-dom-testing it is working very well. The main reason is, the releases tends to be small, just one or two changes. I was thinking in doing the same thing with sprockets.

@vincentwoo @themilkman @elia could you elaborate what the file in the repository can give us more than just using github releases page? I think we can maintain both, but I'd like it to be justified.

**Comment by rafaelfranca** [comment]
Explaining a little bit why I like to use GitHub releases:

The problem with maintaining the file on the repository is handling releases in different branches. People usually only look the CHANGELOG on the master branch and sometimes we do release on different branches, requiring us to do a new commit to master just to sync the CHANGELOG between these branches. With GitHub releases we don't have this problem since all the releases are in the same page.

**Comment by rafaelfranca** [comment]
Here an example of CHANGELOG sync https://github.com/rails/sprockets-rails/pull/245

**Comment by themilkman** [comment]
@rafaelfranca Thanks for your reply. For me, a changelog is a an important source for upgrade-information and general news on the project. I really like to read them and think they're important. The Github-Changelog separates the information from the git repository - which should imho include all important information. Also the official Github Android App (as well as the mobile version of GH) doesn't allow to browse the GHC.

**Comment by rafaelfranca** [comment]
Yeah, agree about the importance of a CHANGELOG, I'm not trying to kill it, just move to some place that would be useful for the users and also easier to maintain. In my opinion GitHub releases have a good balance between both objetives. The important information is centralised in one place, not across different branches having the risk of being outdated or incorrect.

Having both is fine to me, but I'd love to the file on the repository using GitHub releases as the source of information.

**Comment by elia** [comment]
A CHANGELOG generator triggered by releases (as in bundler's `rake release`) seems like the best of both worlds

**Comment by josh** [comment]
I don't really want to be bothered with maintaining both. I'll just wontfix this for now.
