### ISSUE TITLE
The Rack server should follow the HTTP specifications for If-Match and If-None-Match headers.

### ISSUE THREAD

**Issue by travishaynes** [rails/sprockets#472]
### Expected behavior

The [Rack server](https://github.com/rails/sprockets/blob/v4.0.0.beta4/lib/sprockets/server.rb) should follow the HTTP/1.1 specifications for the [If-Match](https://tools.ietf.org/html/rfc2616#section-14.24) and [If-None-Match](https://tools.ietf.org/html/rfc2616#section-14.26) headers since it supports them. Specifially, they should be able to specify multiple values, and include an `*` wildcard.

### Actual behavior

The [code](https://github.com/rails/sprockets/blob/v4.0.0.beta4/lib/sprockets/server.rb#L53) uses a regular expression that extracts the text from a double quoted string, and returns `nil` for anything else. This means arrays, weak matches, and wildcards will all be ignored. So, for example, if the header `If-Match: *` is present, it will erroneously respond with HTTP 412 Precondition Failed since all it does [is check](https://github.com/rails/sprockets/blob/v4.0.0.beta4/lib/sprockets/server.rb#L67) if the content of the `If-Match` is equal to the asset's ETag.

### System configuration

- Sprockets version 4.0.0.beta4
- I was using Ruby 2.4.0.

### Example App

No example app is necessary for this. We just need to make the Rack server follow the HTTP specs.

**Comment by schneems** [comment]
Send me a PR for this?

**Comment by travishaynes** [comment]
Working on it.

**Comment by travishaynes** [comment]
After some more research into this, it looks like Rack already supports caching out of the box: https://github.com/rack/rack/blob/master/lib/rack/conditional_get.rb

Perhaps we should remove caching from `Sprockets::Server` altogether, and leave it up to the developer whether or not they want to enable it by adding the `Rack::ConditionalGet` middleware themselves? Then all we have to do in `Sprockets::Server` is find the asset, serve it, and include the ETag and Last-Modified headers. Rack can do the rest.

**Comment by schneems** [comment]
I don't put a ton of work into the server, you shouldn't be using it in production. You should precompile and then use a static asset server like ActionDispatch::Static (if using rails)

**Comment by schneems** [comment]
Still happy to take a PR if you're interested.
