### ISSUE TITLE
Encoding::ConverterNotFoundError

### ISSUE THREAD

**Issue by umdstu** [rails/sprockets#473]
### Expected behavior

When deploying an application via capistrano, sprockets should concat all javascript sources without error

### Actual behavior

sprockets throws an error when compiling assets:
```
Encoding::ConverterNotFoundError: code converter not found (UTF-8 to UTF-32LE)
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/utils.rb:106:in `encode'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/utils.rb:106:in concat_javascript_sources'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:59:in `call'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:59:in `block (2 levels) in process_bundle_reducers'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:55:in `each'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:55:in `block in process_bundle_reducers'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:54:in `each'
/app/shared/bundle/ruby/2.2.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:54:in `reduce'
```

### System configuration

- sprockets-3.7.0
- ruby-2.2.4p230

This same sources code/application compiles without error on a different server with (with same version of sprockets and ruby).

**Comment by schneems** [comment]
Fix your encodings on your files.

This exception is coming from the `<<` operation on string which is coming from Ruby, not from Sprockets. https://github.com/rails/sprockets/blob/3.x/lib/sprockets/utils.rb#L106

It's because it doesn't know how to turn UTF-8 into UTF-32LE

**Comment by umdstu** [comment]
Hi @schneems. 

I modified the utils.rb file and printed out the source prior to the encoding. the source last printed before the error is thrown is the distribution file from [this](https://www.npmjs.com/package/angular-ui-bootstrap). I was on version 2.2, so i updated to the latest, 2.5 and it still had the issue.

That said, sprockets-3.7.0 and ruby.2.2.4p230 have no problem with this same file on another server; it's compiled just fine.
