### ISSUE TITLE
TypeError in Sprockets::Manifest#find_sources

### ISSUE THREAD

**Issue by atyndall** [rails/sprockets#476]
### Expected behavior

When `Sprockets::Manifest#find_sources(asset_name).first` is called with a non-existent asset in a precompiled environment, it should return nil or a reasonable exception.

### Actual behavior

A `TypeError` is thrown due to an unchecked path join;

```
2.3.1 :012 > Rails.application.assets_manifest.find_sources('foo.css').first
TypeError: no implicit conversion of nil into String
  from bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:164:in `join'
  from bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:164:in `block in find_sources'
  from bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:163:in `each'
  from bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:163:in `find_sources'
  from (irb):12:in `each'
  from (irb):12:in `first'
  from (irb):12
  from bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
  from bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
  from bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
  from bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

### System configuration

- Sprockets 3.7.0
- Ruby 2.3.1

While these aren't the most recent version, I had a look at sprockets 3.7.1 and master, and the bug appears to still be present in those versions. It can be traced to [this line](https://github.com/rails/sprockets/blob/3c542c1b5df82ad1a3a04b818e2ec91b560c9d11/lib/sprockets/manifest.rb#L144).

As for if it should return nil or an exception, I'm not sure, either could be seen as reasonable.

**Comment by schneems** [comment]
This would be a good PR.

**Comment by bbonislawski** [comment]
@schneems Issue is already fixed on master. Backport to 3.x?

**Comment by rafaelfranca** [comment]
It is also fixed on 3.x https://github.com/rails/sprockets/commit/eb0af6d5eb7c0ac049e6c89bd6ee991586f4d256

**Comment by dfyx** [comment]
@rafaelfranca Sadly that fix in 3.x has never been released. Would it be possible to release a 3.7.2?
