### ISSUE TITLE
Issue upgrading to 3.x

### ISSUE THREAD

**Issue by JulienItard** [rails/sprockets#477]
Hello, i try to update to 3.x but something wrong with my code. I have my own environment class like
`class Theme::Environment < Sprockets::Environment`

But apparently `@engines` has been removed from `Sprockets::Environment`. How can i access it and methods like `@engines.delete()` now ?

I checked ChangeLog but can't see something about it.

Thanks a lot.

**Comment by rafaelfranca** [comment]
https://github.com/rails/sprockets/blob/3.x/lib/sprockets/engines.rb
