### ISSUE TITLE
Sprockets cannot find ember/loader

### ISSUE THREAD

**Issue by nachootal** [rails/sprockets#480]
### Expected behavior

Precompilation of assets should finish successfully.

### Actual behavior

When precompiling the assets with sprockets v3.7.1 in a rails v4.2.8 with ember-rails v0.21.0  I get into this situation in which sprockets cannot find "ember/loader". See [log](https://hastebin.com/epajuyabud.hs).

While debugging sprockets to get to the cause I've found what I think is the case:

- As the type of application.module.es6 is ecmascript module, this is set by sprockets as the acceptance for the required files. In this case loader.js, resolver.js and load-initializers.js from ember-cli-assets gem and shims.js from ember-rails gem. Of course, these files, as might be seen by its extension, are not ecmascript6 module detected but regular javascript files.

I changed the extension on all these files to file_name.module.es6 and tried precompiling again and it seems it finishes without precompiling but don't find this is a good fix.

Is this a well known issue and is there a proper fix of configuration for this?.

### System configuration

- sprockets v3.7.1
- rails v4.2.8
- ember-rails v0.21.0
- Ruby 2.3.1p112

### Example App

Please find the example app [here](https://github.com/nachootal/failing_sprockets_ember_assets)

**Comment by tricknotes** [comment]
I thinks this is a bug caused by [ember-emblem-template](https://github.com/botandrose/ember-emblem-template) or [ember-es6-template](https://github.com/tricknotes/ember-es6_template), not by sprockets.

See for detail: https://github.com/emberjs/ember-rails/issues/546

**Comment by robin850** [comment]
Hello,

Thank you very much for commenting there @tricknotes and for reporting @nachootal. I will give this a close but feel free to comment if it turns out to be a Sprockets problem !
