### ISSUE TITLE
Compiler is still being called when assets are skipped/unchanged

### ISSUE THREAD

**Issue by dmnelson** [rails/sprockets#493]
So first, I'm not really sure this is a issue or a design decision, apologies for that.

I'm working on an application that has thousands (literally) of assets, and I noticed that `rake assets:precompile` task still takes a lot of time when nothing has changed (about 10 minutes), enabling logging would output every single asset as being skipped.

Then I saw that `Sprockets::Manifest#find` compiling the assets before checking whether they should or not be skipped. (My understanding is that it will use the compiled version to generate the digest?). I'm pasting the backtrace below.

Is that the desired behavior? If so, is there a recommendation to optimize that (besides reducing the volume of assets)?

```
.../vendor/bundle/ruby/2.3.0/gems/uglifier-3.0.4/lib/uglifier.rb:140:in `compile'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:55:in `block in call'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:54:in `call'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
.../vendor/bundle/ruby/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
```

**Comment by matthewd** [comment]
> Is that the desired behavior?

It doesn't sound like it! It's probably worth checking sprockets master (4.x-to-be) first to ensure it has the same behaviour.. then I guess the next step would be to see if you can work out why it's happening: naïvely speaking, I'd expect the [extensive!] cache to cover this.

**Comment by schneems** [comment]
When you say "checking whether they should be skipped or not" do you mean if they're in the precompile list?

I recommend maybe using Sprockets 4 as MD suggested. Instead of a precompile list you use a manifest file that lets you be much more specific.

**Comment by dmnelson** [comment]
Thank you both for the responses!

@schneems I was talking about of when it checks if they already exist or not (https://github.com/rails/sprockets/blob/v3.7.1/lib/sprockets/manifest.rb#L205) to write the file, at that point the file is already compiled regardless if the existing version is up to date or not.

I'll try 4.x and let you know how it goes.

**Comment by schneems** [comment]
Sprocket is...complicated.

Sprockets uses the cache of the item and it's current mtime on disk to see if an asset has changed. If it hasn't changed then it should be pulling the whole asset from cache (in `tmp/cache`). So it's not actually re-compile the asset there, it's using the cached version. Only if something changes (mtime of the file, or one of the files that it depends on changes). 

Try this out https://github.com/codetriage/codetriage/blob/8c616ae2a427f87decd705d3145b8a9c40453d88/Rakefile#L9-L15 to get a profile of what's taking so long.

You can view the output afterwards by running

```
$ stackprof tmp/stackprof.dump
``
