### ISSUE TITLE
Post processor wont run

### ISSUE THREAD

**Issue by thebravoman** [rails/sprockets#495]
### Expected behavior
After registering a postprocessor as:
Sprockets.register_postprocessor 'application/javascript', MyJsProcessor
the sefl.call method is never called on 
RAILS_ENV=production rake assets:precompile

Tell us what should happen

The method call of MyJsProcessor should have been called.
### Actual behavior
The method call is never called

Tell us what happens instead

### System configuration

- Sprockets version
- Ruby version 4.2.8

### Example App

Please provide an example app that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

To create an example app, make an application locally that uses your same version of Sprockets. Add files to reproduce the problem. Once you've reproduced the problem add instructions on how to run your example app to a README.md file. Then commit everything to git and push to a new project on github. Once you've pushed your app add a link back to this issue.

**Comment by schneems** [comment]
See the docs here https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md
