### ISSUE TITLE
Can not require exporter

### ISSUE THREAD

**Issue by thebravoman** [rails/sprockets#496]
### Expected behavior
Writing an exporter and doing 
require 'sprockets/exporters/base' 

in my file. Expected to have the file required
### Actual behavior

cannot load such file -- sprockets/exporters/base

### System configuration

- Sprockets version - sprockets (3.7.1)
- Ruby version - 2.2.2

**Comment by thebravoman** [comment]
Even when requiring it in the console the result is:
```

2.2.2 :004 > require 'sprockets/exporters/base'
LoadError: cannot load such file -- sprockets/exporters/base
```

In the gem file I have
 
`gem "sprockets"`

**Comment by thebravoman** [comment]
Found it. It is from the version. There are no exporters in the 3.x version and I am with it.

**Comment by Utopism** [comment]
Hi, exporters where brought by v4.0.0.beta4.
Does this meams this issue can be closed ?

**Comment by thebravoman** [comment]
@Utopism yes, I think it can.

**Comment by Utopism** [comment]
Thanks !
