### ISSUE TITLE
Asset compilation fails on FIPS enabled servers

### ISSUE THREAD

**Issue by patrickwilkes** [rails/sprockets#499]
### Expected behavior

Asset compilation can be performed when FIPS is enabled (FIPS is a security standard that prohibits the use of insecure cryptographic algorithms, specifically MD5).

### Actual behavior

Any code that includes `require 'digest/md5'` will be terminated by OpenSSL on a FIPS enabled system, even if MD5 is not actually used.

Although Sprockets has defaulted to SHA256 since version 3.0.0, and configuring the digest_class was deprecated, `lib/sprockets/digest_utils.rb` still requires digest/md5 at the latest version.

Bundler now checks whether MD5 is available before requiring digest/md5, like this:
```ruby
def md5_available?
  return @md5_available if defined?(@md5_available)
  @md5_available = begin
    require "openssl"
    OpenSSL::Digest::MD5.digest("")
    true
  rescue LoadError
    true
  rescue OpenSSL::Digest::DigestError
    false
  end
end
```

Would it be possible to a include a check like this in Sprockets before requiring MD5, or does MD5 need to be available for some reason?

**Comment by schneems** [comment]
Not that I know of. Can you give me a PR?

**Comment by dhh** [comment]
Closed by https://github.com/rails/sprockets/pull/725
