### ISSUE TITLE
DEPRECATION WARNING

### ISSUE THREAD

**Issue by slim1979** [rails/sprockets#501]
Hi there.
Recently I started to get such warnings in terminal:

DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors

i went by link, but didnt understant, where i need to register the code suggested on the website
help, please)

**Comment by schneems** [comment]
Can you give me the backtrace that came with the deprecation? Is it pointing at a gem? Are you a gem author? Likely you need to update your gem version or open an issue with the gem to let them know.
