### ISSUE TITLE
bundle/root pipeline to bootstrap module systems

### ISSUE THREAD

**Issue by elia** [rails/sprockets#52]
Hi @josh,

in my endless quest with sprockets and opal I was going through the sprockets source and I think there's a chance to make module systems happy, or at least opal's require system happy.

The problem is bootstrapping the root file, which is the one that is usually linked with `javascript_include_tag`. The obvious solution would be to inject the [bootstrapping code](https://github.com/opal/opal/blob/ec61e26d47dbbd15183d45caa9034f40de5d6327/lib/opal/sprockets/processor.rb#L133-L163) in a bundle processor as it's called (if I understood correctly) on the root file with all the required assets available.

The problem is it's not called if the debug bit is on (aka the `self` processor).

So, if my assumptions are correct it should be possible to change the `javascript_include_tag` helper to pass through the self pipeline all assets but the root, and add an ad-hoc "self_root" pipeline for it.

The current opal-rails implementation overloads `javascript_include_tag` injecting the bootstrapping code in a `<script>` tag if debug is on. [Here's an example](https://gist.github.com/elia/4f9c906b266890ebdcab#file-gistfile1-html-L91-L122)

What I envision is to have the last of the `?body=1` files be called as something like `?body=1&bundle=1`.

From:

```html
…
<script src="/assets/scroll_up_link-05ca5d05788cc62265bbc4508d80d33f.js?body=1"></script>
<script src="/assets/models/cart-219dd7a6950beb74573b3a106e74970b.js?body=1"></script>
<script src="/assets/inner-d59fa604d4efa67f6b3b204d4529f323.js?body=1"></script>
<script src="/assets/application-6237095f72d7abc6b6df9e5d5284aece.js?body=1"></script>
<script>Opal.load("application")</script>
```

To:

```html
…
<script src="/assets/scroll_up_link-05ca5d05788cc62265bbc4508d80d33f.js?body=1"></script>
<script src="/assets/models/cart-219dd7a6950beb74573b3a106e74970b.js?body=1"></script>
<script src="/assets/inner-d59fa604d4efa67f6b3b204d4529f323.js?body=1"></script>
<script src="/assets/application-6237095f72d7abc6b6df9e5d5284aece.js?body=1&bundle=1"></script>
```

**Comment by josh** [comment]
I'd probably say this shouldn't be a magic step. How does the use control this if theres multiple bundles? Is there any reason the user can't invoke `Opal.load("app")` from "application.js" itself?

``` js
// define application bundle
//= require_tree ./lib
Opal.load("application")
```

**Comment by elia** [comment]
Most apps use application.js.rb which can't escape its closure 

Also people expect it to work out of the box
