### ISSUE TITLE
Sprockets does not work well in multi-process environments like Solano CI

### ISSUE THREAD

**Issue by ipitythefoo** [rails/sprockets#53]
According to Solano CI, a continuous integration test service:

> Many Rails applications use hardcoded paths by default, often relative to “/tmp” or Rails.root. Test threads in Solano CI may not have access to /tmp, and two processes writing to the same file will probably run into trouble.

We have found this to be the case, as our team would sporadically get "ActionView::Template::Error: end of file" errors on Solano CI.  The root cause of these errors is that Sprockets chooses a location for its FileStore cache that is not multi-process friendly.

We have locally patched version 2.12.3 like so and it has fixed these intermittent errors:

    module Sprockets
      module Cache
        class FileStore
          def initialize(root)
            fore, aft = root.split('tmp')
            multiprocess_safe_location = File.join(Dir.tmpdir, aft)
            @root = Pathname.new(multiprocess_safe_location)
          end
        end
      end
    end

I'd suggest tweaking Sprockets' behavior so it works well in multiprocess environments.

**Comment by rafaelfranca** [comment]
Please try the sprockets 3 version. Sprockets 2 is not supported anymore.
