### ISSUE TITLE
Improve performance on server with multiple cores or multiple cpus

### ISSUE THREAD

**Issue by bastengao** [rails/sprockets#54]
My rails project has a bit lot of asset files. It almost takes 7 minutes to compile assets. I use `htop` to see how  usage of computer assets compiling process use, it consumes only one cpu 100%, but other cpus almost are empty.

**Comment by envygeeks** [comment]
You think that's bad, this situation is exacerbated by @discourse which can't really do anything about it other than rewrite the Rails asset pipeline, but it takes a good 20 minutes to generate assets on our 4 core Xeon server.

**Comment by schneems** [comment]
We need to parallelize here, that's a long way off until Sprockets 4 can stabilize. Going to close this for now.
