### ISSUE TITLE
Source maps break when empty js file exists

### ISSUE THREAD

**Issue by C-Higgins** [rails/sprockets#540]
If a js/es6 file is in assets which is empty or contains only comments, the source maps of that file and all files following it in the mapping process will break. 

Example: https://pastebin.com/LuM6V3xQ
In this example, you can see that beginning with activities.source.es6 (the first blank file), the line mappings are wrong. The lines begin counting from 0 again after that and after every subsequent empty file, leading to overlapping and obviously incorrect mappings.

### System configuration
- Sprockets version 4.0.0.beta6
- Ruby 2.2.4p230

**Comment by C-Higgins** [comment]
Closing this because it's obviously not going to get fixed and it's cluttering my open issues

**Comment by jeltz** [comment]
If the bug is still there I think that it is better if it is open so others can find it if they run into the same issue.
