### ISSUE TITLE
Broken SRI support for sprockets-rails

### ISSUE THREAD

**Issue by Fudoshiki** [rails/sprockets#555]
### Expected behavior

```ruby
# Public: A "named information" URL for subresource integrity.
def integrity
  DigestUtils.integrity_uri(Digest::SHA256.digest(source))
end
```
Should be SHA256 hash from content string and encoded in Base64
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

### Actual behavior

Should 

https://github.com/rails/sprockets/blob/master/lib/sprockets/asset.rb#L140
```ruby
# Public: A "named information" URL for subresource integrity.
def integrity
  DigestUtils.integrity_uri(metadata[:digest])
end
```
Now `metadata[:digest]` returning not valid SHA256 hash for integrity

### System configuration

- Sprockets version: 4.0.0.beta7 master
- Ruby version 2.5

Fix for https://github.com/rails/sprockets-rails/issues/393

Actual for Sprockets 4
Sprockets 3 works

**Comment by rafaelfranca** [comment]
Closed by 5038ad5368eb8792465c2eaad453a296ce2180e0
