### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by matthooks** [rails/sprockets#56]
Hi guys. I recently updated sprockets from 2.12.3 to 3.1.0 and sprockets-rails from 2.2.4 to 2.3.1 and I'm noticing a slow growing memory leak on Heroku after the change.

![heroku metrics](https://cloud.githubusercontent.com/assets/3667/7886787/f7f20078-05f1-11e5-8a12-e76c2a4e0fc4.png)

My app is pretty large so I'm still trying to isolate the leak. Any thoughts on the best way to track this down?

**Comment by josh** [comment]
Ich.

Just curious if you have `config.assets.precompile` on or off in production? You really shouldn't need it on if everything is statically compiled.

**Comment by matthooks** [comment]
Yea, Heroku precompiles everything as part of the push to prod.

**Comment by fourseven** [comment]
What version of Ruby are you using @matthooks? I've been fighting a leak myself, but I don't think ours is related to Sprockets

**Comment by matthooks** [comment]
@fourseven 2.2.2. I'm still not 100% sure this is related to sprockets either, this stuff is so annoying to track down.

**Comment by rafaelfranca** [comment]
if precompile is off in production sprockets should not be the cause. Let us know if you could track it down to sprockets though
