### ISSUE TITLE
Why is 2.12 officially supported but 2.2 is not?

### ISSUE THREAD

**Issue by mstroming** [rails/sprockets#562]
The new path traversal security issue (http://seclists.org/oss-sec/2018/q2/210) states that 2.12 is patched, yet Rails 3 requires 2.2, and 2.2 is not patched.

It seems odd that an earlier version is supported (2.12), yet a later version (2.2) is not.

Are there plans to patch the 2.2 series?

**Comment by rafaelfranca** [comment]
https://github.com/rails/sprockets/issues/561#issuecomment-402242144

**Comment by mstroming** [comment]
I get that Rails 3 is EOL, but I'm curious why sprockets decided to patch an older version of 2 rather than a later version?

**Comment by matthewd** [comment]
12 > 2.

**Comment by mstroming** [comment]
Sorry, misread 2.12 as 2.1.2 :)
