### ISSUE TITLE
Sprockets cache digest key when git clone changes mtime

### ISSUE THREAD

**Issue by jmreid** [rails/sprockets#563]
### Expected behaviour

Because an asset's `mtime` changes when a repo is cloned, the sprockets cache digest key also changes. 

Our build pipeline does a `git clone` of a repo, which means that the sprockets cache that we persist between builds (`tmp/cache/assets/sprockets`) has new digest keys created for each new build. This causes our cache to grow on each build. Sprockets appears to still 

### Actual behaviour

Should the digest key be based on `mtime`? Feels like it might be more robust to use something like the `hexdigest_integrity_uri` instead.

I've tested my pipeline with this (https://github.com/rails/sprockets/compare/3.x...jmreid:no-mtime-for-digest-key) and found that the existing cache is used correctly and does not grow on subsequent builds.

But I'm not sure of the overall effects of a change like this. For our pipeline, we're likely going to have to look at monkey patching the `file_digest` method or clear our persistent caches on some schedule to stop them from growing too large. But I'm interested to hear the Sprocket team's thoughts on this! 

### System configuration

- Sprockets version 3.7.2
- Ruby version 2.5.1

cc @brendo

**Comment by schneems** [comment]
The mtime should not change when you clone a repo. Can you give me a small example app that reproduces the behavior?

**Comment by jmreid** [comment]
@schneems As @brendo mentioned, each `git clone` will create new `mtimes` for all cloned files:

```
⋊> ~/Desktop git clone git@github.com:jmreid/rails-mtime-git-example.git clone1                                 22:18:29
Cloning into 'clone1'...
remote: Counting objects: 88, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 88 (delta 2), reused 88 (delta 2), pack-reused 0
Receiving objects: 100% (88/88), 106.88 KiB | 397.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
⋊> ~/Desktop ruby -e "puts File.stat('/Users/justinreid/Desktop/clone1/app/assets/images/sample.jpg').mtime"    22:18:43
2018-07-29 22:18:43 -0400
```

```
⋊> ~/Desktop git clone git@github.com:jmreid/rails-mtime-git-example.git clone2                                 22:18:54
Cloning into 'clone2'...
remote: Counting objects: 88, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 88 (delta 2), reused 88 (delta 2), pack-reused 0
Receiving objects: 100% (88/88), 106.88 KiB | 897.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
⋊> ~/Desktop ruby -e "puts File.stat('/Users/justinreid/Desktop/clone2/app/assets/images/sample.jpg').mtime"    22:19:36
2018-07-29 22:19:36 -0400
```

**Comment by wvanbergen** [comment]
cc @rafaelfranca - any chance you can take a look at this?

**Comment by rafaelfranca** [comment]
There is no way to fix this issue without removing this cache, so I think to be able to change it we will have to measure the performance impact in two occasions:

1. Two subsequents builds with the second being in the same folder and with some file changes. Measure the time with and without removing the `file_digest` cache.
2. Two subsequents build with the second being in a different clone of the same repository. Measure the time with and without removing the `file_digest` cache.

With those numbers in hand I think we can make a more informed decision on if we want to keep the cache or not.

@jmreid can you work on getting those numbers?

**Comment by jmreid** [comment]
@rafaelfranca Yes, I can work on that.

**Comment by rymai** [comment]
@jmreid Any news here? We run into the same issue. Thanks!

**Comment by jmreid** [comment]
@rymai Thanks for the ping and reminder. This definitely fell off my radar.

I'll try to get this together over the next week so we can see how to move forward.

**Comment by rymai** [comment]
@jmreid FYI it seems that we should use `integrity_uri = self.integrity_uri(digest)` instead of `integrity_uri = self.hexdigest_integrity_uri(digest)`, see https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/25033/diffs.
