### ISSUE TITLE
Precompiling Assets Workflow

### ISSUE THREAD

**Issue by ScottyRJames** [rails/sprockets#575]
I would like to know a way to precompile my mustache templates as assets in production, but also be able to not mess up my development flow forcing me to restart the server/compile assets anytime I make a JS, CSS, or template change.

With the following setting: 
`config.assets.debug = true`
only about half of my templates are available at run time which leads to a lot of undefined template errors. When set to false, all my templates are available however this involves restarting my server anytime making an asset change rather than just refreshing, is there a way to have the best of both worlds?

- Ruby version ~ 2.4.1
- Rails version ~ 5.0.0

Example of this implementation: https://hackernoon.com/bundling-custom-assets-with-sprockets-c24f541f5527

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
