### ISSUE TITLE
Problem with `start_with?` on precompile Regexp

### ISSUE THREAD

**Issue by rafbgarcia** [rails/sprockets#578]
### Actual behavior

It's raising on a Bootstrap addition to `assets.precompile` config (coming from here https://github.com/twbs/bootstrap-sass/blob/51486a8bd836d32b9f413e911ed83b433ef4ad39/lib/bootstrap-sass/engine.rb#L12).

<img width="1440" alt="screen shot 2018-09-19 at 4 45 43 pm" src="https://user-images.githubusercontent.com/1904314/45780409-82ddf500-bc2b-11e8-9ef6-bdc52036551d.png">

### Expected behavior

Not to raise? I'm not sure actually.

### System configuration

```
➜  bundle exec sprockets -v
4.0.0.beta8
➜  ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
```

Is this the correct behavior for Sprockets now? I mean, should that be fixed in Bootstrap gem or here?

**Comment by rafaelfranca** [comment]
In bootstrap gem. Sprockets don't support regexp in the precompile option anymore.
