### ISSUE TITLE
Github complaining about vulnerability in v. 3.7.2

### ISSUE THREAD

**Issue by 6temes** [rails/sprockets#584]
Github is showing this message:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/5655861/46772794-c90f0b80-cd34-11e8-8565-1de450904beb.png">

<img width="809" alt="image" src="https://user-images.githubusercontent.com/5655861/46770856-07ec9380-cd2c-11e8-8bc5-aa255c5014dc.png">

**Comment by schneems** [comment]
Yes, please click the link to the CVE for more information. It is very detailed. Here's a blog post I wrote about it as well https://blog.heroku.com/rails-asset-pipeline-vulnerability.
