### ISSUE TITLE
sassc with sprockets 3.x "LoadError: cannot load such file -- sass"

### ISSUE THREAD

**Issue by krisleech** [rails/sprockets#588]
When using sassc / sassc-rails, my Gemfile.lock does not include sass and I do `rake assets:precompile` I get `LoadError: cannot load such file -- sass`. 

```
LoadError: cannot load such file -- sass
sprockets-3.7.2/lib/sprockets/autoload/sass.rb:1:in `<top (required)>'
sprockets-3.7.2/lib/sprockets/sass_processor.rb:47:in `initialize'
```

This is because sprockets 3.x "depends on" and tries to load sass. Unlike in sprockets 4.x which has support for sass and sassc gems.

I wonder if this is something you might consider accepting a fix for? 

The sassc is a a drop in replacement for sass so I was wondering if we might rescue the `LoadError` in Sprockets::AutoLoad::Sass (https://github.com/rails/sprockets/blob/3.x/lib/sprockets/autoload/sass.rb) and try to require sassc instead?

### System configuration

- spockets 3.7.2
- sprockets-rails 3.2.1
- sassc 2.0.0
- sassc-rails 2.0.0

**Comment by rafaelfranca** [comment]
sprockets 3 doesn't support sassc, so if you want to use sassc-rails you still need sass.

**Comment by ahorek** [comment]
you don't need spockets 4 to use sassc without sass. It works fine on sprockets 3 because sassc-rails overrides the original compressor, see:
https://github.com/sass/sassc-rails/blob/master/lib/sassc/rails/compressor.rb

but there's one thing. In your gemfile instead of
```
group :assets do
  gem 'sassc-rails', '~> 2.0.0'
end
```

use just
```
gem 'sassc-rails', '~> 2.0.0'
```
that should do the trick

and of course avoid any usage of "Sass" constant in your code that will trigger an autoload.

**Comment by krisleech** [comment]
Another option might be to leave sassc-rails in the assets group and `require 'sassc-rails'`.

**Comment by themilkman** [comment]
> Another option might be to leave sassc-rails in the assets group and `require 'sassc-rails'`.

I did so in an engine (engine.rb) which solved the issue for me - thanks!
