### ISSUE TITLE
Updated assets not precompiled, must blow away temp cache each deploy

### ISSUE THREAD

**Issue by senorbacon** [rails/sprockets#598]
### Expected behavior

When a javascript asset changes, it should be precompiled and a new asset with a new digest generated and served.  This javascript asset is added to config.assets.precompile, but we do not use manifest.js

### Actual behavior

Sprockets does not update the manifest file for that asset and continues serving the existing file. 

### System configuration

- Sprockets version: 3.7.2
- Ruby version: 2.3.3

### Example App

I'm sorry, I wasn't able to reproduce this issue with a toy app.

We use capistrano 3.4.1 for deploys.

I do have a workaround, which is to `rake tmp:cache:clear`, then `rake assets:precompile`. After restarting the unicorns, everything is good.

**Comment by frenkel** [comment]
I'm experiencing this as well, but for SCSS files references from my application.scss. Did you ever find the cause?

**Comment by senorbacon** [comment]
Yes! This was a while ago and I don’t remember the name of the library, but
we had installed a Capistrano plugin that compiled assets locally and then
uploads to the targets servers, rather than having each server compile
assets. If we ran the cap deploy command from a stale branch then we might
get that behavior. Are you using a tool like that by any chance?
