### ISSUE TITLE
Getting `NoMethodError: undefined method `+' for nil:NilClass` trying to compute an asset path

### ISSUE THREAD

**Issue by tomafro** [rails/sprockets#6]
We're running a version of basecamp against rails master (including sprockets master) and a change since 92eb3072790cef9f1e28c9670abeddcf45de8099 is raising an error trying to find an asset path.

I'm not sure the exact cause, but have traced it down to the following:

A metadata reducer for `:sass_dependencies` has recently been added here: https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L144
 
This reducer is called here when `h[k]` is nil: https://github.com/rails/sprockets/blob/master/lib/sprockets/bundle.rb#L55

I'm not sure really what this code is meant to be doing, so can't really tell what's going wrong. Happy to try and find any extra debug information or anything extra that will help. In case it's useful, here's more of the backtrace:

    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:58:in `call'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:58:in `block (2 levels) in process_bundle_reducers'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:54:in `each'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:54:in `block in process_bundle_reducers'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:53:in `each'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:53:in `reduce'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:53:in `process_bundle_reducers'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/bundle.rb:37:in `call'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/processor_utils.rb:73:in `call_processor'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/processor_utils.rb:55:in `block in call_processors'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/processor_utils.rb:54:in `reverse_each'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/processor_utils.rb:54:in `call_processors'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/loader.rb:100:in `load_asset_by_uri'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/loader.rb:40:in `block in load'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/loader.rb:167:in `fetch_asset_from_dependency_cache'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/loader.rb:33:in `load'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/cached_environment.rb:20:in `block in initialize'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/cached_environment.rb:47:in `yield'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/cached_environment.rb:47:in `load'
    .bundle/gems/bundler/gems/sprockets-9c0d8d4f4a88/lib/sprockets/base.rb:63:in `find_asset'

**Comment by josh** [comment]
Can you give https://github.com/rails/sprockets/commit/b22f6f38781da32b2734e7c79e6c587f3c66d256 a shot? Thanks!

**Comment by tomafro** [comment]
Worked great. Thanks a lot @josh.
