### ISSUE TITLE
Typo in documentation + When is the expected release of 4.0.0

### ISSUE THREAD

**Issue by ndvbd** [rails/sprockets#601]
In here: https://github.com/rails/sprockets/blob/master/UPGRADING.md
it says: "Sprockets 3 introduced the concept of a "manifest" file" - I guess you mean Sprockets 4?

2. Why the 4.0.0 hasn't been release yet? I am asking because I want to use source maps, to be able to debug bundled javascript assets, when an exception arises in production.

**Comment by schneems** [comment]
> Why the 4.0.0 hasn't been release yet

Time and effort.

> I am asking because I want to use source maps, to be able to debug bundled javascript assets, when an exception arises in production.

The beta is extremely stable, you can use it.

> it says: "Sprockets 3 introduced the concept of a "manifest" file" - I guess you mean Sprockets 4?

Sprockets 3 actually introduced the concept, we didn't make it the recommended configuration method until sprockets 4.


> When is the expected release of 4.0.0

🔜
