### ISSUE TITLE
Testing beta9, things I had trouble configuring (Better docs needed?)

### ISSUE THREAD

**Issue by jaredbeck** [rails/sprockets#615]
This issue does not follow the issue template, but @schneems asked me to open it anyway:

>> Me: .. tested beta9 .. happy to provide some feedback of the form "I can't figure out how to configure X" (in the hopes of improving docs maybe?) ..
>
> Schneems: Couldn’t hurt to write it up and stick it in an issue. Would love for better docs if someone wants to work on it.
> https://twitter.com/schneems/status/1139255964367015938

So, I can't figure out how to configure:

1. Non-concatenation
    - Non-concatenation works fine in sprockets 3
    - The docs say: "When using Rails and Sprockets in development mode, no assets are concatenated.", and
    - I have set `config.assets.debug = true` in dev env, but 
    - looking at browser network tab, concatenation still occurs. 
    - Maybe I'm writing the new `manifest.js` file incorrectly? which leads me to:
1. manifest.js
    - The error message re: manifest.js is a good start, and
    - The per-function docs .. exist,
    - but I still have no idea if I'm writing this new file correctly. 
    - Should it only contain `link*` calls?
    - When should I use link, vs dir, vs. tree?
    - Do I need to make any corresponding changes to application.js?
    - Ideally, the error message should tell me what to put in manifest.js, but I doubt that's practical, so maybe we just need more examples in the docs?
1. source maps
    - I don't even know how to tell if they're working 100%, I'm getting mixed signals ..
    - Docs say: "How do you know if source maps are working correctly? Try adding a syntax error to one of your assets and use the console to debug. Does it show the correct file and source location? Or does it reference the top level application.js file?"
    - I introduced a TypeError, and
    - I get the correct file name and line number, 
        - "TypeError: undefined is not a function redacted.source.js:5"
        - redacted is correct, and line 5 is correct
    - but the browser console says "application.source.js is not in the SourceMap"
    - To me, these are mixed signals
    - Maybe it doesn't make sense to even think about source maps until I fix non-concatenation.

So, in a few hours of testing `beta9` these are some things I found confusing. I hope this is useful.

**Comment by dmmat** [comment]
> but the browser console says "application.source.js is not in the SourceMap"

some problem in firefox with sprockets 4.0 version

**Comment by jaredbeck** [comment]
>> but the browser console says "application.source.js is not in the SourceMap"
>
> some problem in firefox with sprockets 4.0 version

Can confirm. Seems to work fine in Chrome 78, error in Firefox 70. I opened a question on SO: 
[“Error while fetching an original source” in new rails app (Sprockets 4, Firefox 70)](https://stackoverflow.com/questions/58632880/error-while-fetching-an-original-source-in-new-rails-app-sprockets-4-firefox)

**Comment by andrewkendall** [comment]
@jaredbeck did you ever find a solution to the concatenation issue?

**Comment by jaredbeck** [comment]
> .. did you ever find a solution to the concatenation issue?

No solution. I continue to observe the following:

- Sprockets 3: The effect of `config.assets.debug` matches the [rails documentation](https://guides.rubyonrails.org/configuring.html): "... disables the concatenation and compression of assets"
- Sprockets 4: The effect of `config.assets.debug` does not match the rails documentation. 
  - This appears to be an undocumented breaking change. For example, the word "debug" does not appear in the sprockets 4 changelog.
  - I have been reading the code for eg. `DebugAssetTest` to learn what it actually does, in hopes of improving the sprockets documentation.

**Comment by jaredbeck** [comment]
I haven't used sprockets for a while now (I use webpacker for everything) so I'll close this.
