### ISSUE TITLE
Link on rubygems.org/gems/sprockets goes to highjacked/lost web domain

### ISSUE THREAD

**Issue by jasnow** [rails/sprockets#619]
Sorry if this is the wrong place way to report this. 
Please comment if I need to report it elsewhere. Thanks....

When you click on "Homepage" on https://rubygems.org/gems/sprockets 
web page, you go to a highjacked/lost "getsprockets.org" domain

**Comment by rafaelfranca** [comment]
For years it is not our homepage. It is not even in the [gemspec anymore](https://github.com/rails/sprockets/blob/v3.7.2/sprockets.gemspec#L35) and I can't find a way to change on Rubygems.org [I guess they disabled the button](https://blog.rubygems.org/2019/03/08/and-then-there-was-one-metadata-links.html).

**Comment by jasnow** [comment]
Hmmm

**Comment by rafaelfranca** [comment]
It seems the next release will fix this issue. Thank you for reporting.

**Comment by jasnow** [comment]
No problem...
