### ISSUE TITLE
404 on HEAD requests

### ISSUE THREAD

**Issue by ddgromit** [rails/sprockets#63]
It seems that locally the asset pipeline only responds to GET requests, not HEAD requests. 

GET:
```
curl 'http://localhost:3000/assets/scriptcam.swf' -X GET -I
HTTP/1.1 200 OK
```

HEAD:
```
curl 'http://localhost:3000/assets/scriptcam.swf' -X HEAD -I
HTTP/1.1 404 Not Found
```

This problem came up because a library I'm using ([scriptcam.js](https://github.com/teleline/ScriptCam/blob/master/scriptcam.js#L111)) does a HEAD request to check if the file exists first before doing a full GET.  In production, it works fine because the files are served up by nginx which knows how to respond to both methods.

What is curious is based on the source code in [server.rb](https://github.com/rails/sprockets/blob/v3.2.0/lib/sprockets/server.rb#L27) that checks the request method, it should actually be responding with a 405 rather than a 404.

Not sure if this should be tagged as a feature request or bug report.  It's fairly easy to workaround but it would be nice to be able to have local mirror standard production capabilities.

**Comment by rafaelfranca** [comment]
Could you check with Rails 4.2.3.rc1?

**Comment by rafaelfranca** [comment]
It should be fixed on Rails 4.2.3.rc1, if not please report back

**Comment by ddgromit** [comment]
Confirmed that 4.2.3 allows the HEAD request to pass through to sprockets.  Thanks for the suggestion.

```
curl 'http://localhost:3000/assets/scriptcam.swf' -X HEAD -I
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain
```

However, sprockets doesn't currently support HEAD requests.  Would this be a reasonable feature to add?

**Comment by rafaelfranca** [comment]
Maybe, I think it will make sprockets behaves more like a CDN. cc @matthewd @arthurnn

**Comment by bmesuere** [comment]
Having HEAD support in sprockets would also benefit my development setup. Currently I can't properly test things in Internet Explorer because of this.
