### ISSUE TITLE
debugger not works on Sprockets 4

### ISSUE THREAD

**Issue by wbotelhos** [rails/sprockets#637]
### Expected behavior

1. Stop on `debugger`;
2. Show the original and non minified file.

### Actual behavior

1. The code does not stop on `debugger` call.
2. When an error or log occurs it appear into other js file, not on the original file:

<img width="566" alt="Screen Shot 2019-10-13 at 13 53 22" src="https://user-images.githubusercontent.com/116234/66719145-29aaab80-edc2-11e9-8cec-21d86e2a14a4.png">

In that case, the `console.log` is into a `checkout.js`, not into handlebars.
By the way, `.source` is a runtime created file?

### System configuration

- Sprockets version: `4.0.0`
- Ruby version: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`

**Comment by wbotelhos** [comment]
Hi @schneems ,

While I was creating the example application, I found the problem that is about `assets.js_compressor`. When it is change, in my case with Uglifier, it ignores `debugger`, even with `false` value:


```rb
Rails.application.config.assets.js_compressor = Uglifier.new(harmony: true)
```

I enabled it to support ES6 syntax of a needed vendor.

**Comment by rafaelfranca** [comment]
Thank you for the issue.

This seems to be the expected behavior of `Uglifier`. It removes any `debugger` call in minified javascript.

Sprockets 4 always show the minified version now if js_compressor is set. If you don't want the minified version you should not set the `js_compressor` option.
