### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by FireFart** [rails/sprockets#638]
After upgrading to sprockets 4 I get the following segfault when trying to recompile the assets. Maybe it's related to https://github.com/rails/sprockets/issues/633 ?

The image is built using docker and the latest ruby:alpine image. On another project this runs just without issues so it must be something special here

The `manifest.js` is just the default one:
```js
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```

Full output: https://pastebin.com/2m0z9aXi

**Comment by FireFart** [comment]
@schneems I can not provide you a sample app sorry, but it looks like there is a null pointer reference somewhere in the code. Is there perhaps a way to enable debug logging in sprockets to see on which file the error happens?

**Comment by schneems** [comment]
Hello! Thanks for opening up an issue. In order to move forwards with this issue I'll need an example app that reproduce the behavior (https://www.codetriage.com/example_app).
