### ISSUE TITLE
asset compilation benchmark logging was removed

### ISSUE THREAD

**Issue by bughit** [rails/sprockets#65]
https://github.com/rails/sprockets/commit/4d47c7986d7379c974d9162d9d06f22f78079614

in prior versions you could connect the sprockets logger to rails:
```ruby
    Rails.application.config.assets.configure do |env|
      env.logger = Rails.logger
    end
```
and get the following output, when a template referencing the assets was being compiled:
```
Compiled application.css  (9ms)  (pid 3727)
Compiled jquery.js  (3ms)  (pid 3727)
Compiled jquery_ujs.js  (0ms)  (pid 3727)
```

this is obviously useful for debugging slow compilation issues, so should return

**Comment by edslocomb** [comment]
I think this is a sprockets-rails issue, not a sprockets issue.  I've made a pull request to fix it here: https://github.com/rails/sprockets-rails/pull/261

**Comment by bughit** [comment]
the code that logs compilation timings was in sprockets, it was removed in the commit linked in the first post, you patch does not restore it

**Comment by edslocomb** [comment]
Hmm, you're right about that commit removing this particular message, but without a fix in sprockets-rails, I kinda doubt sprockets will be logging anything at all to the log you specify in your Rails config...

**Comment by bughit** [comment]
the ruby code in the first post sets the logger directly on sprockets, bypassing config.assets.logger

@josh @rafaelfranca  can you please bring back the logging of compilation timing

**Comment by edslocomb** [comment]
OK, sounds like you know enough to put together your own pull request.

**Comment by bughit** [comment]
@josh @rafaelfranca
I tried wrapping call to ` environment.find_all_linked_assets(filename)` in find_assets, the way it used to be, but that didn't seem to work, was never called.

So where should this benchmarking live now?

**Comment by rafaelfranca** [comment]
It is trivial to get the times from the log right now so I don't think we need the benchmark code.
