### ISSUE TITLE
lambda filter enable

### ISSUE THREAD

**Issue by epipheus** [rails/sprockets#652]
Is there any way to enable the old assets filtering capability in Sprockets 4. While I understand the reason you want to eliminate hard to understand precompilation, I have large applications and one of the things that the precompilation filter was great for was eliminating partials in a large vendor assets.  This is not easily solved now that that behavior is deprecated. Partials will not precompile without a problem.  Adding assets one by one is a horrible solution and going down each vendors assets directory by directory isn't a great solution either.

**Comment by rafaelfranca** [comment]
No. There is no way to enable it. Sorry
