### ISSUE TITLE
Ruby 2.7 deprecation warning

### ISSUE THREAD

**Issue by connorshea** [rails/sprockets#659]
### Expected behavior

I'd expect no deprecation warnings to be caused by sprockets on Ruby 2.7.

### Actual behavior

When running my test suite with Ruby 2.7 I see this deprecation warning:

```
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sprockets-4.0.0/lib/sprockets/base.rb:119: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sprockets-4.0.0/lib/sprockets/base.rb:78: warning: The called method `find_asset' is defined here
```

I tried a quick fix that changes [`base.rb`](https://github.com/rails/sprockets/blob/c4b191e70d89e9d70f19ade5faf0692054a3bd1b/lib/sprockets/base.rb#L119) to use a doublesplat, which fixes the deprecation but then causes a new one in sprockets-rails because it calls the `[]` method :P

```ruby
def [](*args, **options)
  find_asset(*args, **options)
end
```

### System configuration

- Sprockets version: 4.0.0
- Ruby version: 2.7.0

### Example App (Reproduction)

My app VideoGameList is where I'm seeing this, specifically if you run the test suite with Ruby 2.7 on my `test-ruby-2-7` branch: https://github.com/connorshea/VideoGameList/commit/ce84ad20ace4b7bbdf98b6fc5644967ed2641eb3

It'd probably be easier to just run the Sprockets test suite on Ruby 2.7, though. You'll probably see the same deprecation warning that way.

**Comment by andyjeffries** [comment]
Given that this fix hasn't been released as a new version, is there a recommended stable branch we can use in our Gemfiles to remove these warnings?

**Comment by andyjeffries** [comment]
Or can we get a 4.0.1 please?

**Comment by connorshea** [comment]
It'll hopefully be released next week :) https://github.com/rails/sprockets/pull/660#issuecomment-625886668

**Comment by nathanhinchey** [comment]
I'm still seeing this error with sprockets 4.0.2

```
home/nathanhinchey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/nathanhinchey/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:118: warning: The called method `[]' is defined here
```

**Comment by professorNim** [comment]
Like @nathanhinchey, I'm still seeing the deprecation warning with Ruby 2.7.1, Rails 6.0.3.2, sprockets-rails 3.2.1, and sprockets 4.0.2.

**Comment by Gekk3** [comment]
Thanks to @connorshea its was [fixed ](https://github.com/rails/sprockets-rails/pull/454) also in sprockets-rails. 
But the gem releases has not been updated since 2007, so if you want, you can use the master branch with the fix:
`gem "sprockets-rails", git: 'git://github.com/rails/sprockets-rails.git'`

**Comment by bookmebus** [comment]
> Thanks to @connorshea its was [fixed ](https://github.com/rails/sprockets-rails/pull/454) also in sprockets-rails.
> But the gem releases has not been updated since 2017, so if you want, you can use the master branch with the fix:
> `gem "sprockets-rails", git: 'git://github.com/rails/sprockets-rails.git'`

it works for me.

**Comment by bookmebus** [comment]
> Like @nathanhinchey, I'm still seeing the deprecation warning with Ruby 2.7.1, Rails 6.0.3.2, sprockets-rails 3.2.1, and sprockets 4.0.2.

This https://github.com/rails/sprockets/issues/659#issuecomment-659438073 work

**Comment by channainfo** [comment]
> Thanks to @connorshea its was [fixed ](https://github.com/rails/sprockets-rails/pull/454) also in sprockets-rails.
> But the gem releases has not been updated since 2017, so if you want, you can use the master branch with the fix:
> `gem "sprockets-rails", git: 'git://github.com/rails/sprockets-rails.git'`

it works for me too.

**Comment by micke** [comment]
Version 3.2.2 was released 2 days ago which fixes this issue without having to use the git version

**Comment by DillonBarker** [comment]
This worked for me now also:
`gem "sprockets-rails", git: 'git://github.com/rails/sprockets-rails.git'`
