### ISSUE TITLE
Sprockets4 / CommonJS ??

### ISSUE THREAD

**Issue by andyl** [rails/sprockets#66]
Does Sprockets4 intend to support CommonJS modules and import/export?

Right now I'm using browserify-rails - it works but is slow and doesn't handle style/image assets. My other alternative is a NodeJS build system, but I'd rather avoid that if possible.

**Comment by rafaelfranca** [comment]
Not in sprockets core, at leat for sprockets 4.0, but people can create a plugin to support it.

**Comment by runephilosof-karnovgroup** [comment]
For anyone stumbling over this, there is a different answer in #173
