### ISSUE TITLE
Segfault in find_asset

### ISSUE THREAD

**Issue by FireFart** [rails/sprockets#665]
Just fyi. We had the following snippet in our code with sprockets 3 to get the file content of a specific asset:
```ruby
Sprockets::Railtie.build_environment(Rails.application).find_asset(path, base_path: Rails.application.root.to_s)
```

Unfortunately, this segfaulted with sprockets 4.

This issue was fixed by changing the code to
```ruby
Rails.application.assets_manifest.find_sources(path).to_a.join("\n")
```

I hope this helps some people coming here via google having the same issue but maybe you also want to look into this error as it's not handled correctly. Happened with Ruby 2.7.0

Sadly I don't have the full stacktrace of the segfault any more but I think this should be reproducible

**Comment by schneems** [comment]
Hello! Thanks for opening up an issue. In order to move forwards with this issue I'll need an example app that reproduce the behavior (https://www.codetriage.com/example_app).
