### ISSUE TITLE
Test env with config.assets.debug=false does not load application. Not clear how to use in test env.

### ISSUE THREAD

**Issue by thebravoman** [rails/sprockets#671]
It is not clear how should sprockets be used in a test environment.

### Expected behavior
1.Precompile
2. Start test with config.assets.debug.
3. Have application.js loaded on the page

### Actual behavior
1. Precompile
2. Start test
3. File could be accessed with /assets/application.js as described in the documentation https://guides.rubyonrails.org/asset_pipeline.html#turning-debugging-off

but the actual link in the head is 
```
<script src="/assets/application-d270a8746ef544f413bcda90d94d9a356319c11d4ce157f6a77a1cdaecb1fe12.js"></script>
```

### System configuration

- Sprockets 3.7.2
- Ruby 2.6.5

My bug is not about the functionallity but more about the clarity. Should sprockets be used with config.assets.debug=true always or it could be used with debug=false

How should sprockets be used in a test env and what are the specifics.

Update 1:
I had to set 
config.assets.digest=false 
with 
config.assets.debug=false
to make it work

Which was odd. I understand (kind of) way, but still could not find it described

**Comment by schneems** [comment]
Hello! Thanks for opening up an issue. In order to move forwards with this issue I'll need an example app that reproduces the behavior (https://www.codetriage.com/example_app).
