### ISSUE TITLE
Timeline for 4.0 release?

### ISSUE THREAD

**Issue by ylluminate** [rails/sprockets#68]
There has been some chatter about when we may see a Sprockets 4.0 release over with [Opal](https://github.com/opal/opal) due to its reliance on Sprockets for sourcemaps.  Is there a general sense of what kind of a timeline may exist for a 4.0 drop?

**Comment by rafaelfranca** [comment]
Yes. As soon it is done, it will be released.

**Comment by ylluminate** [comment]
@rafaelfranca https://gitter.im/opal/opal?at=5597e122a6c8169b5632be83 and I think we all need this: https://pragprog.com/book/d-jrpredict/predicting-the-unpredictable ;)

**Comment by rafaelfranca** [comment]
Unfortunately we can't commit with any better time frame that: this year. Maybe before Rails 5, maybe a little bit later. Sorry if this is not enough.

**Comment by chaman** [comment]
@rafaelfranca is there any reason, this is still in beta  ?

**Comment by rafaelfranca** [comment]
It is not ready yet.
