### ISSUE TITLE
Bootstrap fonts don't use digest-urls unless @import directives use double quotes and 'application.scss' is given '.erb' extension

### ISSUE THREAD

**Issue by devonparsons** [rails/sprockets#691]
### Expected behavior

`application.scss` has the following content:

    @import 'bootstrap-sprockets';
    @import 'bootstrap';
    @import 'bootstrap-extensions';

Running `rake assets:precompile` produces `application-<digest>.css` with statements like ` src: url("/assets/bootstrap/glyphicons-halflings-regular-<digest>.eot");`

### Actual behavior

The same statement in `application-<digest>.css` does not include a digest.

However, the issue is fixed if both of the following are true: `application.scss` is renamed to `application.scss.erb`, and all three import directives are changed from single-quotes to double-quotes. 

### System configuration

`application.scss` does not contain any ruby interpolation. It DOES contain other imports, all of which are using single quotes. The three bootstrap import come after the following three directives:

    /*= require jquery-ui */
    /*= require select2 */
    /*= require select2-bootstrap */

`config/initializers/assets.rb` does not appear to have anything relevant in it.

manifest.js:

    //= link_tree ../images
    //= link application.css
    //= link application.js

Sprockets 4.0.0
Ruby 2.6.4
Rails  6.0.3.2

jquery-ui-rails 6.0.1
bootstrap-sass 3.4.1
select2-rails 4.0.3

### Example App (Reproduction)

I don't actually need anything fixed per se, because the solution I outlined above works, but I do not understand why and I would like to. I actually don't even know if this is a question for sprockets - does this have to do with the way digests are produced? Or does it have to do with how @imports work? Or how `scss.erb` files are interpreted? We've tested every subset of changes explained above and only the filename change AND all three lines getting double-quotes fixes it.  Thanks in advance if you can provide any explanation why we see this behaviour.

**Comment by schneems** [comment]
Hello! Thanks for opening up an issue. In order to move forwards with this issue I'll need an example app that reproduces the behavior (https://www.codetriage.com/example_app).
