### ISSUE TITLE
Feature Proposal - Environment dependant directives

### ISSUE THREAD

**Issue by TomasBarry** [rails/sprockets#692]
### Expected behavior

This feature proposal would address (at least) these issues:
* https://github.com/rails/sprockets/issues/666 - Need two assets compiled in rails test environment, but not compiled in rails production.
* https://github.com/rails/sprockets/issues/655 - Failing to serve assets (Asset was not declared to be precompiled)
* https://github.com/rails/sprockets/issues/542 - Rails Engine not compiling assets unless explicitly declared
* https://github.com/rails/sprockets/issues/426 - Images in engines: Asset was not declared to be precompiled in production.

I am proposing amending the `process_directives` method in [`lib/sprockets/directive_processor.rb`](https://github.com/rails/sprockets/blob/d327cde914d2b4624ad9480360036088d2a01253/lib/sprockets/directive_processor.rb#L186) which currently looks like:

```ruby
def process_directives(directives)
  directives.each do |line_number, name, *args|
    begin
      send("process_#{name}_directive", *args)
    rescue Exception => e
      e.set_backtrace(["#{@filename}:#{line_number}"] + e.backtrace)
      raise e
    end
  end
end
```

My assumption is that within this method we can have access to `Rails.env` so that we can test for the environment that would be within `args`:

```ruby
def process_directives(directives)
  directives.each do |line_number, name, *args|
    begin
      # If the target environment does not match the current environment
      # then skip the directive
      if args["target_environment"] && args["target_environment"] != Rails.env[args["target_environment"]]
        next
      end
      send("process_#{name}_directive", *args)
    rescue Exception => e
      e.set_backtrace(["#{@filename}:#{line_number}"] + e.backtrace)
      raise e
    end
  end
end
```

The API for the directive would be something along the lines of

```javascript
//= DIRECTIVE PATH EXTENSION target_environment=[production|development|test|*]
```

Example:
```javascript
//= link_directory ../stylesheets/some_specific_sheet .css target_environment=development
```

By default, the exclusion of `target_environment` would mean that the directive should apply to all environments. Perhaps multiple environments should be possible in one line too:

```javascript
//= link_directory ../stylesheets/some_specific_sheet .css target_environment=[development,test]
```

Or perhaps event an `exclude_environment` argument should be present:

```javascript
//= link_directory ../stylesheets/some_specific_sheet .css exclude_environment=production

//= link_directory ../stylesheets/some_specific_sheet .css exclude_environment=[production,test]
```

What drew me to this issue was GraphiQL from [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) which is only mounted in development and with the latest version of sprockets, the JS and CSS for GraphiQL would need to be added to the `manifest.js` file (`//= link graphiql/rails/application.css`) in all environments instead of just in development.

### Actual behavior

Directives cannot be conditional depending on the Rails environment. Specifically for `link_tree` etc, assets are either pre-compiled in all environments or in none.

### System configuration

- Sprockets version - 4.0.2
- Ruby version - 2.6.0

### Example App (Reproduction) - THIS IS IMPORTANT YOUR ISSUE LIKELY WILL NOT BE RESOLVED WITHOUT THIS

Example of the `manifest.js`:

```javascript
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css

//= link_directory ../stylesheets/some_specific_sheet_only_for_development .css target_environment=development
```

**Comment by schneems** [comment]
Sorry, i just can't. If you have a proposal please send a PR or maybe write it up in your own library that extends sprockets or sprockets-rails. It's extremely hard for me to pre-approve any discussion without also seeing the code involved to implement it.
