### ISSUE TITLE
importing third party css from node_modules not working on production

### ISSUE THREAD

**Issue by scratchoo** [rails/sprockets#693]
When we run assets:precompile on production mode, importing bootstrap from node_modules

`@import "bootstrap/dist/bootstrap.css";`

becomes

`@import url(bootstrap/dist/css/bootstrap.css)`

leading to bootstrap styles never show up! 

**Expected behavior**: Embedding the bootstrap styles from `node_modules/bootstrap/dist/css/bootstrap.css` into application.css

Rails version 6.0.3.3
yarn version 1.19.0
node version v10.16.3

**Comment by schneems** [comment]
Hello! Thanks for opening up an issue. In order to move forwards with this issue I'll need an example app that reproduces the behavior (https://www.codetriage.com/example_app).
