### ISSUE TITLE
Issue with dynamically loaded erb code compilation is js files

### ISSUE THREAD

**Issue by praWeb** [rails/sprockets#703]
### Expected behavior

On compiling erb file, it should resolve all the env mappings

### Actual behavior

They are not getting resolved, and rendering the normal source code

### System configuration

- Sprockets version: 4.0.2
- Ruby version: 2.6.6

### Reproduction steps

In html:
```ruby
<%= javascript_include_tag 'application' %>
```

Under app/assets/javascripts

application.js.erb
```ruby
//= depend_on 'check2'
function checks(){
 <%= Rails.application.assets.find_asset('check2').source %>
}
```

check2.js.erb

```ruby

function keys() {
  var key = '<%= ENV["KEY_NAME"] %>'
}
```

Say KEY_NAME = 'rubyjs'

expected application.js to render as:
```js
function checks(){
  function keys(){
    var key = 'rubyjs'
  }
}
```

But it is rendering as
```js.erb
function checks(){
  function keys(){
    var key = '<%= ENV["KEY_NAME"] %>'
  }
}
```

On compilation, application.js file is not compiling the value of ENV variable. It is simply rendering the source code as it is. Not sure, what I am exactly missing here. Any help would be much appreciated. Thanks.

**Comment by travisp** [comment]
I think outputting `source` like this, this is the expected behavior (source returns the string of the source, it doesn't compile ERB). This isn't really a sprockets issue, you'd have the same output if you did it in a rails view.

Something like this might work:
```
<%= ERB.new(Rails.application.assets.find_asset('check2').source).result %>
```

**Comment by ahorek** [comment]
I don't know what your intentions are, but even if using ```.erb``` is possible, you should know, that assets are compiled statically.

so <%= ENV["KEY_NAME"] %> will be evaluated at ```assets:precompile``` step and it will stay frozen after that. If you want to pass a dynamic variable each time you run the application, you have to use it for example as an argument to a static js function and pass KEY_NAME from a dynamic template.
