### ISSUE TITLE
SASS sourcemap :mappings is empty

### ISSUE THREAD

**Issue by julik** [rails/sprockets#71]
Currently (after 4.x merge) the Sass sourcemaps are output without :mappings. Maybe I am missing something, but Sass supports sourcemap generation since 3.3 at least (so it's been a year).

Currently the output does not contain any mappings. Proof:
https://github.com/julik/4perf/blob/master/spec/assets_spec.rb#L117

**Comment by rafaelfranca** [comment]
This should be fixed now

**Comment by julik** [comment]
Yes, confirmed (tested with 343ceb5b6635889d826bd52ec2a89c057ecb5283)
