### ISSUE TITLE
Missing GitHub Releases for 4.x

### ISSUE THREAD

**Issue by olleolleolle** [rails/sprockets#710]
### Expected behavior

I expected there would be GitHub Release records for 4.0.0 and onwards. 

### Actual behavior

The latest "Release" is shown as 3.7.2, whereas there are git tags and releases for 4.x already.

### System configuration

N/A, this is on the GitHub repository.

**Comment by ahorek** [comment]
they do exist https://github.com/rails/sprockets/releases

but 4.x releases are probably marked as prerelease, that's why 3.7.2 is still shown as the latest.

**Comment by olleolleolle** [comment]
They are not marked --pre. The version.rb has a regular 4.0.2 value in it.

**Comment by dhh** [comment]
They're there now.
