### ISSUE TITLE
Cut a new version now that Ruby 3.1 is out?

### ISSUE THREAD

**Issue by machty** [rails/sprockets#730]
https://github.com/rails/sprockets/commit/355b04c7ddd803659c5828a800ecf0949b20d80d#commitcomment-62495854

> Ruby 3.1 is out and there is currently no version pushed without emitting warnings on 3.1. Would it be possible to cut a new release please @rafaelfranca? Is there anything I can help with?

**Comment by cover** [comment]
Also related to #720, I was getting some of our specs failing with the current version of Sprockets (4.0.2) under Ruby 3.1 and Premailer. After monkey-patching with that PR code they went back to green.

It'd be nice to have a new release :crossed_fingers:

**Comment by markets** [comment]
That would be amazing! 🚀  It will be also really helpful to have this #726 merged before cutting a new release. Now that we have `jsbundling-rails` with `esbuild` support 🙌🏼 , we should properly support `esbuild` digested files as well.
