### ISSUE TITLE
Shouldn't an app be able to override assets from a gem ?  

### ISSUE THREAD

**Issue by muriloime** [rails/sprockets#733]
### Expected behavior

IMHO I think assets with same output path in gem and app should be possible, with default behavior being prioritising app asset.  

### Actual behavior

Sprockets raises `Sprockets::DoubleLinkError` with message "Multiple files with the same output path cannot be linked"

### System configuration

- Sprockets version: 4.0.2
- Ruby version: 3.0.0

### Example App (Reproduction) 

The following is an app with this error ( although my initial case is my compelling: app overriding gem asset ) 

https://github.com/muriloime/sprockets-error

Thanks

**Comment by rafaelfranca** [comment]
Not really. They should be able to override the behavior, but overriding the output path can cause very dangerous and sometimes not wanted overrides. Sprockets is behaving as intended. Thank you for the issue.

**Comment by muriloime** [comment]
Thanks for the reply @rafaelfranca, although I think in certain cases it might be useful to have this behaviour. Would you possibly accept a PR on passing this possibility as a configuration to sprockets? 

thanks

**Comment by rafaelfranca** [comment]
I think so. It depends on how complex the implementation becomes, but I think it makes sense to be configurable.

**Comment by mohamed-bahaa21** [comment]
sorry to ask, but when I get this error, how to solve it ?
I got it, after I downloaded my code on a new device, bundle install, db:migrate, 
but saw that error, on other devices bin/dev is working fine.
