### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0) on bundle rake assets:clobber

### ISSUE THREAD

**Issue by olleolleolle** [rails/sprockets#736]
### Expected behavior

I expect `bundle rake assets:clobber` to run without exceptions.

### Actual behavior

I see an exception about "keyword arguments":

> ArgumentError: wrong number of arguments (given 1, expected 0)

<details>

```
I, [2022-02-22T16:25:24.019999 #2479373]  INFO -- : Removed /home/olle/myapp/public/assets
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/home/olle/.devbox/code/myapp/gems/gems/activesupport-6.0.4.6/lib/active_support/cache/strategy/local_cache.rb:95:in `clear'
/home/olle/.devbox/code/myapp/gems/bundler/gems/sprockets-4aa1c55e6646/lib/sprockets/cache.rb:266:in `clear'
/home/olle/.devbox/code/myapp/gems/bundler/gems/sprockets-4aa1c55e6646/lib/sprockets/cache.rb:157:in `clear'
/home/olle/.devbox/code/myapp/gems/bundler/gems/sprockets-4aa1c55e6646/lib/sprockets/manifest.rb:273:in `clobber'
/home/olle/.devbox/code/myapp/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:81:in `block (3 levels) in define'
/home/olle/.devbox/code/myapp/gems/bundler/gems/sprockets-4aa1c55e6646/lib/rake/sprocketstask.rb:148:in `with_logger'
/home/olle/.devbox/code/myapp/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:80:in `block (2 levels) in define'
/home/olle/myapp/lib/tasks/no_rails_rake_tasks.rb:33:in `top_level'
/home/olle/.devbox/code/myapp/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/devbox/dependencies/ruby-ruby-2.7.5-gems-3.3.7-bundler-2.3.7-wti-2.4.11/bin/bundle:32:in `load'
/opt/devbox/dependencies/ruby-ruby-2.7.5-gems-3.3.7-bundler-2.3.7-wti-2.4.11/bin/bundle:32:in `<main>'
Tasks: TOP => assets:clobber
(See full trace by running task with --trace)
```

</details>

https://github.com/rails/sprockets/blob/4aa1c55e66463f982c05cc85b94375be52d0d3f9/lib/sprockets/cache.rb#L265-L270

I attempted to change it into this, which made my use-case work:

```ruby
def clear(options=nil)
  cache.clear(**(options || {}))
  true
end
```

### System configuration

- Sprockets version: current development version in this repo 4aa1c55e6646
- Ruby version: 2.7.5

### Example App (Reproduction) - TODO

- [ ] Add an example app, demonstrating the above failure.

Please provide an [example app](https://www.codetriage.com/example_app) that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

To create an example app, make an application locally that uses your same version of Sprockets. Add files to reproduce the problem. Once you've reproduced the problem add instructions on how to run your example app to a README.md file. Then commit everything to git and push to a new project on github. Once you've pushed your app add a link back to this issue.

[More information about example apps](https://www.codetriage.com/example_app)

**Comment by rafaelfranca** [comment]
I just tried this same command in a new Rails application and it passes. If you could provide a reproduction application I can reopen the issue. Thank you

**Comment by headshota** [comment]
I can confirm that I have the same issue on rails 6.1.6, sprockets 4.0.3, sprockets-rails 3.2.2. I ended creating a monkey patch for it:

```
module Sprockets
  class Cache
    class ReadWriteWrapper
      def clear(options={})
        cache.clear(options)
        true
      end
    end
  end
end
```
