### ISSUE TITLE
Uglifier compressor generates random variable names under 3.x

### ISSUE THREAD

**Issue by amw** [rails/sprockets#74]
This one is a bit complex, but I'll try to provide as much detail as possible. 

After upgrading from sprockets 2.12.4 to 3.0.3 (or 3.2.0) I get different digests for many of my JS files on different production machines. If I disable Uglifier compression in Rails config then the problem goes away and the digests are the same. With Uglifier enabled the differences look like this:

Instance 1
```
(function(){$(function(){var t,e,i,n,o,r,a,s,l;if
```

Instance 2
```
(function(){$(function(){var e,t,r,i,n,o,a,s,h;if
```

I have looked on the whole files and the only differences are in variable names and function parameter names.

The other relevant gems in my setup are:

```
    execjs (2.5.2)
    libv8 (3.16.14.11)
    therubyracer (0.12.2)
    uglifier (2.7.1)
    sprockets-rails (2.3.2)
```

Keeping all these gem versions constant and only changing `sprockets` version the problem is introduced somewhere between 2.12.4 and 3.0.3. It might be an issue of `sprockets-rails` though - maybe it doesn't handle `sprockets` 3.x well yet.

Don't know if it matters, but these JS files are added to sprockets like this:

```
# config/initializers/assets.rb

Rails.application.config.assets.precompile += Rails
  .root
  .join("app/assets/javascripts/page_scripts")
  .children(false)
  .map {|file|
    file = file.to_s
      .sub(/\.erb\z/, '')
      .sub(/\.coffee\z/, '')
    "page_scripts/#{file}"
  }
```

**Comment by rafaelfranca** [comment]
Which problems does this cause?

**Comment by amw** [comment]
Uglifier generates different variable names on different machines -> causing different asset hashes on different machines -> causing 404 HTTP errors.

**Comment by amw** [comment]
For a little bit more context:

There are two main strategies for asset compilation:
1. Asset compilation can be performed on a single developer/deploying machine and the compiled assets are then pushed to all the production servers. No problem here.
2. Only asset sources can be copied to production machines and the deploy process will compile the assets independently on each production server. This is how `cap production deploy:compile_assets` works. This is what I use.

Now with sprockets 3.x the `uglifier` on these different machines generates different function argument names. This causes the asset hashes to differ.

So now one production web server sends html file with request for `asset-abc.js`. User's web browser sends request for that JS file, but it goes to a different web server. That web server has only `asset-zxc.js` available so it responds with 404 error code.

I use capistrano and bundler so the gem versions are all the same on each production server. Somehow the shortened function arguments produced by `uglifier` under sprockets 3.x are not generated deterministically.

**Comment by schneems** [comment]
Can you give me a project that reproduces this problem?

**Comment by rafaelfranca** [comment]
I'm using sprockets 3 in a large Rails application that uses uglifier too and I'm reproducing this issue. It may be something in your application that is causing. Let us know if you are able to make a project that reproduces the problem.

**Comment by amw** [comment]
I have upgraded my project again and I'm no longer able to reproduce this issue.

Just to be sure I've added a Capistrano deploy task that verifies digests match after each assets compilation. If I ever run into this issue again I will let you know.

**Comment by jeremymarc** [comment]
had the same issue: when deploying to production, the digest was incorrect for my application.js file. 
I fixed it by disabling uglifier mangle:

```
config.assets.js_compressor = Uglifier.new(mangle: false)
```

**Comment by amw** [comment]
Mangling can shorten the code by quite a lot. I'm pretty verbose when naming variables and arguments. I'd rather get to the bottom of this issue than disable mangling. Fortunately my environment seems to be alright now.

I have a Capistrano task that checks asset digests during each deploy. Maybe you'll find it useful: https://gist.github.com/amw/895ff841e71b800f255f

**Comment by tubaxenor** [comment]
We have encounter the same issue when having following scenario on our rails' application.js after upgrade from sprockets 2.x to  sprockets 3.x: 

1. A new server spins up with no assets at all
2. Run `RAILS_ENV=production bundle exec rake assets:precompile`
3. The first created application.js is having different variable names compares to old ones, which also causing different digest generated.

But if we change something on application.js and then precompile again on all servers including the newest one, var name then become consistent, also the digest.

Does anything changed on compressing strategy when no previous public assets generated?

**Comment by gmhawash** [comment]
I am seeing this issue with Sprocket 2.0.0.  I just added a new server to my EC2 stack and they are ending up with different names for the variables.  Are there any fixes for this?
