### ISSUE TITLE
We cannot test on Rack 3

### ISSUE THREAD

**Issue by ioquatix** [rails/sprockets#753]
https://github.com/rails/sprockets/blob/e36620745d7150fc33eccffeaf79e741a774499c/sprockets.gemspec#L14

Because of this line.

https://github.com/rails/rails/pull/45741

**Comment by p8** [comment]
I think you can create a fork of sprockets and link to that in the Rails Gemfile.
Similar to:
https://github.com/rails/rails/blob/8b0499aa1d3fcfb0f42ded41990bc91b50821a84/Gemfile#L93
