### ISSUE TITLE
Remove Rack < 3 dependency from Sprockets

### ISSUE THREAD

**Issue by captbrando** [rails/sprockets#766]
### Expected behavior

Sprockets should use current versions of Rack.

### Actual behavior

Sprockets dependencies for 4.1.1 require rack version < 3.

### System configuration

- Sprockets version: 4.1.1
- Ruby version: 2.7.6

### Example App (Reproduction) - THIS IS IMPORTANT YOUR ISSUE LIKELY WILL NOT BE RESOLVED WITHOUT THIS

All you need to do is look at Gemfile.lock for your project to see the stuck dependency.

**Comment by chadlwilson** [comment]
This is fixed in 4.2.0.
