### ISSUE TITLE
sprockets 4.2.0 on rubygems.org

### ISSUE THREAD

**Issue by sokkalf** [rails/sprockets#774]
I did a bundle update, and got sprockets 4.2.0 - with which my asset pipeline broke. I'm not excatly _why_ it broke, but I went to this repo to read the documentation for the latest version and see what changes I needed to make. However, the latest released version based on this repository is 4.1.1 (which is the version I upgraded from). I see that 4.2.0 is released on rubygems.org. Is this in error?

### Expected behavior

bundle update should fetch the latest version.

### Actual behavior

bundle update fetches a seemingly unreleased version (??), which broke the app.

### System configuration

- Sprockets version
4.2.0
- Ruby version
3.1.3

**Comment by hahmed** [comment]
@sokkalf the latest version is indeed 4.2.0 that's the latest tagged version (and commit) https://github.com/rails/sprockets/releases/tag/v4.2.0

It's missing a release on github though, which is what I think you meant -- https://github.com/rails/sprockets/releases

**Comment by sokkalf** [comment]
Ah, didn't think to check for tags. Thanks! I'll investigate closer then. I suspect this really is because of a conflict with another gem, as 4.2.0 worked fine on another project.
