### ISSUE TITLE
Sprockets compiles from "*.jpeg" to "*.jpg" that creates an error

### ISSUE THREAD

**Issue by loqimean** [rails/sprockets#775]
### Expected behavior

`hello.jpeg` is founded as `hello.jpg` OR compiled as it is: `hello.jpeg`

### Actual behavior

Instead of this Sprockets on production compiles my file called `hello.jpeg` to file `hello.jpg` and because of it I have an error on my production where I have the next chunk of code: `image_path("hello.jpeg")`, because of file are stored with *.jpeg extension, but compiled as *.jpg

### System configuration

- Sprockets version - 2.0.0
- Ruby version - 6.0.3

### Example App (Reproduction)
Will be added soon

**Comment by rubydesign** [comment]
I second that.  Must be a very recent change.

image.jpeg gets compiled to image.jpg

and then `image_tag("image.jpeg") ` throws and error, but only in product (just the way we love it, error only in production :-)

Reverting, i would suggest even yanking

**Comment by chadlwilson** [comment]
I think this is fixed in #781 released in 4.2.1
