### ISSUE TITLE
Custom cache directory ?

### ISSUE THREAD

**Issue by hopewise** [rails/sprockets#779]
How to change the cache directory? I am using my app in a read-only file system, and I am getting erros, such as:

```
Read-only file system @ apply2files - /app/tmp/cache/assets/sprockets/v3.0/pF/pFfFjKIa9QwojrufCxxwrRGvRT5Bkq14Et0i6oxzMs8.cache
```

**Comment by jeremy** [comment]
You can set your own cache store, including setting a file store with a different path. Here's how the default file cache is set up:
https://github.com/rails/sprockets-rails/blob/065cbe83989c44019eca7161782ed4fdb6473517/lib/sprockets/railtie.rb#L152-L158
