### ISSUE TITLE
erb is processed after `require`s?

### ISSUE THREAD

**Issue by kitop** [rails/sprockets#9]
I'm trying to dynamically require files on a certain directory (that's already added to the load path),  doing this:
```
/*
<% Dir.glob(Rails.root.join('app', 'components', '*')) do |component_dir| %>
<% component = File.basename component_dir %>
 *= require <%=component%>/<%=component%>
<% end %>
*/
```
I was expecting `erb` to be processed before the actual `require` call, but I'm getting this error:
`couldn't find file '<%=component%>/<%=component%>'`

It seems like it's processing the `erb` after requiring the rest of the files.

Is that on purpose? If so is there a way to somehow dinamically require the files there?

This is on the context of a rails engine, where I'd like to have one file on the engine that dinamically requires files in the application directory.
I can't use `require_tree` because that `app/components` directory is the one added on the path.

**Comment by josh** [comment]
Try this instead.

``` erb
<% Dir.glob(Rails.root.join('app', 'components', '*')) do |component_dir|
  component = File.basename component_dir
 require_asset "#{component}/#{component}"
end %>
```

**Comment by kitop** [comment]
That worked like a charm!!! Thanks @josh!
