### ISSUE TITLE
sprockets returning nil

### ISSUE THREAD

**Issue by Thermatix** [rails/sprockets#95]
First of all, here's my code as a [gist](https://gist.github.com/Thermatix/6c7d579a4962cc905d72)

Sprockets only returns nil, I've done this 
```ruby
 settings.assets.instance_exec(file_name,extention) do |file_name,extention|
	puts 'assets'
	puts @assets
	@assets[cache_key_for("#{file_name}#{extention}", {bundle: true})]
end
```

To see what files sprockets has and `@assets`  is just `{}`

I know however that file name is being correctly passed becuase:
```ruby
puts params[:captures].to_s # in my asset routes output
  #=> ["application", ".css"]
  #=> ["application", ".js"]
```
It also doesn't raise any errors.

I don't know what's wrong or how to fix this, what do I do?

**Comment by schneems** [comment]
What version of sprockets are you using and was this working before?

**Comment by Thermatix** [comment]
I'm currently using sprockets "2.12.4", I have no choice but to use this older version because a library I want to use (react.rb) won't work with sprockets "3.0.0" or above and  "2.12.4" is the highest version I can use. 

And it was never working :(

**Comment by schneems** [comment]
Thanks for the report can you give me an example github repo with a Gemfile and some assets that I can clone and run to reproduce the problem?

**Comment by Thermatix** [comment]
If you take out the Registry line and then just require + include the file, it should just work in a normal sinatra app, umm but an actual repo will have to wait as I'm about to leave work.

The gem version are
"sinatra", "1.4.6"
"sprockets", "2.12.4"
"sass", "3.4.13"
"yui-compressor", "0.12.0"
"opal", "~> 0.6"
"react.rb", "~> 0.3"

I can try building a small micro project for this tomorrow.
